import ZkfProtocolProofs.Common

namespace ZkfProtocolProofs

/-- Generated by `scripts/generate_protocol_parameter_snapshots.py`. -/
def groth16Snapshot : Groth16SurfaceSnapshot := {
  surface := "groth16",
  backend := "arkworks-groth16",
  field := "bn254",
  curve := "bn254",
  scheme := "groth16",
  setupBlobVersion := 1,
  setupProvenance := "trusted-imported-blob",
  securityBoundary := "trusted-imported",
  developmentBoundary := "development-only",
  requiredCompiledMetadata := ["curve", "scheme", "setup_blob_version", "setup_deterministic", "setup_seed_source", "groth16_setup_provenance", "groth16_setup_security_boundary", "groth16_setup_blob_path"],
  requiredProofMetadata := ["curve", "scheme", "prove_deterministic", "prove_seed_source"],
  verifierChecks := ["compiled_backend_matches", "artifact_backend_matches", "program_digest_matches", "verification_key_matches_compiled_setup_blob"],
  rustFiles := [
  { path := "zkf-backends/src/arkworks.rs", sha256 := "63893118a5617b14ee979a3995cedf1a2aa423d3ca41b3dd005ed6c31c1e0b28" },
  { path := "zkf-backends/src/lib_non_hax.rs", sha256 := "31f3e1756ff867c6848e49a4f57942e4c5473d8411e1df9af4d96d19973dcb3a" }
]
}

/-- Generated by `scripts/generate_protocol_parameter_snapshots.py`. -/
def friSnapshot : FriSurfaceSnapshot := {
  surface := "fri",
  backend := "plonky3",
  scheme := "stark",
  pcs := "fri",
  plonky3Version := "0.4.2",
  seedDerivation := "program-digest",
  wrapperSurface := "stark-to-groth16",
  wrapperStatuses := ["wrapped-v2", "wrapped-v3"],
  wrapperStrategies := ["direct-fri-v2", "nova-compressed-v3"],
  wrapperSemantics := ["fri-verifier-circuit", "nova-compressed-attestation-binding"],
  sourceVerificationSemantics := ["circuit-replayed", "host-compressed-check"],
  requiredProofMetadata := ["field", "scheme", "pcs", "seed"],
  rustFiles := [
  { path := "zkf-backends/src/plonky3.rs", sha256 := "fc21fab3ac376c33052f078e446a02cb4227c1fa782ce2f9d981b45e5a2fd63d" },
  { path := "zkf-backends/src/wrapping/stark_to_groth16.rs", sha256 := "b47897b338965d89f657977680d2d468da77c94b4a9024ede9ca448bc830ed45" }
]
}

/-- Generated by `scripts/generate_protocol_parameter_snapshots.py`. -/
def novaSnapshot : NovaSurfaceSnapshot := {
  surface := "nova-hypernova",
  backend := "nova-native",
  compileScheme := "nova-ivc",
  foldScheme := "nova-ivc-fold",
  nativeMode := "recursive-snark-v2",
  profiles := ["classic", "hypernova"],
  primaryCurve := "pallas",
  secondaryCurve := "vesta",
  curveCycle := "pallas-vesta",
  stepArity := 1,
  compressedFoldSupportedProfiles := ["classic"],
  requiredCompiledMetadata := ["nova_native_mode", "nova_profile", "nova_curve_cycle", "nova_step_arity", "scheme", "mode"],
  requiredSingleStepProofMetadata := ["nova_native_mode", "nova_steps", "nova_curve_cycle", "nova_profile"],
  requiredFoldProofMetadata := ["nova_native_mode", "nova_steps", "nova_curve_cycle", "nova_profile", "nova_compressed", "nova_ivc_in", "nova_ivc_out", "nova_ivc_initial_state", "nova_ivc_final_state"],
  rustFiles := [
  { path := "zkf-backends/src/nova_native.rs", sha256 := "5c03282a423e5bb9b10b97c4cbded45a43123afc1d0f53c675e508c23f0df098" }
]
}

end ZkfProtocolProofs
