(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

Record SpecWitnessSignal_record : Type :=
  {
    SpecWitnessSignal_f_constant_value : t_Option ((t_SpecFieldValue));
    SpecWitnessSignal_f_required : bool;
  }.



#[export] Instance settable_SpecWitnessSignal_record : Settable _ :=
  settable! (Build_SpecWitnessSignal_record) <SpecWitnessSignal_f_constant_value; SpecWitnessSignal_f_required>.

Record SpecWitnessAssignment_record : Type :=
  {
    SpecWitnessAssignment_f_target_signal_index : t_usize;
    SpecWitnessAssignment_f_expr : t_SpecKernelExpr;
  }.



#[export] Instance settable_SpecWitnessAssignment_record : Settable _ :=
  settable! (Build_SpecWitnessAssignment_record) <SpecWitnessAssignment_f_target_signal_index; SpecWitnessAssignment_f_expr>.

Record SpecWitnessHint_record : Type :=
  {
    SpecWitnessHint_f_target_signal_index : t_usize;
    SpecWitnessHint_f_source_signal_index : t_usize;
  }.



#[export] Instance settable_SpecWitnessHint_record : Settable _ :=
  settable! (Build_SpecWitnessHint_record) <SpecWitnessHint_f_target_signal_index; SpecWitnessHint_f_source_signal_index>.

Record SpecWitnessGenerationProgram_record : Type :=
  {
    SpecWitnessGenerationProgram_f_kernel_program : t_SpecKernelProgram;
    SpecWitnessGenerationProgram_f_signals : t_Vec ((t_SpecWitnessSignal)) ((t_Global));
    SpecWitnessGenerationProgram_f_assignments : t_Vec ((t_SpecWitnessAssignment)) ((t_Global));
    SpecWitnessGenerationProgram_f_hints : t_Vec ((t_SpecWitnessHint)) ((t_Global));
  }.





#[export] Instance settable_SpecWitnessGenerationProgram_record : Settable _ :=
  settable! (Build_SpecWitnessGenerationProgram_record) <SpecWitnessGenerationProgram_f_kernel_program; SpecWitnessGenerationProgram_f_signals; SpecWitnessGenerationProgram_f_assignments; SpecWitnessGenerationProgram_f_hints>.

Record SpecWitnessGenerationError_MissingRequiredSignal_record : Type :=
  {
    SpecWitnessGenerationError_MissingRequiredSignal_f_signal_index : t_usize;
  }.


#[export] Instance settable_SpecWitnessGenerationError_MissingRequiredSignal_record : Settable _ :=
  settable! (Build_SpecWitnessGenerationError_MissingRequiredSignal_record) <SpecWitnessGenerationError_MissingRequiredSignal_f_signal_index>.
Record SpecWitnessGenerationError_UnsupportedWitnessSolve_record : Type :=
  {
    SpecWitnessGenerationError_UnsupportedWitnessSolve_f_unresolved_signal_indices : t_Vec ((t_usize)) ((t_Global));
  }.


#[export] Instance settable_SpecWitnessGenerationError_UnsupportedWitnessSolve_record : Settable _ :=
  settable! (Build_SpecWitnessGenerationError_UnsupportedWitnessSolve_record) <SpecWitnessGenerationError_UnsupportedWitnessSolve_f_unresolved_signal_indices>.
Record SpecWitnessGenerationError_AmbiguousLookup_record : Type :=
  {
    SpecWitnessGenerationError_AmbiguousLookup_f_constraint_index : t_usize;
    SpecWitnessGenerationError_AmbiguousLookup_f_table_index : t_usize;
  }.



#[export] Instance settable_SpecWitnessGenerationError_AmbiguousLookup_record : Settable _ :=
  settable! (Build_SpecWitnessGenerationError_AmbiguousLookup_record) <SpecWitnessGenerationError_AmbiguousLookup_f_constraint_index; SpecWitnessGenerationError_AmbiguousLookup_f_table_index>.
Inductive t_SpecWitnessGenerationError : Type :=
| SpecWitnessGenerationError_MissingRequiredSignal : SpecWitnessGenerationError_MissingRequiredSignal_record  -> _
| SpecWitnessGenerationError_UnsupportedWitnessSolve : SpecWitnessGenerationError_UnsupportedWitnessSolve_record  -> _
| SpecWitnessGenerationError_KernelCheck : t_SpecKernelCheckError -> _
| SpecWitnessGenerationError_AmbiguousLookup : SpecWitnessGenerationError_AmbiguousLookup_record  -> _.





Definition generate_non_blackbox_witness_unchecked (program : t_SpecWitnessGenerationProgram) (inputs : t_Slice t_Option ((t_SpecFieldValue))) : t_Result ((t_SpecKernelWitness)) ((t_SpecWitnessGenerationError)) :=
  generate_non_blackbox_witness_unchecked_runtime (program) (inputs).

Definition validate_generated_witness (program : t_SpecWitnessGenerationProgram) (witness : t_SpecKernelWitness) : t_Result ((t_SpecKernelWitness)) ((t_SpecWitnessGenerationError)) :=
  match check_program (f_kernel_program program) (witness) with
  | Result_Ok (()) =>
    Result_Ok (witness)
  | Result_Err (error) =>
    Result_Err (SpecWitnessGenerationError_KernelCheck (error))
  end.

Definition generate_non_blackbox_witness (program : t_SpecWitnessGenerationProgram) (inputs : t_Slice t_Option ((t_SpecFieldValue))) : t_Result ((t_SpecKernelWitness)) ((t_SpecWitnessGenerationError)) :=
  match generate_non_blackbox_witness_unchecked (program) (inputs) with
  | Result_Ok (witness) =>
    validate_generated_witness (program) (witness)
  | Result_Err (error) =>
    Result_Err (error)
  end.
