(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

Inductive t_SpecTransformVisibility : Type :=
| SpecTransformVisibility_Public
| SpecTransformVisibility_Constant
| SpecTransformVisibility_Private.




Record SpecTransformSignal_record : Type :=
  {
    SpecTransformSignal_f_signal_index : t_usize;
    SpecTransformSignal_f_sort_key : t_usize;
    SpecTransformSignal_f_visibility : t_SpecTransformVisibility;
    SpecTransformSignal_f_constant_value : t_Option ((t_SpecFieldValue));
    SpecTransformSignal_f_required : bool;
  }.






#[export] Instance settable_SpecTransformSignal_record : Settable _ :=
  settable! (Build_SpecTransformSignal_record) <SpecTransformSignal_f_signal_index; SpecTransformSignal_f_sort_key; SpecTransformSignal_f_visibility; SpecTransformSignal_f_constant_value; SpecTransformSignal_f_required>.

Record SpecTransformHint_record : Type :=
  {
    SpecTransformHint_f_target_signal_index : t_usize;
    SpecTransformHint_f_source_signal_index : t_usize;
  }.



#[export] Instance settable_SpecTransformHint_record : Settable _ :=
  settable! (Build_SpecTransformHint_record) <SpecTransformHint_f_target_signal_index; SpecTransformHint_f_source_signal_index>.

Record SpecNormalizationReport_record : Type :=
  {
    SpecNormalizationReport_f_algebraic_rewrites : t_u32;
    SpecNormalizationReport_f_constant_folds : t_u32;
    SpecNormalizationReport_f_dead_signals_removed : t_u32;
  }.




#[export] Instance settable_SpecNormalizationReport_record : Settable _ :=
  settable! (Build_SpecNormalizationReport_record) <SpecNormalizationReport_f_algebraic_rewrites; SpecNormalizationReport_f_constant_folds; SpecNormalizationReport_f_dead_signals_removed>.

Record SpecOptimizeReport_record : Type :=
  {
    SpecOptimizeReport_f_folded_expr_nodes : t_usize;
    SpecOptimizeReport_f_deduplicated_constraints : t_usize;
    SpecOptimizeReport_f_removed_tautology_constraints : t_usize;
    SpecOptimizeReport_f_removed_private_signals : t_usize;
  }.





#[export] Instance settable_SpecOptimizeReport_record : Settable _ :=
  settable! (Build_SpecOptimizeReport_record) <SpecOptimizeReport_f_folded_expr_nodes; SpecOptimizeReport_f_deduplicated_constraints; SpecOptimizeReport_f_removed_tautology_constraints; SpecOptimizeReport_f_removed_private_signals>.

Definition zero_spec_value '(_ : unit) : t_SpecFieldValue :=
  spec_field_value_zero (tt).

Definition normalize_spec_value (value : t_SpecFieldValue) (field : t_FieldId) : t_SpecFieldValue :=
  normalize (value) (field).

Definition add_spec_values (lhs : t_SpecFieldValue) (rhs : t_SpecFieldValue) (field : t_FieldId) : t_SpecFieldValue :=
  Add_f_add (lhs) (rhs) (field).

Definition sub_spec_values (lhs : t_SpecFieldValue) (rhs : t_SpecFieldValue) (field : t_FieldId) : t_SpecFieldValue :=
  Sub_f_sub (lhs) (rhs) (field).

Definition mul_spec_values (lhs : t_SpecFieldValue) (rhs : t_SpecFieldValue) (field : t_FieldId) : t_SpecFieldValue :=
  Mul_f_mul (lhs) (rhs) (field).

Definition div_spec_values (lhs : t_SpecFieldValue) (rhs : t_SpecFieldValue) (field : t_FieldId) : t_Option ((t_SpecFieldValue)) :=
  Div_f_div (lhs) (rhs) (field).

Definition spec_values_equal (lhs : t_SpecFieldValue) (rhs : t_SpecFieldValue) (field : t_FieldId) : bool :=
  PartialEq_f_eq (lhs) (rhs) (field).

Definition spec_value_is_boolean (value : t_SpecFieldValue) (field : t_FieldId) : bool :=
  is_boolean (value) (field).

Definition spec_value_fits_bits (value : t_SpecFieldValue) (bits : t_u32) (field : t_FieldId) : bool :=
  fits_bits (value) (bits) (field).

Definition spec_value_is_zero_raw (value : t_SpecFieldValue) : bool :=
  spec_field_value_is_zero_raw (value).

Definition spec_value_is_one_raw (value : t_SpecFieldValue) : bool :=
  spec_field_value_is_one_raw (value).

Definition transform_signal_value (witness : t_SpecKernelWitness) (signal_index : t_usize) (field : t_FieldId) : t_Result ((t_SpecFieldValue)) ((t_SpecKernelCheckError)) :=
  match impl__get (f_deref (f_values witness)) (signal_index) with
  | Option_Some (Option_Some (value)) =>
    Result_Ok (normalize_spec_value (value) (field))
  | _ =>
    Result_Err (SpecKernelCheckError_MissingSignal {| SpecKernelCheckError_MissingSignal_f_signal_index := (signal_index) |})
  end.

Record SpecTransformExpr_Const_record : Type :=
  {
    SpecTransformExpr_Const_f_value : t_SpecFieldValue;
    SpecTransformExpr_Const_f_sort_key : t_usize;
  }.



#[export] Instance settable_SpecTransformExpr_Const_record : Settable _ :=
  settable! (Build_SpecTransformExpr_Const_record) <SpecTransformExpr_Const_f_value; SpecTransformExpr_Const_f_sort_key>.
Record SpecTransformExpr_Signal_record : Type :=
  {
    SpecTransformExpr_Signal_f_signal_index : t_usize;
    SpecTransformExpr_Signal_f_sort_key : t_usize;
  }.



#[export] Instance settable_SpecTransformExpr_Signal_record : Settable _ :=
  settable! (Build_SpecTransformExpr_Signal_record) <SpecTransformExpr_Signal_f_signal_index; SpecTransformExpr_Signal_f_sort_key>.
Inductive t_SpecTransformExpr : Type :=
| SpecTransformExpr_Const : SpecTransformExpr_Const_record  -> _
| SpecTransformExpr_Signal : SpecTransformExpr_Signal_record  -> _
| SpecTransformExpr_Add : t_Vec ((t_SpecTransformExpr)) ((t_Global)) -> _
| SpecTransformExpr_Sub : t_SpecTransformExpr -> t_SpecTransformExpr -> _
| SpecTransformExpr_Mul : t_SpecTransformExpr -> t_SpecTransformExpr -> _
| SpecTransformExpr_Div : t_SpecTransformExpr -> t_SpecTransformExpr -> _.







Fixpoint insert_signal_sorted_from (signal : t_SpecTransformSignal) (sorted : t_Slice t_SpecTransformSignal) (inserted : bool) (result : t_Vec ((t_SpecTransformSignal)) ((t_Global))) : t_Vec ((t_SpecTransformSignal)) ((t_Global)) :=
  match impl__split_first (sorted) with
  | Option_Some ((item,remaining)) =>
    let (result,inserted) := if
      andb (f_not (inserted)) (f_lt (f_sort_key signal) (f_sort_key item))
    then
      let result := impl_1__push (result) (f_clone (signal)) in
      (result,(true : bool))
    else
      (result,inserted) in
    let result := impl_1__push (result) (f_clone (item)) in
    insert_signal_sorted_from (signal) (remaining) (inserted) (result)
  | Option_None =>
    let result := if
      f_not (inserted)
    then
      let result := impl_1__push (result) (signal) in
      result
    else
      result in
    result
  end.

Fixpoint contains_signal_index (signals : t_Slice t_usize) (signal_index : t_usize) : bool :=
  match impl__split_first (signals) with
  | Option_Some ((current_signal_index,remaining_signals)) =>
    if
      f_eq (current_signal_index) (signal_index)
    then
      (true : bool)
    else
      contains_signal_index (remaining_signals) (signal_index)
  | Option_None =>
    (false : bool)
  end.

Fixpoint collect_signal_indices_from_signals (signals : t_Slice t_SpecTransformSignal) (kept_signal_indices : t_Vec ((t_usize)) ((t_Global))) : t_Vec ((t_usize)) ((t_Global)) :=
  match impl__split_first (signals) with
  | Option_Some ((signal,remaining_signals)) =>
    let kept_signal_indices := impl_1__push (kept_signal_indices) (f_signal_index signal) in
    collect_signal_indices_from_signals (remaining_signals) (kept_signal_indices)
  | Option_None =>
    kept_signal_indices
  end.

Record SpecTransformConstraint_Equal_record : Type :=
  {
    SpecTransformConstraint_Equal_f_lhs : t_SpecTransformExpr;
    SpecTransformConstraint_Equal_f_rhs : t_SpecTransformExpr;
    SpecTransformConstraint_Equal_f_label_key : t_usize;
  }.




#[export] Instance settable_SpecTransformConstraint_Equal_record : Settable _ :=
  settable! (Build_SpecTransformConstraint_Equal_record) <SpecTransformConstraint_Equal_f_lhs; SpecTransformConstraint_Equal_f_rhs; SpecTransformConstraint_Equal_f_label_key>.
Record SpecTransformConstraint_Boolean_record : Type :=
  {
    SpecTransformConstraint_Boolean_f_signal_index : t_usize;
    SpecTransformConstraint_Boolean_f_label_key : t_usize;
  }.



#[export] Instance settable_SpecTransformConstraint_Boolean_record : Settable _ :=
  settable! (Build_SpecTransformConstraint_Boolean_record) <SpecTransformConstraint_Boolean_f_signal_index; SpecTransformConstraint_Boolean_f_label_key>.
Record SpecTransformConstraint_Range_record : Type :=
  {
    SpecTransformConstraint_Range_f_signal_index : t_usize;
    SpecTransformConstraint_Range_f_bits : t_u32;
    SpecTransformConstraint_Range_f_label_key : t_usize;
  }.




#[export] Instance settable_SpecTransformConstraint_Range_record : Settable _ :=
  settable! (Build_SpecTransformConstraint_Range_record) <SpecTransformConstraint_Range_f_signal_index; SpecTransformConstraint_Range_f_bits; SpecTransformConstraint_Range_f_label_key>.
Inductive t_SpecTransformConstraint : Type :=
| SpecTransformConstraint_Equal : SpecTransformConstraint_Equal_record  -> _
| SpecTransformConstraint_Boolean : SpecTransformConstraint_Boolean_record  -> _
| SpecTransformConstraint_Range : SpecTransformConstraint_Range_record  -> _.




Record SpecTransformAssignment_record : Type :=
  {
    SpecTransformAssignment_f_target_signal_index : t_usize;
    SpecTransformAssignment_f_expr : t_SpecTransformExpr;
  }.



#[export] Instance settable_SpecTransformAssignment_record : Settable _ :=
  settable! (Build_SpecTransformAssignment_record) <SpecTransformAssignment_f_target_signal_index; SpecTransformAssignment_f_expr>.

Record SpecTransformProgram_record : Type :=
  {
    SpecTransformProgram_f_field : t_FieldId;
    SpecTransformProgram_f_signals : t_Vec ((t_SpecTransformSignal)) ((t_Global));
    SpecTransformProgram_f_constraints : t_Vec ((t_SpecTransformConstraint)) ((t_Global));
    SpecTransformProgram_f_assignments : t_Vec ((t_SpecTransformAssignment)) ((t_Global));
    SpecTransformProgram_f_hints : t_Vec ((t_SpecTransformHint)) ((t_Global));
  }.






#[export] Instance settable_SpecTransformProgram_record : Settable _ :=
  settable! (Build_SpecTransformProgram_record) <SpecTransformProgram_f_field; SpecTransformProgram_f_signals; SpecTransformProgram_f_constraints; SpecTransformProgram_f_assignments; SpecTransformProgram_f_hints>.

Record SpecNormalizationResult_record : Type :=
  {
    SpecNormalizationResult_f_program : t_SpecTransformProgram;
    SpecNormalizationResult_f_report : t_SpecNormalizationReport;
  }.



#[export] Instance settable_SpecNormalizationResult_record : Settable _ :=
  settable! (Build_SpecNormalizationResult_record) <SpecNormalizationResult_f_program; SpecNormalizationResult_f_report>.

Record SpecOptimizeResult_record : Type :=
  {
    SpecOptimizeResult_f_program : t_SpecTransformProgram;
    SpecOptimizeResult_f_report : t_SpecOptimizeReport;
  }.



#[export] Instance settable_SpecOptimizeResult_record : Settable _ :=
  settable! (Build_SpecOptimizeResult_record) <SpecOptimizeResult_f_program; SpecOptimizeResult_f_report>.

Definition zero_spec_expr '(_ : unit) : t_SpecTransformExpr :=
  SpecTransformExpr_Const {| SpecTransformExpr_Const_f_value := (zero_spec_value (tt)); SpecTransformExpr_Const_f_sort_key := ((0 : t_usize)) |}.

Definition expr_order_rank (expr : t_SpecTransformExpr) : t_usize :=
  match expr with
  | SpecTransformExpr_Add (_) =>
    (0 : t_usize)
  | SpecTransformExpr_Const =>
    (1 : t_usize)
  | SpecTransformExpr_Div (_) (_) =>
    (2 : t_usize)
  | SpecTransformExpr_Mul (_) (_) =>
    (3 : t_usize)
  | SpecTransformExpr_Signal =>
    (4 : t_usize)
  | SpecTransformExpr_Sub (_) (_) =>
    (5 : t_usize)
  end.

Definition expr_sort_key (expr : t_SpecTransformExpr) : t_usize :=
  match expr with
  | SpecTransformExpr_Const (sort_key)
  | SpecTransformExpr_Signal (sort_key) =>
    sort_key
  | _ =>
    (0 : t_usize)
  end.

Definition expr_order_lt (lhs : t_SpecTransformExpr) (rhs : t_SpecTransformExpr) : bool :=
  run (let lhs_rank := expr_order_rank (lhs) in
  let rhs_rank := expr_order_rank (rhs) in
  let _ := if
    f_ne (lhs_rank) (rhs_rank)
  then
    let hoist59 := ControlFlow_Break (f_lt (lhs_rank) (rhs_rank)) in
    ControlFlow_Continue (never_to_any (hoist59))
  else
    ControlFlow_Continue (tt) in
  ControlFlow_Continue (f_lt (expr_sort_key (lhs)) (expr_sort_key (rhs)))).

Definition constraint_order_variant (constraint : t_SpecTransformConstraint) : t_usize :=
  match constraint with
  | SpecTransformConstraint_Equal =>
    (0 : t_usize)
  | SpecTransformConstraint_Boolean =>
    (1 : t_usize)
  | SpecTransformConstraint_Range =>
    (2 : t_usize)
  end.

Definition constraint_order_lt (lhs : t_SpecTransformConstraint) (rhs : t_SpecTransformConstraint) : bool :=
  run (let lhs_variant := constraint_order_variant (lhs) in
  let rhs_variant := constraint_order_variant (rhs) in
  let _ := if
    f_ne (lhs_variant) (rhs_variant)
  then
    let hoist60 := ControlFlow_Break (f_lt (lhs_variant) (rhs_variant)) in
    ControlFlow_Continue (never_to_any (hoist60))
  else
    ControlFlow_Continue (tt) in
  match (lhs,rhs) with
  | (SpecTransformConstraint_Equal (lhs_expr) (lhs_rhs) (lhs_label),SpecTransformConstraint_Equal (rhs_expr) (rhs_rhs) (rhs_label)) =>
    let _ := if
      expr_order_lt (lhs_expr) (rhs_expr)
    then
      let hoist61 := ControlFlow_Break ((true : bool)) in
      ControlFlow_Continue (never_to_any (hoist61))
    else
      ControlFlow_Continue (tt) in
    let _ := if
      expr_order_lt (rhs_expr) (lhs_expr)
    then
      let hoist62 := ControlFlow_Break ((false : bool)) in
      ControlFlow_Continue (never_to_any (hoist62))
    else
      ControlFlow_Continue (tt) in
    let _ := if
      expr_order_lt (lhs_rhs) (rhs_rhs)
    then
      let hoist63 := ControlFlow_Break ((true : bool)) in
      ControlFlow_Continue (never_to_any (hoist63))
    else
      ControlFlow_Continue (tt) in
    let _ := if
      expr_order_lt (rhs_rhs) (lhs_rhs)
    then
      let hoist64 := ControlFlow_Break ((false : bool)) in
      ControlFlow_Continue (never_to_any (hoist64))
    else
      ControlFlow_Continue (tt) in
    ControlFlow_Continue (f_lt (lhs_label) (rhs_label))
  | (SpecTransformConstraint_Boolean (lhs_signal) (lhs_label),SpecTransformConstraint_Boolean (rhs_signal) (rhs_label)) =>
    let _ := if
      f_ne (lhs_signal) (rhs_signal)
    then
      let hoist65 := ControlFlow_Break (f_lt (lhs_signal) (rhs_signal)) in
      ControlFlow_Continue (never_to_any (hoist65))
    else
      ControlFlow_Continue (tt) in
    ControlFlow_Continue (f_lt (lhs_label) (rhs_label))
  | (SpecTransformConstraint_Range (lhs_signal) (lhs_bits) (lhs_label),SpecTransformConstraint_Range (rhs_signal) (rhs_bits) (rhs_label)) =>
    let _ := if
      f_ne (lhs_signal) (rhs_signal)
    then
      let hoist66 := ControlFlow_Break (f_lt (lhs_signal) (rhs_signal)) in
      ControlFlow_Continue (never_to_any (hoist66))
    else
      ControlFlow_Continue (tt) in
    let _ := if
      f_ne (lhs_bits) (rhs_bits)
    then
      let hoist67 := ControlFlow_Break (f_lt (lhs_bits) (rhs_bits)) in
      ControlFlow_Continue (never_to_any (hoist67))
    else
      ControlFlow_Continue (tt) in
    ControlFlow_Continue (f_lt (lhs_label) (rhs_label))
  | _ =>
    ControlFlow_Continue ((false : bool))
  end).

Definition insert_signal_sorted (signal : t_SpecTransformSignal) (sorted : t_Slice t_SpecTransformSignal) : t_Vec ((t_SpecTransformSignal)) ((t_Global)) :=
  insert_signal_sorted_from (signal) (sorted) ((false : bool)) (impl__with_capacity (f_add (impl__len (sorted)) ((1 : t_usize)))).

Definition push_unique_signal (signals : t_Vec ((t_usize)) ((t_Global))) (signal_index : t_usize) : t_Vec ((t_usize)) ((t_Global)) :=
  let signals := if
    f_not (contains_signal_index (f_deref (signals)) (signal_index))
  then
    let signals := impl_1__push (signals) (signal_index) in
    signals
  else
    signals in
  signals.

Fixpoint sort_signals_by_key (signals : t_Slice t_SpecTransformSignal) : t_Vec ((t_SpecTransformSignal)) ((t_Global)) :=
  match impl__split_first (signals) with
  | Option_Some ((signal,remaining_signals)) =>
    let sorted := sort_signals_by_key (remaining_signals) in
    insert_signal_sorted (f_clone (signal)) (f_deref (sorted))
  | Option_None =>
    impl__new (tt)
  end.

Fixpoint insert_constraint_sorted_from (constraint : t_SpecTransformConstraint) (sorted : t_Slice t_SpecTransformConstraint) (inserted : bool) (result : t_Vec ((t_SpecTransformConstraint)) ((t_Global))) : t_Vec ((t_SpecTransformConstraint)) ((t_Global)) :=
  match impl__split_first (sorted) with
  | Option_Some ((item,remaining)) =>
    let (result,inserted) := if
      andb (f_not (inserted)) (constraint_order_lt (constraint) (item))
    then
      let result := impl_1__push (result) (f_clone (constraint)) in
      (result,(true : bool))
    else
      (result,inserted) in
    let result := impl_1__push (result) (f_clone (item)) in
    insert_constraint_sorted_from (constraint) (remaining) (inserted) (result)
  | Option_None =>
    let result := if
      f_not (inserted)
    then
      let result := impl_1__push (result) (constraint) in
      result
    else
      result in
    result
  end.

Fixpoint collect_hint_signal_indices_from (hints : t_Slice t_SpecTransformHint) (referenced : t_Vec ((t_usize)) ((t_Global))) : t_Vec ((t_usize)) ((t_Global)) :=
  match impl__split_first (hints) with
  | Option_Some ((hint,remaining_hints)) =>
    let referenced := push_unique_signal (referenced) (f_target_signal_index hint) in
    let referenced := push_unique_signal (referenced) (f_source_signal_index hint) in
    collect_hint_signal_indices_from (remaining_hints) (referenced)
  | Option_None =>
    referenced
  end.

Definition collect_constraint_signals (constraint : t_SpecTransformConstraint) (signals : t_Vec ((t_usize)) ((t_Global))) : t_Vec ((t_usize)) ((t_Global)) :=
  let signals := match constraint with
  | SpecTransformConstraint_Equal (lhs) (rhs) =>
    let signals := collect_expr_signals (lhs) (signals) in
    let signals := collect_expr_signals (rhs) (signals) in
    signals
  | SpecTransformConstraint_Boolean (signal_index)
  | SpecTransformConstraint_Range (signal_index) =>
    let signals := push_unique_signal (signals) (signal_index) in
    signals
  end in
  signals.

Fixpoint all_const_exprs (values : t_Slice t_SpecTransformExpr) : bool :=
  match impl__split_first (values) with
  | Option_Some ((value,remaining_values)) =>
    andb (match value with
    | SpecTransformExpr_Const =>
      (true : bool)
    | _ =>
      (false : bool)
    end) (all_const_exprs (remaining_values))
  | Option_None =>
    (true : bool)
  end.

Fixpoint filter_live_signals_for_normalization_from (signals : t_Slice t_SpecTransformSignal) (referenced : t_Slice t_usize) (report : t_SpecNormalizationReport) (live_signals : t_Vec ((t_SpecTransformSignal)) ((t_Global))) : (t_SpecNormalizationReport*t_Vec ((t_SpecTransformSignal)) ((t_Global))) :=
  let ((live_signals,report),hax_temp_output) := match impl__split_first (signals) with
  | Option_Some ((signal,remaining_signals)) =>
    let keep := orb (orb (match f_visibility signal with
    | SpecTransformVisibility_Public =>
      (true : bool)
    | _ =>
      (false : bool)
    end) (match f_visibility signal with
    | SpecTransformVisibility_Constant =>
      (true : bool)
    | _ =>
      (false : bool)
    end)) (contains_signal_index (referenced) (f_signal_index signal)) in
    let (live_signals,report) := if
      keep
    then
      let live_signals := impl_1__push (live_signals) (f_clone (signal)) in
      (live_signals,report)
    else
      let report := report <|t_SpecNormalizationReportf_dead_signals_removed := f_add (f_dead_signals_removed report) ((1 : t_u32)) |> in
      (live_signals,report) in
    let (tmp0,out) := filter_live_signals_for_normalization_from (remaining_signals) (referenced) (report) (live_signals) in
    let report := tmp0 in
    ((live_signals,report),out)
  | Option_None =>
    ((live_signals,report),live_signals)
  end in
  (report,hax_temp_output).

Fixpoint append_transform_exprs (target : t_Vec ((t_SpecTransformExpr)) ((t_Global))) (values : t_Slice t_SpecTransformExpr) : t_Vec ((t_SpecTransformExpr)) ((t_Global)) :=
  let target := match impl__split_first (values) with
  | Option_Some ((value,remaining_values)) =>
    let target := impl_1__push (target) (f_clone (value)) in
    let target := append_transform_exprs (target) (remaining_values) in
    target
  | Option_None =>
    target
  end in
  target.

Definition constraint_is_tautology (constraint : t_SpecTransformConstraint) : bool :=
  match constraint with
  | SpecTransformConstraint_Equal (lhs) (rhs) =>
    transform_expr_eq (lhs) (rhs)
  | _ =>
    (false : bool)
  end.

Definition transform_constraint_eq (lhs : t_SpecTransformConstraint) (rhs : t_SpecTransformConstraint) : bool :=
  match (lhs,rhs) with
  | (SpecTransformConstraint_Equal (lhs_expr) (lhs_rhs) (lhs_label_key),SpecTransformConstraint_Equal (rhs_expr) (rhs_rhs) (rhs_label_key)) =>
    andb (andb (transform_expr_eq (lhs_expr) (rhs_expr)) (transform_expr_eq (lhs_rhs) (rhs_rhs))) (f_eq (lhs_label_key) (rhs_label_key))
  | (SpecTransformConstraint_Boolean (lhs_signal) (lhs_label_key),SpecTransformConstraint_Boolean (rhs_signal) (rhs_label_key)) =>
    andb (f_eq (lhs_signal) (rhs_signal)) (f_eq (lhs_label_key) (rhs_label_key))
  | (SpecTransformConstraint_Range (lhs_signal) (lhs_bits) (lhs_label_key),SpecTransformConstraint_Range (rhs_signal) (rhs_bits) (rhs_label_key)) =>
    andb (andb (f_eq (lhs_signal) (rhs_signal)) (f_eq (lhs_bits) (rhs_bits))) (f_eq (lhs_label_key) (rhs_label_key))
  | _ =>
    (false : bool)
  end.

Definition constraint_equals_ignoring_label (lhs : t_SpecTransformConstraint) (rhs : t_SpecTransformConstraint) : bool :=
  match (lhs,rhs) with
  | (SpecTransformConstraint_Equal (lhs_expr) (lhs_rhs),SpecTransformConstraint_Equal (rhs_expr) (rhs_rhs)) =>
    andb (transform_expr_eq (lhs_expr) (rhs_expr)) (transform_expr_eq (lhs_rhs) (rhs_rhs))
  | (SpecTransformConstraint_Boolean (lhs_signal),SpecTransformConstraint_Boolean (rhs_signal)) =>
    f_eq (lhs_signal) (rhs_signal)
  | (SpecTransformConstraint_Range (lhs_signal) (lhs_bits),SpecTransformConstraint_Range (rhs_signal) (rhs_bits)) =>
    andb (f_eq (lhs_signal) (rhs_signal)) (f_eq (lhs_bits) (rhs_bits))
  | _ =>
    (false : bool)
  end.

Fixpoint filter_live_signals__filter_live_signals_from (signals : t_Slice t_SpecTransformSignal) (referenced : t_Slice t_usize) (report : t_SpecOptimizeReport) (kept_signals : t_Vec ((t_SpecTransformSignal)) ((t_Global))) : (t_SpecOptimizeReport*t_Vec ((t_SpecTransformSignal)) ((t_Global))) :=
  let ((kept_signals,report),hax_temp_output) := match impl__split_first (signals) with
  | Option_Some ((signal,remaining_signals)) =>
    let keep := orb (f_not (match f_visibility signal with
    | SpecTransformVisibility_Private =>
      (true : bool)
    | _ =>
      (false : bool)
    end)) (contains_signal_index (referenced) (f_signal_index signal)) in
    let (kept_signals,report) := if
      keep
    then
      let kept_signals := impl_1__push (kept_signals) (f_clone (signal)) in
      (kept_signals,report)
    else
      let report := report <|t_SpecOptimizeReportf_removed_private_signals := f_add (f_removed_private_signals report) ((1 : t_usize)) |> in
      (kept_signals,report) in
    let (tmp0,out) := filter_live_signals__filter_live_signals_from (remaining_signals) (referenced) (report) (kept_signals) in
    let report := tmp0 in
    ((kept_signals,report),out)
  | Option_None =>
    ((kept_signals,report),kept_signals)
  end in
  (report,hax_temp_output).

Fixpoint filter_assignments_by_signal_indices_from (assignments : t_Slice t_SpecTransformAssignment) (kept_signal_indices : t_Slice t_usize) (filtered_assignments : t_Vec ((t_SpecTransformAssignment)) ((t_Global))) : t_Vec ((t_SpecTransformAssignment)) ((t_Global)) :=
  match impl__split_first (assignments) with
  | Option_Some ((assignment,remaining_assignments)) =>
    let filtered_assignments := if
      contains_signal_index (kept_signal_indices) (f_target_signal_index assignment)
    then
      let filtered_assignments := impl_1__push (filtered_assignments) (f_clone (assignment)) in
      filtered_assignments
    else
      filtered_assignments in
    filter_assignments_by_signal_indices_from (remaining_assignments) (kept_signal_indices) (filtered_assignments)
  | Option_None =>
    filtered_assignments
  end.

Fixpoint filter_hints_by_signal_indices_from (hints : t_Slice t_SpecTransformHint) (kept_signal_indices : t_Slice t_usize) (filtered_hints : t_Vec ((t_SpecTransformHint)) ((t_Global))) : t_Vec ((t_SpecTransformHint)) ((t_Global)) :=
  match impl__split_first (hints) with
  | Option_Some ((hint,remaining_hints)) =>
    let filtered_hints := if
      contains_signal_index (kept_signal_indices) (f_target_signal_index hint)
    then
      let filtered_hints := impl_1__push (filtered_hints) (f_clone (hint)) in
      filtered_hints
    else
      filtered_hints in
    filter_hints_by_signal_indices_from (remaining_hints) (kept_signal_indices) (filtered_hints)
  | Option_None =>
    filtered_hints
  end.

Definition transform_check_constraint (constraint : t_SpecTransformConstraint) (constraint_index : t_usize) (program : t_SpecTransformProgram) (witness : t_SpecKernelWitness) : t_Result ((unit)) ((t_SpecKernelCheckError)) :=
  match constraint with
  | SpecTransformConstraint_Equal (lhs) (rhs) =>
    match transform_eval_expr (lhs) (witness) (f_field program) with
    | Result_Ok (lhs_value) =>
      match transform_eval_expr (rhs) (witness) (f_field program) with
      | Result_Ok (rhs_value) =>
        if
          spec_values_equal (lhs_value) (rhs_value) (f_field program)
        then
          Result_Ok (tt)
        else
          Result_Err (SpecKernelCheckError_EqualViolation {| SpecKernelCheckError_EqualViolation_f_constraint_index := (constraint_index); SpecKernelCheckError_EqualViolation_f_lhs := (lhs_value); SpecKernelCheckError_EqualViolation_f_rhs := (rhs_value) |})
      | Result_Err (error) =>
        Result_Err (error)
      end
    | Result_Err (error) =>
      Result_Err (error)
    end
  | SpecTransformConstraint_Boolean (signal_index) =>
    match transform_signal_value (witness) (signal_index) (f_field program) with
    | Result_Ok (value) =>
      if
        spec_value_is_boolean (value) (f_field program)
      then
        Result_Ok (tt)
      else
        Result_Err (SpecKernelCheckError_BooleanViolation {| SpecKernelCheckError_BooleanViolation_f_constraint_index := (constraint_index); SpecKernelCheckError_BooleanViolation_f_signal_index := (signal_index); SpecKernelCheckError_BooleanViolation_f_value := (value) |})
    | Result_Err (error) =>
      Result_Err (error)
    end
  | SpecTransformConstraint_Range (signal_index) (bits) =>
    match transform_signal_value (witness) (signal_index) (f_field program) with
    | Result_Ok (value) =>
      if
        spec_value_fits_bits (value) (bits) (f_field program)
      then
        Result_Ok (tt)
      else
        Result_Err (SpecKernelCheckError_RangeViolation {| SpecKernelCheckError_RangeViolation_f_constraint_index := (constraint_index); SpecKernelCheckError_RangeViolation_f_signal_index := (signal_index); SpecKernelCheckError_RangeViolation_f_bits := (bits); SpecKernelCheckError_RangeViolation_f_value := (value) |})
    | Result_Err (error) =>
      Result_Err (error)
    end
  end.

Definition transform_program_to_kernel (program : t_SpecTransformProgram) : t_SpecKernelProgram :=
  let constraints := transform_constraints_to_kernel_from (f_deref (f_constraints program)) ((0 : t_usize)) (impl__new (tt)) (f_field program) in
  SpecKernelProgram (f_field program) (constraints) (impl__new (tt)).

Definition insert_constraint_sorted (constraint : t_SpecTransformConstraint) (sorted : t_Slice t_SpecTransformConstraint) : t_Vec ((t_SpecTransformConstraint)) ((t_Global)) :=
  insert_constraint_sorted_from (constraint) (sorted) ((false : bool)) (impl__with_capacity (f_add (impl__len (sorted)) ((1 : t_usize)))).

Fixpoint sort_constraints_by_key (constraints : t_Slice t_SpecTransformConstraint) : t_Vec ((t_SpecTransformConstraint)) ((t_Global)) :=
  match impl__split_first (constraints) with
  | Option_Some ((constraint,remaining_constraints)) =>
    let sorted := sort_constraints_by_key (remaining_constraints) in
    insert_constraint_sorted (f_clone (constraint)) (f_deref (sorted))
  | Option_None =>
    impl__new (tt)
  end.

Fixpoint collect_constraint_signal_indices_from (constraints : t_Slice t_SpecTransformConstraint) (referenced : t_Vec ((t_usize)) ((t_Global))) : t_Vec ((t_usize)) ((t_Global)) :=
  match impl__split_first (constraints) with
  | Option_Some ((constraint,remaining_constraints)) =>
    let referenced := collect_constraint_signals (constraint) (referenced) in
    collect_constraint_signal_indices_from (remaining_constraints) (referenced)
  | Option_None =>
    referenced
  end.

Definition normalize_transform_constraint (constraint : t_SpecTransformConstraint) (report : t_SpecNormalizationReport) : (t_SpecNormalizationReport*t_SpecTransformConstraint) :=
  let (report,hax_temp_output) := match constraint with
  | SpecTransformConstraint_Equal (lhs) (rhs) (label_key) =>
    let (tmp0,out) := normalize_transform_expr (lhs) (report) in
    let report := tmp0 in
    let hoist77 := out in
    let (tmp0,out) := normalize_transform_expr (rhs) (report) in
    let report := tmp0 in
    let hoist76 := out in
    (report,SpecTransformConstraint_Equal {| SpecTransformConstraint_Equal_f_lhs := (hoist77); SpecTransformConstraint_Equal_f_rhs := (hoist76); SpecTransformConstraint_Equal_f_label_key := (label_key) |})
  | _ =>
    (report,f_clone (constraint))
  end in
  (report,hax_temp_output).

Definition normalize_expr_output (expr : t_SpecTransformExpr) : t_SpecTransformExpr :=
  let report := f_default (tt) in
  let (tmp0,out) := normalize_transform_expr (expr) (report) in
  let report := tmp0 in
  out.

Definition fold_transform_constraint (constraint : t_SpecTransformConstraint) (field : t_FieldId) (folded_nodes : t_usize) : (t_usize*t_SpecTransformConstraint) :=
  let (folded_nodes,hax_temp_output) := match constraint with
  | SpecTransformConstraint_Equal (lhs) (rhs) (label_key) =>
    let (tmp0,out) := fold_transform_expr (lhs) (field) (folded_nodes) in
    let folded_nodes := tmp0 in
    let hoist91 := out in
    let (tmp0,out) := fold_transform_expr (rhs) (field) (folded_nodes) in
    let folded_nodes := tmp0 in
    let hoist90 := out in
    (folded_nodes,SpecTransformConstraint_Equal {| SpecTransformConstraint_Equal_f_lhs := (hoist91); SpecTransformConstraint_Equal_f_rhs := (hoist90); SpecTransformConstraint_Equal_f_label_key := (label_key) |})
  | _ =>
    (folded_nodes,f_clone (constraint))
  end in
  (folded_nodes,hax_temp_output).

Definition fold_expr_output (expr : t_SpecTransformExpr) (field : t_FieldId) : t_SpecTransformExpr :=
  let folded_nodes := (0 : t_usize) in
  let (tmp0,out) := fold_transform_expr (expr) (field) (folded_nodes) in
  let folded_nodes := tmp0 in
  out.

Fixpoint contains_equivalent_ir_constraint (constraints : t_Slice t_SpecTransformConstraint) (target : t_SpecTransformConstraint) : bool :=
  match impl__split_first (constraints) with
  | Option_Some ((current,remaining)) =>
    orb (constraint_equals_ignoring_label (current) (target)) (contains_equivalent_ir_constraint (remaining) (target))
  | Option_None =>
    (false : bool)
  end.

Fixpoint contains_exact_constraint (constraints : t_Slice t_SpecTransformConstraint) (target : t_SpecTransformConstraint) : bool :=
  match impl__split_first (constraints) with
  | Option_Some ((current,remaining)) =>
    orb (transform_constraint_eq (current) (target)) (contains_exact_constraint (remaining) (target))
  | Option_None =>
    (false : bool)
  end.

Fixpoint transform_check_constraints_from (constraints : t_Slice t_SpecTransformConstraint) (constraint_index : t_usize) (program : t_SpecTransformProgram) (witness : t_SpecKernelWitness) : t_Result ((unit)) ((t_SpecKernelCheckError)) :=
  match impl__split_first (constraints) with
  | Option_Some ((constraint,remaining_constraints)) =>
    match transform_check_constraint (constraint) (constraint_index) (program) (witness) with
    | Result_Ok (()) =>
      transform_check_constraints_from (remaining_constraints) (f_add (constraint_index) ((1 : t_usize))) (program) (witness)
    | Result_Err (error) =>
      Result_Err (error)
    end
  | Option_None =>
    Result_Ok (tt)
  end.

Definition normalize_constraint_output (constraint : t_SpecTransformConstraint) : t_SpecTransformConstraint :=
  let report := f_default (tt) in
  let (tmp0,out) := normalize_transform_constraint (constraint) (report) in
  let report := tmp0 in
  out.

Definition fold_constraint_output (constraint : t_SpecTransformConstraint) (field : t_FieldId) : t_SpecTransformConstraint :=
  let folded_nodes := (0 : t_usize) in
  let (tmp0,out) := fold_transform_constraint (constraint) (field) (folded_nodes) in
  let folded_nodes := tmp0 in
  out.

Definition transform_check_program (program : t_SpecTransformProgram) (witness : t_SpecKernelWitness) : t_Result ((unit)) ((t_SpecKernelCheckError)) :=
  transform_check_constraints_from (f_deref (f_constraints program)) ((0 : t_usize)) (program) (witness).

Definition referenced_signal_indices (program : t_SpecTransformProgram) (constraints : t_Slice t_SpecTransformConstraint) : t_Vec ((t_usize)) ((t_Global)) :=
  let referenced := collect_constraint_signal_indices_from (constraints) (impl__new (tt)) in
  let referenced := collect_assignment_signal_indices_from (f_deref (f_assignments program)) (referenced) in
  collect_hint_signal_indices_from (f_deref (f_hints program)) (referenced).

Fixpoint normalize_constraints_from (constraints : t_Slice t_SpecTransformConstraint) (report : t_SpecNormalizationReport) (normalized_constraints : t_Vec ((t_SpecTransformConstraint)) ((t_Global))) : (t_SpecNormalizationReport*t_Vec ((t_SpecTransformConstraint)) ((t_Global))) :=
  let ((normalized_constraints,report),hax_temp_output) := match impl__split_first (constraints) with
  | Option_Some ((constraint,remaining_constraints)) =>
    let (tmp0,out) := normalize_transform_constraint (constraint) (report) in
    let report := tmp0 in
    let hoist78 := out in
    let hoist79 := impl_1__push (normalized_constraints) (hoist78) in
    let normalized_constraints := hoist79 in
    let (tmp0,out) := normalize_constraints_from (remaining_constraints) (report) (normalized_constraints) in
    let report := tmp0 in
    ((normalized_constraints,report),out)
  | Option_None =>
    ((normalized_constraints,report),normalized_constraints)
  end in
  (report,hax_temp_output).

Fixpoint dedup_constraints_ir (constraints : t_Slice t_SpecTransformConstraint) (report : t_SpecOptimizeReport) : (t_SpecOptimizeReport*t_Vec ((t_SpecTransformConstraint)) ((t_Global))) :=
  let (report,hax_temp_output) := match impl__split_first (constraints) with
  | Option_Some ((constraint,remaining_constraints)) =>
    let (tmp0,out) := dedup_constraints_ir (remaining_constraints) (report) in
    let report := tmp0 in
    let deduped := out in
    let (deduped,report) := if
      contains_equivalent_ir_constraint (f_deref (deduped)) (constraint)
    then
      let report := report <|t_SpecOptimizeReportf_deduplicated_constraints := f_add (f_deduplicated_constraints report) ((1 : t_usize)) |> in
      (deduped,report)
    else
      let deduped := insert_constraint_sorted (f_clone (constraint)) (f_deref (deduped)) in
      (deduped,report) in
    (report,deduped)
  | Option_None =>
    (report,impl__new (tt))
  end in
  (report,hax_temp_output).

Fixpoint dedup_constraints_zir (constraints : t_Slice t_SpecTransformConstraint) (report : t_SpecOptimizeReport) : (t_SpecOptimizeReport*t_Vec ((t_SpecTransformConstraint)) ((t_Global))) :=
  let (report,hax_temp_output) := match impl__split_first (constraints) with
  | Option_Some ((constraint,remaining_constraints)) =>
    let (tmp0,out) := dedup_constraints_zir (remaining_constraints) (report) in
    let report := tmp0 in
    let deduped := out in
    let (deduped,report) := if
      contains_exact_constraint (f_deref (deduped)) (constraint)
    then
      let report := report <|t_SpecOptimizeReportf_deduplicated_constraints := f_add (f_deduplicated_constraints report) ((1 : t_usize)) |> in
      (deduped,report)
    else
      let deduped := insert_constraint_sorted (f_clone (constraint)) (f_deref (deduped)) in
      (deduped,report) in
    (report,deduped)
  | Option_None =>
    (report,impl__new (tt))
  end in
  (report,hax_temp_output).

Fixpoint fold_constraints_for_ir_from (constraints : t_Slice t_SpecTransformConstraint) (field : t_FieldId) (report : t_SpecOptimizeReport) (folded_constraints : t_Vec ((t_SpecTransformConstraint)) ((t_Global))) : (t_SpecOptimizeReport*t_Vec ((t_SpecTransformConstraint)) ((t_Global))) :=
  let ((folded_constraints,report),hax_temp_output) := match impl__split_first (constraints) with
  | Option_Some ((constraint,remaining_constraints)) =>
    let (tmp0,out) := fold_transform_constraint (constraint) (field) (f_folded_expr_nodes report) in
    let report := report <|t_SpecOptimizeReportf_folded_expr_nodes := tmp0 |> in
    let folded := out in
    let (folded_constraints,report) := if
      constraint_is_tautology (folded)
    then
      let report := report <|t_SpecOptimizeReportf_removed_tautology_constraints := f_add (f_removed_tautology_constraints report) ((1 : t_usize)) |> in
      (folded_constraints,report)
    else
      let folded_constraints := impl_1__push (folded_constraints) (folded) in
      (folded_constraints,report) in
    let (tmp0,out) := fold_constraints_for_ir_from (remaining_constraints) (field) (report) (folded_constraints) in
    let report := tmp0 in
    ((folded_constraints,report),out)
  | Option_None =>
    ((folded_constraints,report),folded_constraints)
  end in
  (report,hax_temp_output).

Fixpoint fold_constraints_for_zir_from (constraints : t_Slice t_SpecTransformConstraint) (field : t_FieldId) (report : t_SpecOptimizeReport) (folded_constraints : t_Vec ((t_SpecTransformConstraint)) ((t_Global))) : (t_SpecOptimizeReport*t_Vec ((t_SpecTransformConstraint)) ((t_Global))) :=
  let ((folded_constraints,report),hax_temp_output) := match impl__split_first (constraints) with
  | Option_Some ((constraint,remaining_constraints)) =>
    let (tmp0,out) := fold_transform_constraint (constraint) (field) (f_folded_expr_nodes report) in
    let report := report <|t_SpecOptimizeReportf_folded_expr_nodes := tmp0 |> in
    let folded := out in
    let (folded_constraints,report) := if
      constraint_is_tautology (folded)
    then
      let report := report <|t_SpecOptimizeReportf_removed_tautology_constraints := f_add (f_removed_tautology_constraints report) ((1 : t_usize)) |> in
      (folded_constraints,report)
    else
      let folded_constraints := impl_1__push (folded_constraints) (folded) in
      (folded_constraints,report) in
    let (tmp0,out) := fold_constraints_for_zir_from (remaining_constraints) (field) (report) (folded_constraints) in
    let report := tmp0 in
    ((folded_constraints,report),out)
  | Option_None =>
    ((folded_constraints,report),folded_constraints)
  end in
  (report,hax_temp_output).

Definition normalize_supported_program (program : t_SpecTransformProgram) : t_SpecNormalizationResult :=
  let report := f_default (tt) in
  let (tmp0,out) := normalize_constraints_from (f_deref (f_constraints program)) (report) (impl__with_capacity (impl_1__len (f_constraints program))) in
  let report := tmp0 in
  let constraints := out in
  let referenced := referenced_signal_indices (program) (f_deref (constraints)) in
  let (tmp0,out) := filter_live_signals_for_normalization_from (f_deref (f_signals program)) (f_deref (referenced)) (report) (impl__new (tt)) in
  let report := tmp0 in
  let live_signals := out in
  SpecNormalizationResult (SpecTransformProgram (f_field program) (sort_signals_by_key (f_deref (live_signals))) (sort_constraints_by_key (f_deref (constraints))) (f_clone (f_assignments program)) (f_clone (f_hints program))) (report).

Definition normalize_program_output (program : t_SpecTransformProgram) : t_SpecTransformProgram :=
  f_program normalize_supported_program (program).

Definition filter_live_signals (program : t_SpecTransformProgram) (constraints : t_Slice t_SpecTransformConstraint) (report : t_SpecOptimizeReport) : (t_SpecOptimizeReport*t_Vec ((t_SpecTransformSignal)) ((t_Global))) :=
  let referenced := referenced_signal_indices (program) (constraints) in
  let (tmp0,out) := filter_live_signals__filter_live_signals_from (f_deref (f_signals program)) (f_deref (referenced)) (report) (impl__new (tt)) in
  let report := tmp0 in
  let hax_temp_output := out in
  (report,hax_temp_output).

Definition optimize_supported_ir_program (program : t_SpecTransformProgram) : t_SpecOptimizeResult :=
  let report := f_default (tt) in
  let (tmp0,out) := fold_constraints_for_ir_from (f_deref (f_constraints program)) (f_field program) (report) (impl__new (tt)) in
  let report := tmp0 in
  let folded_constraints := out in
  let (tmp0,out) := dedup_constraints_ir (f_deref (folded_constraints)) (report) in
  let report := tmp0 in
  let constraints := out in
  let (tmp0,out) := filter_live_signals (program) (f_deref (constraints)) (report) in
  let report := tmp0 in
  let signals := out in
  let kept_signal_indices := collect_signal_indices_from_signals (f_deref (signals)) (impl__new (tt)) in
  let assignments := filter_assignments_by_signal_indices_from (f_deref (f_assignments program)) (f_deref (kept_signal_indices)) (impl__new (tt)) in
  let hints := filter_hints_by_signal_indices_from (f_deref (f_hints program)) (f_deref (kept_signal_indices)) (impl__new (tt)) in
  SpecOptimizeResult (SpecTransformProgram (f_field program) (signals) (constraints) (assignments) (hints)) (report).

Definition optimize_ir_program_output (program : t_SpecTransformProgram) : t_SpecTransformProgram :=
  f_program optimize_supported_ir_program (program).

Definition optimize_supported_zir_program (program : t_SpecTransformProgram) : t_SpecOptimizeResult :=
  let report := f_default (tt) in
  let (tmp0,out) := fold_constraints_for_zir_from (f_deref (f_constraints program)) (f_field program) (report) (impl__new (tt)) in
  let report := tmp0 in
  let folded_constraints := out in
  let (tmp0,out) := dedup_constraints_zir (f_deref (folded_constraints)) (report) in
  let report := tmp0 in
  let constraints := out in
  let (tmp0,out) := filter_live_signals (program) (f_deref (constraints)) (report) in
  let report := tmp0 in
  let signals := out in
  SpecOptimizeResult (SpecTransformProgram (f_field program) (signals) (constraints) (f_clone (f_assignments program)) (f_clone (f_hints program))) (report).

Definition optimize_zir_program_output (program : t_SpecTransformProgram) : t_SpecTransformProgram :=
  f_program optimize_supported_zir_program (program).

Fixpoint collect_expr_signals (expr : t_SpecTransformExpr) (signals : t_Vec ((t_usize)) ((t_Global))) : t_Vec ((t_usize)) ((t_Global)) :=
  let signals := match expr with
  | SpecTransformExpr_Const =>
    signals
  | SpecTransformExpr_Signal (signal_index) =>
    push_unique_signal (signals) (signal_index)
  | SpecTransformExpr_Add (values) =>
    collect_expr_signal_values (f_deref (values)) (signals)
  | SpecTransformExpr_Sub (lhs) (rhs)
  | SpecTransformExpr_Mul (lhs) (rhs)
  | SpecTransformExpr_Div (lhs) (rhs) =>
    let signals := collect_expr_signals (lhs) (signals) in
    let signals := collect_expr_signals (rhs) (signals) in
    signals
  end in
  signals.

Fixpoint collect_expr_signal_values (values : t_Slice t_SpecTransformExpr) (signals : t_Vec ((t_usize)) ((t_Global))) : t_Vec ((t_usize)) ((t_Global)) :=
  let signals := match impl__split_first (values) with
  | Option_Some ((value,remaining_values)) =>
    let signals := collect_expr_signals (value) (signals) in
    let signals := collect_expr_signal_values (remaining_values) (signals) in
    signals
  | Option_None =>
    signals
  end in
  signals.

Fixpoint normalize_transform_expr (expr : t_SpecTransformExpr) (report : t_SpecNormalizationReport) : (t_SpecNormalizationReport*t_SpecTransformExpr) :=
  run (let (report,hax_temp_output) := match expr with
  | SpecTransformExpr_Const
  | SpecTransformExpr_Signal =>
    ControlFlow_Continue ((report,f_clone (expr)))
  | SpecTransformExpr_Add (values) =>
    ControlFlow_Continue (let (tmp0,out) := normalize_non_zero_values_from (f_deref (values)) (report) (impl__new (tt)) in
    let report := tmp0 in
    let non_zero := out in
    match impl_1__len (non_zero) with
    | 0 =>
      let report := report <|t_SpecNormalizationReportf_constant_folds := f_add (f_constant_folds report) ((1 : t_u32)) |> in
      (report,zero_spec_expr (tt))
    | 1 =>
      let (tmp0,out) := impl_1__remove (non_zero) ((0 : t_usize)) in
      let non_zero := tmp0 in
      (report,out)
    | _ =>
      let report := if
        all_const_exprs (f_deref (non_zero))
      then
        let report := report <|t_SpecNormalizationReportf_constant_folds := f_add (f_constant_folds report) ((1 : t_u32)) |> in
        report
      else
        report in
      (report,SpecTransformExpr_Add (non_zero))
    end)
  | SpecTransformExpr_Mul (lhs) (rhs) =>
    let (tmp0,out) := normalize_transform_expr (lhs) (report) in
    let report := tmp0 in
    let lhs := out in
    let (tmp0,out) := normalize_transform_expr (rhs) (report) in
    let report := tmp0 in
    let rhs := out in
    let report := if
      match match lhs with
      | SpecTransformExpr_Const (value) =>
        match spec_value_is_one_raw (value) with
        | true =>
          Option_Some ((true : bool))
        | _ =>
          Option_None
        end
      | _ =>
        Option_None
      end with
      | Option_Some (x) =>
        x
      | Option_None =>
        (false : bool)
      end
    then
      let report := report <|t_SpecNormalizationReportf_algebraic_rewrites := f_add (f_algebraic_rewrites report) ((1 : t_u32)) |> in
      let hoist70 := ControlFlow_Break ((report,rhs)) in
      ControlFlow_Continue (report)
    else
      ControlFlow_Continue (report) in
    let report := if
      match match rhs with
      | SpecTransformExpr_Const (value) =>
        match spec_value_is_one_raw (value) with
        | true =>
          Option_Some ((true : bool))
        | _ =>
          Option_None
        end
      | _ =>
        Option_None
      end with
      | Option_Some (x) =>
        x
      | Option_None =>
        (false : bool)
      end
    then
      let report := report <|t_SpecNormalizationReportf_algebraic_rewrites := f_add (f_algebraic_rewrites report) ((1 : t_u32)) |> in
      let hoist71 := ControlFlow_Break ((report,lhs)) in
      ControlFlow_Continue (report)
    else
      ControlFlow_Continue (report) in
    let report := if
      match match lhs with
      | SpecTransformExpr_Const (value) =>
        match spec_value_is_zero_raw (value) with
        | true =>
          Option_Some ((true : bool))
        | _ =>
          Option_None
        end
      | _ =>
        Option_None
      end with
      | Option_Some (x) =>
        x
      | Option_None =>
        (false : bool)
      end
    then
      let report := report <|t_SpecNormalizationReportf_algebraic_rewrites := f_add (f_algebraic_rewrites report) ((1 : t_u32)) |> in
      let hoist72 := ControlFlow_Break ((report,zero_spec_expr (tt))) in
      ControlFlow_Continue (report)
    else
      ControlFlow_Continue (report) in
    let report := if
      match match rhs with
      | SpecTransformExpr_Const (value) =>
        match spec_value_is_zero_raw (value) with
        | true =>
          Option_Some ((true : bool))
        | _ =>
          Option_None
        end
      | _ =>
        Option_None
      end with
      | Option_Some (x) =>
        x
      | Option_None =>
        (false : bool)
      end
    then
      let report := report <|t_SpecNormalizationReportf_algebraic_rewrites := f_add (f_algebraic_rewrites report) ((1 : t_u32)) |> in
      let hoist73 := ControlFlow_Break ((report,zero_spec_expr (tt))) in
      ControlFlow_Continue (report)
    else
      ControlFlow_Continue (report) in
    ControlFlow_Continue ((report,SpecTransformExpr_Mul (lhs) (rhs)))
  | SpecTransformExpr_Sub (lhs) (rhs) =>
    let (tmp0,out) := normalize_transform_expr (lhs) (report) in
    let report := tmp0 in
    let lhs := out in
    let (tmp0,out) := normalize_transform_expr (rhs) (report) in
    let report := tmp0 in
    let rhs := out in
    let report := if
      match match rhs with
      | SpecTransformExpr_Const (value) =>
        match spec_value_is_zero_raw (value) with
        | true =>
          Option_Some ((true : bool))
        | _ =>
          Option_None
        end
      | _ =>
        Option_None
      end with
      | Option_Some (x) =>
        x
      | Option_None =>
        (false : bool)
      end
    then
      let report := report <|t_SpecNormalizationReportf_algebraic_rewrites := f_add (f_algebraic_rewrites report) ((1 : t_u32)) |> in
      let hoist74 := ControlFlow_Break ((report,lhs)) in
      ControlFlow_Continue (report)
    else
      ControlFlow_Continue (report) in
    ControlFlow_Continue ((report,SpecTransformExpr_Sub (lhs) (rhs)))
  | SpecTransformExpr_Div (lhs) (rhs) =>
    let (tmp0,out) := normalize_transform_expr (lhs) (report) in
    let report := tmp0 in
    let lhs := out in
    let (tmp0,out) := normalize_transform_expr (rhs) (report) in
    let report := tmp0 in
    let rhs := out in
    let report := if
      match match rhs with
      | SpecTransformExpr_Const (value) =>
        match spec_value_is_one_raw (value) with
        | true =>
          Option_Some ((true : bool))
        | _ =>
          Option_None
        end
      | _ =>
        Option_None
      end with
      | Option_Some (x) =>
        x
      | Option_None =>
        (false : bool)
      end
    then
      let report := report <|t_SpecNormalizationReportf_algebraic_rewrites := f_add (f_algebraic_rewrites report) ((1 : t_u32)) |> in
      let hoist75 := ControlFlow_Break ((report,lhs)) in
      ControlFlow_Continue (report)
    else
      ControlFlow_Continue (report) in
    ControlFlow_Continue ((report,SpecTransformExpr_Div (lhs) (rhs)))
  end in
  ControlFlow_Continue ((report,hax_temp_output))).

Fixpoint normalize_non_zero_values_from (values : t_Slice t_SpecTransformExpr) (report : t_SpecNormalizationReport) (non_zero : t_Vec ((t_SpecTransformExpr)) ((t_Global))) : (t_SpecNormalizationReport*t_Vec ((t_SpecTransformExpr)) ((t_Global))) :=
  let ((non_zero,report),hax_temp_output) := match impl__split_first (values) with
  | Option_Some ((value,remaining_values)) =>
    let (tmp0,out) := normalize_transform_expr (value) (report) in
    let report := tmp0 in
    let normalized := out in
    let (report,hoist69) := match normalized with
    | SpecTransformExpr_Const (value) =>
      match spec_value_is_zero_raw (value) with
      | true =>
        let report := report <|t_SpecNormalizationReportf_algebraic_rewrites := f_add (f_algebraic_rewrites report) ((1 : t_u32)) |> in
        let hoist68 := tt in
        (report,Option_Some (hoist68))
      | _ =>
        (report,Option_None)
      end
    | _ =>
      (report,Option_None)
    end in
    let non_zero := match hoist69 with
    | Option_Some (x) =>
      non_zero
    | Option_None =>
      impl_1__push (non_zero) (normalized)
    end in
    let (tmp0,out) := normalize_non_zero_values_from (remaining_values) (report) (non_zero) in
    let report := tmp0 in
    ((non_zero,report),out)
  | Option_None =>
    ((non_zero,report),non_zero)
  end in
  (report,hax_temp_output).

Fixpoint fold_transform_expr (expr : t_SpecTransformExpr) (field : t_FieldId) (folded_nodes : t_usize) : (t_usize*t_SpecTransformExpr) :=
  run (let (folded_nodes,hax_temp_output) := match expr with
  | SpecTransformExpr_Const
  | SpecTransformExpr_Signal =>
    ControlFlow_Continue ((folded_nodes,f_clone (expr)))
  | SpecTransformExpr_Add (values) =>
    ControlFlow_Continue (let (tmp0,out) := fold_add_terms_from (f_deref (values)) (field) (folded_nodes) (zero_spec_value (tt)) ((false : bool)) (impl__new (tt)) in
    let folded_nodes := tmp0 in
    let (const_acc,saw_const,terms) := out in
    let terms := if
      andb (saw_const) (f_not (spec_value_is_zero_raw (const_acc)))
    then
      let terms := impl_1__push (terms) (SpecTransformExpr_Const {| SpecTransformExpr_Const_f_value := (const_acc); SpecTransformExpr_Const_f_sort_key := ((0 : t_usize)) |}) in
      terms
    else
      terms in
    match impl_1__len (terms) with
    | 0 =>
      (folded_nodes,zero_spec_expr (tt))
    | 1 =>
      let (tmp0,out) := impl_1__remove (terms) ((0 : t_usize)) in
      let terms := tmp0 in
      (folded_nodes,out)
    | _ =>
      (folded_nodes,SpecTransformExpr_Add (terms))
    end)
  | SpecTransformExpr_Sub (lhs) (rhs) =>
    ControlFlow_Continue (let (tmp0,out) := fold_transform_expr (lhs) (field) (folded_nodes) in
    let folded_nodes := tmp0 in
    let lhs := out in
    let (tmp0,out) := fold_transform_expr (rhs) (field) (folded_nodes) in
    let folded_nodes := tmp0 in
    let rhs := out in
    match (lhs,rhs) with
    | (SpecTransformExpr_Const (lhs_value),SpecTransformExpr_Const (rhs_value)) =>
      let folded_nodes := f_add (folded_nodes) ((1 : t_usize)) in
      (folded_nodes,SpecTransformExpr_Const {| SpecTransformExpr_Const_f_value := (sub_spec_values (lhs_value) (rhs_value) (field)); SpecTransformExpr_Const_f_sort_key := ((0 : t_usize)) |})
    | _ =>
      if
        match match rhs with
        | SpecTransformExpr_Const (value) =>
          match spec_value_is_zero_raw (value) with
          | true =>
            Option_Some ((true : bool))
          | _ =>
            Option_None
          end
        | _ =>
          Option_None
        end with
        | Option_Some (x) =>
          x
        | Option_None =>
          (false : bool)
        end
      then
        let folded_nodes := f_add (folded_nodes) ((1 : t_usize)) in
        (folded_nodes,lhs)
      else
        (folded_nodes,SpecTransformExpr_Sub (lhs) (rhs))
    end)
  | SpecTransformExpr_Mul (lhs) (rhs) =>
    ControlFlow_Continue (let (tmp0,out) := fold_transform_expr (lhs) (field) (folded_nodes) in
    let folded_nodes := tmp0 in
    let lhs := out in
    let (tmp0,out) := fold_transform_expr (rhs) (field) (folded_nodes) in
    let folded_nodes := tmp0 in
    let rhs := out in
    match (lhs,rhs) with
    | (SpecTransformExpr_Const (lhs_value),SpecTransformExpr_Const (rhs_value)) =>
      let folded_nodes := f_add (folded_nodes) ((1 : t_usize)) in
      (folded_nodes,SpecTransformExpr_Const {| SpecTransformExpr_Const_f_value := (mul_spec_values (lhs_value) (rhs_value) (field)); SpecTransformExpr_Const_f_sort_key := ((0 : t_usize)) |})
    | _ =>
      let (folded_nodes,hoist87) := match (lhs,rhs) with
      | (SpecTransformExpr_Const (value),_) =>
        match spec_value_is_zero_raw (value) with
        | true =>
          let folded_nodes := f_add (folded_nodes) ((1 : t_usize)) in
          let hoist86 := zero_spec_expr (tt) in
          (folded_nodes,Option_Some (hoist86))
        | _ =>
          (folded_nodes,Option_None)
        end
      | _ =>
        (folded_nodes,Option_None)
      end in
      match hoist87 with
      | Option_Some (x) =>
        (folded_nodes,x)
      | Option_None =>
        let (folded_nodes,hoist85) := match (lhs,rhs) with
        | (_,SpecTransformExpr_Const (value)) =>
          match spec_value_is_zero_raw (value) with
          | true =>
            let folded_nodes := f_add (folded_nodes) ((1 : t_usize)) in
            let hoist84 := zero_spec_expr (tt) in
            (folded_nodes,Option_Some (hoist84))
          | _ =>
            (folded_nodes,Option_None)
          end
        | _ =>
          (folded_nodes,Option_None)
        end in
        match hoist85 with
        | Option_Some (x) =>
          (folded_nodes,x)
        | Option_None =>
          let (folded_nodes,hoist83) := match (lhs,rhs) with
          | (SpecTransformExpr_Const (value),_) =>
            match spec_value_is_one_raw (value) with
            | true =>
              let folded_nodes := f_add (folded_nodes) ((1 : t_usize)) in
              let hoist82 := rhs in
              (folded_nodes,Option_Some (hoist82))
            | _ =>
              (folded_nodes,Option_None)
            end
          | _ =>
            (folded_nodes,Option_None)
          end in
          match hoist83 with
          | Option_Some (x) =>
            (folded_nodes,x)
          | Option_None =>
            let (folded_nodes,hoist81) := match (lhs,rhs) with
            | (_,SpecTransformExpr_Const (value)) =>
              match spec_value_is_one_raw (value) with
              | true =>
                let folded_nodes := f_add (folded_nodes) ((1 : t_usize)) in
                let hoist80 := lhs in
                (folded_nodes,Option_Some (hoist80))
              | _ =>
                (folded_nodes,Option_None)
              end
            | _ =>
              (folded_nodes,Option_None)
            end in
            match hoist81 with
            | Option_Some (x) =>
              (folded_nodes,x)
            | Option_None =>
              (folded_nodes,SpecTransformExpr_Mul (lhs) (rhs))
            end
          end
        end
      end
    end)
  | SpecTransformExpr_Div (lhs) (rhs) =>
    let (tmp0,out) := fold_transform_expr (lhs) (field) (folded_nodes) in
    let folded_nodes := tmp0 in
    let lhs := out in
    let (tmp0,out) := fold_transform_expr (rhs) (field) (folded_nodes) in
    let folded_nodes := tmp0 in
    let rhs := out in
    let folded_nodes := match (lhs,rhs) with
    | (SpecTransformExpr_Const (lhs_value),SpecTransformExpr_Const (rhs_value)) =>
      let folded_nodes := match div_spec_values (lhs_value) (rhs_value) (field) with
      | Option_Some (value) =>
        let folded_nodes := f_add (folded_nodes) ((1 : t_usize)) in
        let hoist88 := ControlFlow_Break ((folded_nodes,SpecTransformExpr_Const {| SpecTransformExpr_Const_f_value := (value); SpecTransformExpr_Const_f_sort_key := ((0 : t_usize)) |})) in
        ControlFlow_Continue (folded_nodes)
      | _ =>
        ControlFlow_Continue (folded_nodes)
      end in
      let hoist89 := ControlFlow_Break ((folded_nodes,SpecTransformExpr_Div (lhs) (rhs))) in
      ControlFlow_Continue (folded_nodes)
    | _ =>
      ControlFlow_Continue (folded_nodes)
    end in
    ControlFlow_Continue (if
      match match rhs with
      | SpecTransformExpr_Const (value) =>
        match spec_value_is_one_raw (value) with
        | true =>
          Option_Some ((true : bool))
        | _ =>
          Option_None
        end
      | _ =>
        Option_None
      end with
      | Option_Some (x) =>
        x
      | Option_None =>
        (false : bool)
      end
    then
      let folded_nodes := f_add (folded_nodes) ((1 : t_usize)) in
      (folded_nodes,lhs)
    else
      (folded_nodes,SpecTransformExpr_Div (lhs) (rhs)))
  end in
  ControlFlow_Continue ((folded_nodes,hax_temp_output))).

Fixpoint fold_add_terms_from (values : t_Slice t_SpecTransformExpr) (field : t_FieldId) (folded_nodes : t_usize) (const_acc : t_SpecFieldValue) (saw_const : bool) (terms : t_Vec ((t_SpecTransformExpr)) ((t_Global))) : (t_usize*(t_SpecFieldValue*bool*t_Vec ((t_SpecTransformExpr)) ((t_Global)))) :=
  let ((folded_nodes,terms),hax_temp_output) := match impl__split_first (values) with
  | Option_Some ((value,remaining_values)) =>
    let (tmp0,out) := fold_transform_expr (value) (field) (folded_nodes) in
    let folded_nodes := tmp0 in
    let folded := out in
    let ((folded_nodes,terms),(const_acc,saw_const,terms)) := match folded with
    | SpecTransformExpr_Const (value) =>
      let folded_nodes := f_add (folded_nodes) ((1 : t_usize)) in
      ((folded_nodes,terms),(add_spec_values (const_acc) (value) (field),(true : bool),terms))
    | SpecTransformExpr_Add (nested) =>
      let folded_nodes := f_add (folded_nodes) ((1 : t_usize)) in
      let terms := append_transform_exprs (terms) (f_deref (nested)) in
      ((folded_nodes,terms),(const_acc,saw_const,terms))
    | other =>
      let terms := impl_1__push (terms) (other) in
      ((folded_nodes,terms),(const_acc,saw_const,terms))
    end in
    let (tmp0,out) := fold_add_terms_from (remaining_values) (field) (folded_nodes) (const_acc) (saw_const) (terms) in
    let folded_nodes := tmp0 in
    ((folded_nodes,terms),out)
  | Option_None =>
    ((folded_nodes,terms),(const_acc,saw_const,terms))
  end in
  (folded_nodes,hax_temp_output).

Fixpoint transform_expr_list_eq (lhs : t_Slice t_SpecTransformExpr) (rhs : t_Slice t_SpecTransformExpr) : bool :=
  match (impl__split_first (lhs),impl__split_first (rhs)) with
  | (Option_Some ((lhs_value,lhs_remaining)),Option_Some ((rhs_value,rhs_remaining))) =>
    andb (transform_expr_eq (lhs_value) (rhs_value)) (transform_expr_list_eq (lhs_remaining) (rhs_remaining))
  | (Option_None,Option_None) =>
    (true : bool)
  | _ =>
    (false : bool)
  end.

Fixpoint transform_expr_eq (lhs : t_SpecTransformExpr) (rhs : t_SpecTransformExpr) : bool :=
  match (lhs,rhs) with
  | (SpecTransformExpr_Const (lhs_value) (lhs_sort_key),SpecTransformExpr_Const (rhs_value) (rhs_sort_key)) =>
    andb (f_eq (lhs_sort_key) (rhs_sort_key)) (f_eq (lhs_value) (rhs_value))
  | (SpecTransformExpr_Signal (lhs_signal_index) (lhs_sort_key),SpecTransformExpr_Signal (rhs_signal_index) (rhs_sort_key)) =>
    andb (f_eq (lhs_signal_index) (rhs_signal_index)) (f_eq (lhs_sort_key) (rhs_sort_key))
  | (SpecTransformExpr_Add (lhs_values),SpecTransformExpr_Add (rhs_values)) =>
    transform_expr_list_eq (f_deref (lhs_values)) (f_deref (rhs_values))
  | (SpecTransformExpr_Sub (lhs_lhs) (lhs_rhs),SpecTransformExpr_Sub (rhs_lhs) (rhs_rhs))
  | (SpecTransformExpr_Mul (lhs_lhs) (lhs_rhs),SpecTransformExpr_Mul (rhs_lhs) (rhs_rhs))
  | (SpecTransformExpr_Div (lhs_lhs) (lhs_rhs),SpecTransformExpr_Div (rhs_lhs) (rhs_rhs)) =>
    andb (transform_expr_eq (lhs_lhs) (rhs_lhs)) (transform_expr_eq (lhs_rhs) (rhs_rhs))
  | _ =>
    (false : bool)
  end.

Fixpoint transform_eval_exprs (values : t_Slice t_SpecTransformExpr) (witness : t_SpecKernelWitness) (field : t_FieldId) (acc : t_SpecFieldValue) : t_Result ((t_SpecFieldValue)) ((t_SpecKernelCheckError)) :=
  match impl__split_first (values) with
  | Option_Some ((value,remaining_values)) =>
    match transform_eval_expr (value) (witness) (field) with
    | Result_Ok (evaluated) =>
      transform_eval_exprs (remaining_values) (witness) (field) (add_spec_values (acc) (evaluated) (field))
    | Result_Err (error) =>
      Result_Err (error)
    end
  | Option_None =>
    Result_Ok (acc)
  end.

Fixpoint transform_eval_expr (expr : t_SpecTransformExpr) (witness : t_SpecKernelWitness) (field : t_FieldId) : t_Result ((t_SpecFieldValue)) ((t_SpecKernelCheckError)) :=
  match expr with
  | SpecTransformExpr_Const (value) =>
    Result_Ok (normalize_spec_value (value) (field))
  | SpecTransformExpr_Signal (signal_index) =>
    transform_signal_value (witness) (signal_index) (field)
  | SpecTransformExpr_Add (values) =>
    transform_eval_exprs (f_deref (values)) (witness) (field) (zero_spec_value (tt))
  | SpecTransformExpr_Sub (lhs) (rhs) =>
    match transform_eval_expr (lhs) (witness) (field) with
    | Result_Ok (lhs_value) =>
      match transform_eval_expr (rhs) (witness) (field) with
      | Result_Ok (rhs_value) =>
        Result_Ok (sub_spec_values (lhs_value) (rhs_value) (field))
      | Result_Err (error) =>
        Result_Err (error)
      end
    | Result_Err (error) =>
      Result_Err (error)
    end
  | SpecTransformExpr_Mul (lhs) (rhs) =>
    match transform_eval_expr (lhs) (witness) (field) with
    | Result_Ok (lhs_value) =>
      match transform_eval_expr (rhs) (witness) (field) with
      | Result_Ok (rhs_value) =>
        Result_Ok (mul_spec_values (lhs_value) (rhs_value) (field))
      | Result_Err (error) =>
        Result_Err (error)
      end
    | Result_Err (error) =>
      Result_Err (error)
    end
  | SpecTransformExpr_Div (lhs) (rhs) =>
    match transform_eval_expr (lhs) (witness) (field) with
    | Result_Ok (lhs_value) =>
      match transform_eval_expr (rhs) (witness) (field) with
      | Result_Ok (rhs_value) =>
        match div_spec_values (lhs_value) (rhs_value) (field) with
        | Option_Some (value) =>
          Result_Ok (value)
        | Option_None =>
          Result_Err (SpecKernelCheckError_DivisionByZero)
        end
      | Result_Err (error) =>
        Result_Err (error)
      end
    | Result_Err (error) =>
      Result_Err (error)
    end
  end.

Fixpoint transform_expr_to_kernel (expr : t_SpecTransformExpr) (field : t_FieldId) : t_SpecKernelExpr :=
  match expr with
  | SpecTransformExpr_Const (value) =>
    SpecKernelExpr_Const (f_clone (value))
  | SpecTransformExpr_Signal (signal_index) =>
    SpecKernelExpr_Signal (signal_index)
  | SpecTransformExpr_Add (values) =>
    to_kernel_expr (f_deref (values)) (field)
  | SpecTransformExpr_Sub (lhs) (rhs) =>
    SpecKernelExpr_Sub (transform_expr_to_kernel (lhs) (field)) (transform_expr_to_kernel (rhs) (field))
  | SpecTransformExpr_Mul (lhs) (rhs) =>
    SpecKernelExpr_Mul (transform_expr_to_kernel (lhs) (field)) (transform_expr_to_kernel (rhs) (field))
  | SpecTransformExpr_Div (lhs) (rhs) =>
    SpecKernelExpr_Div (transform_expr_to_kernel (lhs) (field)) (transform_expr_to_kernel (rhs) (field))
  end.

Fixpoint to_kernel_expr_from (values : t_Slice t_SpecTransformExpr) (acc : t_SpecKernelExpr) (field : t_FieldId) : t_SpecKernelExpr :=
  match impl__split_first (values) with
  | Option_Some ((value,remaining_values)) =>
    to_kernel_expr_from (remaining_values) (SpecKernelExpr_Add (acc) (transform_expr_to_kernel (value) (field))) (field)
  | Option_None =>
    acc
  end.

Definition to_kernel_expr (values : t_Slice t_SpecTransformExpr) (field : t_FieldId) : t_SpecKernelExpr :=
  match impl__split_first (values) with
  | Option_Some ((first,rest)) =>
    to_kernel_expr_from (rest) (transform_expr_to_kernel (first) (field)) (field)
  | Option_None =>
    SpecKernelExpr_Const (zero_spec_value (tt))
  end.

Fixpoint collect_assignment_signal_indices_from (assignments : t_Slice t_SpecTransformAssignment) (referenced : t_Vec ((t_usize)) ((t_Global))) : t_Vec ((t_usize)) ((t_Global)) :=
  match impl__split_first (assignments) with
  | Option_Some ((assignment,remaining_assignments)) =>
    let referenced := push_unique_signal (referenced) (f_target_signal_index assignment) in
    let referenced := collect_expr_signals (f_expr assignment) (referenced) in
    collect_assignment_signal_indices_from (remaining_assignments) (referenced)
  | Option_None =>
    referenced
  end.

Fixpoint transform_constraints_to_kernel_from (constraints : t_Slice t_SpecTransformConstraint) (index : t_usize) (kernel_constraints : t_Vec ((t_SpecKernelConstraint)) ((t_Global))) (field : t_FieldId) : t_Vec ((t_SpecKernelConstraint)) ((t_Global)) :=
  match impl__split_first (constraints) with
  | Option_Some ((constraint,remaining_constraints)) =>
    let kernel_constraints := impl_1__push (kernel_constraints) (match constraint with
    | SpecTransformConstraint_Equal (lhs) (rhs) =>
      SpecKernelConstraint_Equal {| SpecKernelConstraint_Equal_f_index := (index); SpecKernelConstraint_Equal_f_lhs := (transform_expr_to_kernel (lhs) (field)); SpecKernelConstraint_Equal_f_rhs := (transform_expr_to_kernel (rhs) (field)) |}
    | SpecTransformConstraint_Boolean (signal_index) =>
      SpecKernelConstraint_Boolean {| SpecKernelConstraint_Boolean_f_index := (index); SpecKernelConstraint_Boolean_f_signal := (signal_index) |}
    | SpecTransformConstraint_Range (signal_index) (bits) =>
      SpecKernelConstraint_Range {| SpecKernelConstraint_Range_f_index := (index); SpecKernelConstraint_Range_f_signal := (signal_index); SpecKernelConstraint_Range_f_bits := (bits) |}
    end) in
    transform_constraints_to_kernel_from (remaining_constraints) (f_add (index) ((1 : t_usize))) (kernel_constraints) (field)
  | Option_None =>
    kernel_constraints
  end.
