(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

Inductive t_SpecCcsVisibility : Type :=
| SpecCcsVisibility_Public
| SpecCcsVisibility_NonPublic.



Record SpecCcsSignal_record : Type :=
  {
    SpecCcsSignal_f_visibility : t_SpecCcsVisibility;
  }.


#[export] Instance settable_SpecCcsSignal_record : Settable _ :=
  settable! (Build_SpecCcsSignal_record) <SpecCcsSignal_f_visibility>.

Inductive t_SpecCcsBlackBoxKind : Type :=
| SpecCcsBlackBoxKind_RecursiveAggregationMarker
| SpecCcsBlackBoxKind_Other.



Record SpecCcsMatrixEntry_record : Type :=
  {
    SpecCcsMatrixEntry_f_row : t_usize;
    SpecCcsMatrixEntry_f_col : t_usize;
    SpecCcsMatrixEntry_f_value : t_SpecFieldValue;
  }.




#[export] Instance settable_SpecCcsMatrixEntry_record : Settable _ :=
  settable! (Build_SpecCcsMatrixEntry_record) <SpecCcsMatrixEntry_f_row; SpecCcsMatrixEntry_f_col; SpecCcsMatrixEntry_f_value>.

Record SpecCcsMatrix_record : Type :=
  {
    SpecCcsMatrix_f_rows : t_usize;
    SpecCcsMatrix_f_cols : t_usize;
    SpecCcsMatrix_f_entries : t_Vec ((t_SpecCcsMatrixEntry)) ((t_Global));
  }.




#[export] Instance settable_SpecCcsMatrix_record : Settable _ :=
  settable! (Build_SpecCcsMatrix_record) <SpecCcsMatrix_f_rows; SpecCcsMatrix_f_cols; SpecCcsMatrix_f_entries>.

Record SpecCcsMultiset_record : Type :=
  {
    SpecCcsMultiset_f_matrix_indices : t_Vec ((t_usize)) ((t_Global));
    SpecCcsMultiset_f_coefficient : t_SpecFieldValue;
  }.



#[export] Instance settable_SpecCcsMultiset_record : Settable _ :=
  settable! (Build_SpecCcsMultiset_record) <SpecCcsMultiset_f_matrix_indices; SpecCcsMultiset_f_coefficient>.

Record SpecCcsProgram_record : Type :=
  {
    SpecCcsProgram_f_field : t_FieldId;
    SpecCcsProgram_f_num_constraints : t_usize;
    SpecCcsProgram_f_num_variables : t_usize;
    SpecCcsProgram_f_num_public : t_usize;
    SpecCcsProgram_f_matrices : t_Vec ((t_SpecCcsMatrix)) ((t_Global));
    SpecCcsProgram_f_multisets : t_Vec ((t_SpecCcsMultiset)) ((t_Global));
  }.







#[export] Instance settable_SpecCcsProgram_record : Settable _ :=
  settable! (Build_SpecCcsProgram_record) <SpecCcsProgram_f_field; SpecCcsProgram_f_num_constraints; SpecCcsProgram_f_num_variables; SpecCcsProgram_f_num_public; SpecCcsProgram_f_matrices; SpecCcsProgram_f_multisets>.

Inductive t_SpecCcsSynthesisErrorKind : Type :=
| SpecCcsSynthesisErrorKind_InvalidSignalIndex
| SpecCcsSynthesisErrorKind_LookupRequiresLowering
| SpecCcsSynthesisErrorKind_BlackBoxRequiresLowering.




Record SpecCcsSynthesisError_record : Type :=
  {
    SpecCcsSynthesisError_f_constraint_index : t_usize;
    SpecCcsSynthesisError_f_kind : t_SpecCcsSynthesisErrorKind;
  }.



#[export] Instance settable_SpecCcsSynthesisError_record : Settable _ :=
  settable! (Build_SpecCcsSynthesisError_record) <SpecCcsSynthesisError_f_constraint_index; SpecCcsSynthesisError_f_kind>.

Definition spec_value_to_bigint (value : t_SpecFieldValue) (field : t_FieldId) : t_BigInt :=
  normalize (impl_FieldElement__as_bigint (impl_SpecFieldValue__to_runtime (value))) (field).

Definition bigint_to_spec_value (value : t_BigInt) (field : t_FieldId) : t_SpecFieldValue :=
  impl_SpecFieldValue__from_runtime (impl_FieldElement__from_bigint_with_field (value) (field)).

Record SpecCcsBuilder_record : Type :=
  {
    SpecCcsBuilder_f_field : t_FieldId;
    SpecCcsBuilder_f_signal_columns : t_Vec ((t_usize)) ((t_Global));
    SpecCcsBuilder_f_next_col : t_usize;
    SpecCcsBuilder_f_num_public : t_usize;
    SpecCcsBuilder_f_row : t_usize;
    SpecCcsBuilder_f_a_entries : t_Vec ((t_SpecCcsMatrixEntry)) ((t_Global));
    SpecCcsBuilder_f_b_entries : t_Vec ((t_SpecCcsMatrixEntry)) ((t_Global));
    SpecCcsBuilder_f_c_entries : t_Vec ((t_SpecCcsMatrixEntry)) ((t_Global));
  }.









#[export] Instance settable_SpecCcsBuilder_record : Settable _ :=
  settable! (Build_SpecCcsBuilder_record) <SpecCcsBuilder_f_field; SpecCcsBuilder_f_signal_columns; SpecCcsBuilder_f_next_col; SpecCcsBuilder_f_num_public; SpecCcsBuilder_f_row; SpecCcsBuilder_f_a_entries; SpecCcsBuilder_f_b_entries; SpecCcsBuilder_f_c_entries>.

Definition builder_finish (builder : t_SpecCcsBuilder) (field : t_FieldId) : t_SpecCcsProgram :=
  let num_constraints := f_row builder in
  let rows := num_constraints in
  let cols := f_next_col builder in
  SpecCcsProgram (field) (num_constraints) (cols) (f_num_public builder) (impl__into_vec (unsize ([SpecCcsMatrix (rows) (cols) (f_a_entries builder); SpecCcsMatrix (rows) (cols) (f_b_entries builder); SpecCcsMatrix (rows) (cols) (f_c_entries builder)]))) (impl__into_vec (unsize ([SpecCcsMultiset (impl__into_vec (unsize ([(0 : t_usize); (1 : t_usize)]))) (bigint_to_spec_value (f_one (tt)) (field)); SpecCcsMultiset (impl__into_vec (unsize ([(2 : t_usize)]))) (bigint_to_spec_value (f_neg (f_one (tt))) (field))]))).

Definition builder_allocate_aux (builder : t_SpecCcsBuilder) : (t_SpecCcsBuilder*t_usize) :=
  let col := f_next_col builder in
  let builder := builder <|t_SpecCcsBuilderf_next_col := f_add (f_next_col builder) ((1 : t_usize)) |> in
  let hax_temp_output := col in
  (builder,hax_temp_output).

Definition lc_add_term (target : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) (col : t_usize) (coeff : t_BigInt) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  run (let _ := if
    f_is_zero (coeff)
  then
    let hoist56 := ControlFlow_Break (target) in
    ControlFlow_Continue (never_to_any (hoist56))
  else
    ControlFlow_Continue (tt) in
  ControlFlow_Continue (let (tmp0,out) := impl_20__remove (target) (col) in
  let target := tmp0 in
  let hoist57 := out in
  let hoist58 := impl__map (hoist57) (fun existing =>
    f_add (existing) (f_clone (coeff))) in
  let updated := impl__unwrap_or (hoist58) (coeff) in
  let target := if
    f_not (f_is_zero (updated))
  then
    let (tmp0,out) := impl_20__insert (target) (col) (updated) in
    let target := tmp0 in
    let _ := out in
    target
  else
    target in
  target)).

Definition lc_const (value : t_BigInt) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  let expr := impl_18__new (tt) in
  let expr := lc_add_term (expr) ((0 : t_usize)) (value) in
  expr.

Definition lc_var (col : t_usize) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  let expr := impl_18__new (tt) in
  let expr := lc_add_term (expr) (col) (f_one (tt)) in
  expr.

Definition builder_signal_lc (builder : t_SpecCcsBuilder) (signal_index : t_usize) (constraint_index : t_usize) : t_Result ((t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)))) ((t_SpecCcsSynthesisError)) :=
  run (match impl_2__copied (impl__get (f_deref (f_signal_columns builder)) (signal_index)) with
  | Option_Some (col) =>
    ControlFlow_Continue (Result_Ok (lc_var (col)))
  | _ =>
    let _ := ControlFlow_Break (Result_Err (SpecCcsSynthesisError (constraint_index) (SpecCcsSynthesisErrorKind_InvalidSignalIndex))) in
    ControlFlow_Continue (tt)
  end).

Definition lc_one '(_ : unit) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  lc_const (f_one (tt)).

Definition lc_one_minus_var (col : t_usize) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  let expr := lc_one (tt) in
  let expr := lc_add_term (expr) (col) (f_neg (f_one (tt))) in
  expr.

Definition lc_add_assign (target : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) (other : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  let target := f_fold (f_into_iter (other)) (target) (fun target (col,coeff) =>
    lc_add_term (target) (col) (f_clone (coeff))) in
  target.

Definition lc_sub_assign (target : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) (other : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  let target := f_fold (f_into_iter (other)) (target) (fun target (col,coeff) =>
    lc_add_term (target) (col) (f_neg (f_clone (coeff)))) in
  target.

Definition push_lc_entries (field : t_FieldId) (entries : t_Vec ((t_SpecCcsMatrixEntry)) ((t_Global))) (row : t_usize) (lc : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) : t_Vec ((t_SpecCcsMatrixEntry)) ((t_Global)) :=
  let entries := f_fold (f_into_iter (lc)) (entries) (fun entries (col,coeff) =>
    let normalized := normalize_mod (f_clone (coeff)) (impl_FieldId__modulus (field)) in
    if
      f_not (f_is_zero (normalized))
    then
      let entries := impl_1__push (entries) (SpecCcsMatrixEntry (row) (col) (bigint_to_spec_value (normalized) (field))) in
      entries
    else
      entries) in
  entries.

Definition builder_add_row (builder : t_SpecCcsBuilder) (a : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) (b : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) (c : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) : t_SpecCcsBuilder :=
  let row := f_row builder in
  let builder := builder <|t_SpecCcsBuilderf_a_entries := push_lc_entries (f_field builder) (f_a_entries builder) (row) (a) |> in
  let builder := builder <|t_SpecCcsBuilderf_b_entries := push_lc_entries (f_field builder) (f_b_entries builder) (row) (b) |> in
  let builder := builder <|t_SpecCcsBuilderf_c_entries := push_lc_entries (f_field builder) (f_c_entries builder) (row) (c) |> in
  let builder := builder <|t_SpecCcsBuilderf_row := f_add (f_row builder) ((1 : t_usize)) |> in
  builder.

Inductive t_SpecCcsExpr : Type :=
| SpecCcsExpr_Const : t_SpecFieldValue -> _
| SpecCcsExpr_Signal : t_usize -> _
| SpecCcsExpr_Add : t_Vec ((t_SpecCcsExpr)) ((t_Global)) -> _
| SpecCcsExpr_Sub : t_SpecCcsExpr -> t_SpecCcsExpr -> _
| SpecCcsExpr_Mul : t_SpecCcsExpr -> t_SpecCcsExpr -> _
| SpecCcsExpr_Div : t_SpecCcsExpr -> t_SpecCcsExpr -> _.







Record SpecCcsConstraint_Equal_record : Type :=
  {
    SpecCcsConstraint_Equal_f_lhs : t_SpecCcsExpr;
    SpecCcsConstraint_Equal_f_rhs : t_SpecCcsExpr;
  }.



#[export] Instance settable_SpecCcsConstraint_Equal_record : Settable _ :=
  settable! (Build_SpecCcsConstraint_Equal_record) <SpecCcsConstraint_Equal_f_lhs; SpecCcsConstraint_Equal_f_rhs>.
Record SpecCcsConstraint_Boolean_record : Type :=
  {
    SpecCcsConstraint_Boolean_f_signal_index : t_usize;
  }.


#[export] Instance settable_SpecCcsConstraint_Boolean_record : Settable _ :=
  settable! (Build_SpecCcsConstraint_Boolean_record) <SpecCcsConstraint_Boolean_f_signal_index>.
Record SpecCcsConstraint_Range_record : Type :=
  {
    SpecCcsConstraint_Range_f_signal_index : t_usize;
    SpecCcsConstraint_Range_f_bits : t_u32;
  }.



#[export] Instance settable_SpecCcsConstraint_Range_record : Settable _ :=
  settable! (Build_SpecCcsConstraint_Range_record) <SpecCcsConstraint_Range_f_signal_index; SpecCcsConstraint_Range_f_bits>.
Record SpecCcsConstraint_BlackBox_record : Type :=
  {
    SpecCcsConstraint_BlackBox_f_kind : t_SpecCcsBlackBoxKind;
  }.


#[export] Instance settable_SpecCcsConstraint_BlackBox_record : Settable _ :=
  settable! (Build_SpecCcsConstraint_BlackBox_record) <SpecCcsConstraint_BlackBox_f_kind>.
Inductive t_SpecCcsConstraint : Type :=
| SpecCcsConstraint_Equal : SpecCcsConstraint_Equal_record  -> _
| SpecCcsConstraint_Boolean : SpecCcsConstraint_Boolean_record  -> _
| SpecCcsConstraint_Range : SpecCcsConstraint_Range_record  -> _
| SpecCcsConstraint_Lookup
| SpecCcsConstraint_BlackBox : SpecCcsConstraint_BlackBox_record  -> _.






Record SpecCcsConstraintProgram_record : Type :=
  {
    SpecCcsConstraintProgram_f_field : t_FieldId;
    SpecCcsConstraintProgram_f_signals : t_Vec ((t_SpecCcsSignal)) ((t_Global));
    SpecCcsConstraintProgram_f_constraints : t_Vec ((t_SpecCcsConstraint)) ((t_Global));
  }.




#[export] Instance settable_SpecCcsConstraintProgram_record : Settable _ :=
  settable! (Build_SpecCcsConstraintProgram_record) <SpecCcsConstraintProgram_f_field; SpecCcsConstraintProgram_f_signals; SpecCcsConstraintProgram_f_constraints>.

Definition builder_new (program : t_SpecCcsConstraintProgram) : t_SpecCcsBuilder :=
  let signal_columns := from_elem ((0 : t_usize)) (impl_1__len (f_signals program)) in
  let next_col := (1 : t_usize) in
  let num_public := (0 : t_usize) in
  let (next_col,num_public,signal_columns) := fold_enumerated_slice (f_deref (f_signals program)) (fun (next_col,num_public,signal_columns) _ =>
    (true : bool)) ((next_col,num_public,signal_columns)) (fun (next_col,num_public,signal_columns) (signal_index,signal) =>
    if
      f_eq (f_visibility signal) (SpecCcsVisibility_Public)
    then
      let signal_columns := impl__to_vec (update_at_usize (impl_1__as_slice (signal_columns)) (signal_index) (next_col)) in
      let next_col := f_add (next_col) ((1 : t_usize)) in
      let num_public := f_add (num_public) ((1 : t_usize)) in
      (next_col,num_public,signal_columns)
    else
      (next_col,num_public,signal_columns)) in
  let (next_col,signal_columns) := fold_enumerated_slice (f_deref (f_signals program)) (fun (next_col,signal_columns) _ =>
    (true : bool)) ((next_col,signal_columns)) (fun (next_col,signal_columns) (signal_index,signal) =>
    if
      f_ne (f_visibility signal) (SpecCcsVisibility_Public)
    then
      let signal_columns := impl__to_vec (update_at_usize (impl_1__as_slice (signal_columns)) (signal_index) (next_col)) in
      let next_col := f_add (next_col) ((1 : t_usize)) in
      (next_col,signal_columns)
    else
      (next_col,signal_columns)) in
  SpecCcsBuilder (f_field program) (signal_columns) (next_col) (num_public) ((0 : t_usize)) (impl__new (tt)) (impl__new (tt)) (impl__new (tt)).

Fixpoint builder_expr_to_lc (builder : t_SpecCcsBuilder) (expr : t_SpecCcsExpr) (constraint_index : t_usize) : (t_SpecCcsBuilder*t_Result ((t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)))) ((t_SpecCcsSynthesisError))) :=
  run (let (builder,hax_temp_output) := match expr with
  | SpecCcsExpr_Const (value) =>
    ControlFlow_Continue ((builder,Result_Ok (lc_const (spec_value_to_bigint (value) (f_field builder)))))
  | SpecCcsExpr_Signal (signal_index) =>
    ControlFlow_Continue ((builder,builder_signal_lc (builder) (signal_index) (constraint_index)))
  | SpecCcsExpr_Add (terms) =>
    ControlFlow_Continue (let acc := impl_18__new (tt) in
    let (acc,builder) := f_fold (f_into_iter (terms)) ((acc,builder)) (fun (acc,builder) term =>
      let (tmp0,out) := builder_expr_to_lc (builder) (term) (constraint_index) in
      let builder := tmp0 in
      let hoist2 := out in
      let hoist3 := f_branch (hoist2) in
      let hoist4 := match hoist3 with
      | ControlFlow_Break (residual) =>
        let hoist1 := ControlFlow_Break ((builder,f_from_residual (residual))) in
        ControlFlow_Continue (never_to_any (hoist1))
      | ControlFlow_Continue (val) =>
        ControlFlow_Continue (val)
      end in
      ControlFlow_Continue (let hoist5 := lc_add_assign (acc) (hoist4) in
      (hoist5,builder))) in
    (builder,Result_Ok (acc)))
  | SpecCcsExpr_Sub (lhs) (rhs) =>
    let (tmp0,out) := builder_expr_to_lc (builder) (lhs) (constraint_index) in
    let builder := tmp0 in
    let hoist7 := out in
    let hoist8 := f_branch (hoist7) in
    let acc := match hoist8 with
    | ControlFlow_Break (residual) =>
      let hoist6 := ControlFlow_Break ((builder,f_from_residual (residual))) in
      ControlFlow_Continue (never_to_any (hoist6))
    | ControlFlow_Continue (val) =>
      ControlFlow_Continue (val)
    end in
    let (tmp0,out) := builder_expr_to_lc (builder) (rhs) (constraint_index) in
    let builder := tmp0 in
    let hoist10 := out in
    let hoist11 := f_branch (hoist10) in
    let hoist12 := match hoist11 with
    | ControlFlow_Break (residual) =>
      let hoist9 := ControlFlow_Break ((builder,f_from_residual (residual))) in
      ControlFlow_Continue (never_to_any (hoist9))
    | ControlFlow_Continue (val) =>
      ControlFlow_Continue (val)
    end in
    ControlFlow_Continue (let hoist13 := lc_sub_assign (acc) (hoist12) in
    let acc := hoist13 in
    (builder,Result_Ok (acc)))
  | SpecCcsExpr_Mul (lhs) (rhs) =>
    let (tmp0,out) := builder_expr_to_lc (builder) (lhs) (constraint_index) in
    let builder := tmp0 in
    let hoist15 := out in
    let hoist16 := f_branch (hoist15) in
    let lhs_lc := match hoist16 with
    | ControlFlow_Break (residual) =>
      let hoist14 := ControlFlow_Break ((builder,f_from_residual (residual))) in
      ControlFlow_Continue (never_to_any (hoist14))
    | ControlFlow_Continue (val) =>
      ControlFlow_Continue (val)
    end in
    let (tmp0,out) := builder_expr_to_lc (builder) (rhs) (constraint_index) in
    let builder := tmp0 in
    let hoist18 := out in
    let hoist19 := f_branch (hoist18) in
    let rhs_lc := match hoist19 with
    | ControlFlow_Break (residual) =>
      let hoist17 := ControlFlow_Break ((builder,f_from_residual (residual))) in
      ControlFlow_Continue (never_to_any (hoist17))
    | ControlFlow_Continue (val) =>
      ControlFlow_Continue (val)
    end in
    ControlFlow_Continue (let (tmp0,out) := builder_allocate_aux (builder) in
    let builder := tmp0 in
    let aux_col := out in
    let builder := builder_add_row (builder) (lhs_lc) (rhs_lc) (lc_var (aux_col)) in
    (builder,Result_Ok (lc_var (aux_col))))
  | SpecCcsExpr_Div (lhs) (rhs) =>
    let (tmp0,out) := builder_expr_to_lc (builder) (lhs) (constraint_index) in
    let builder := tmp0 in
    let hoist21 := out in
    let hoist22 := f_branch (hoist21) in
    let numerator := match hoist22 with
    | ControlFlow_Break (residual) =>
      let hoist20 := ControlFlow_Break ((builder,f_from_residual (residual))) in
      ControlFlow_Continue (never_to_any (hoist20))
    | ControlFlow_Continue (val) =>
      ControlFlow_Continue (val)
    end in
    let (tmp0,out) := builder_expr_to_lc (builder) (rhs) (constraint_index) in
    let builder := tmp0 in
    let hoist24 := out in
    let hoist25 := f_branch (hoist24) in
    let denominator := match hoist25 with
    | ControlFlow_Break (residual) =>
      let hoist23 := ControlFlow_Break ((builder,f_from_residual (residual))) in
      ControlFlow_Continue (never_to_any (hoist23))
    | ControlFlow_Continue (val) =>
      ControlFlow_Continue (val)
    end in
    ControlFlow_Continue (let (tmp0,out) := builder_allocate_aux (builder) in
    let builder := tmp0 in
    let quotient_col := out in
    let (tmp0,out) := builder_allocate_aux (builder) in
    let builder := tmp0 in
    let inverse_col := out in
    let builder := builder_add_row (builder) (f_clone (denominator)) (lc_var (inverse_col)) (lc_one (tt)) in
    let builder := builder_add_row (builder) (lc_var (quotient_col)) (denominator) (numerator) in
    (builder,Result_Ok (lc_var (quotient_col))))
  end in
  ControlFlow_Continue ((builder,hax_temp_output))).

Definition encode_constraint_runtime (builder : t_SpecCcsBuilder) (constraint : t_SpecCcsConstraint) (constraint_index : t_usize) : (t_SpecCcsBuilder*t_Result ((unit)) ((t_SpecCcsSynthesisError))) :=
  run (let (builder,hax_temp_output) := match constraint with
  | SpecCcsConstraint_Equal (lhs) (rhs) =>
    let builder := match lhs with
    | SpecCcsExpr_Mul (left) (right) =>
      let (tmp0,out) := builder_expr_to_lc (builder) (left) (constraint_index) in
      let builder := tmp0 in
      let hoist27 := out in
      let hoist28 := f_branch (hoist27) in
      let a := match hoist28 with
      | ControlFlow_Break (residual) =>
        let hoist26 := ControlFlow_Break ((builder,f_from_residual (residual))) in
        ControlFlow_Continue (never_to_any (hoist26))
      | ControlFlow_Continue (val) =>
        ControlFlow_Continue (val)
      end in
      let (tmp0,out) := builder_expr_to_lc (builder) (right) (constraint_index) in
      let builder := tmp0 in
      let hoist30 := out in
      let hoist31 := f_branch (hoist30) in
      let b := match hoist31 with
      | ControlFlow_Break (residual) =>
        let hoist29 := ControlFlow_Break ((builder,f_from_residual (residual))) in
        ControlFlow_Continue (never_to_any (hoist29))
      | ControlFlow_Continue (val) =>
        ControlFlow_Continue (val)
      end in
      let (tmp0,out) := builder_expr_to_lc (builder) (rhs) (constraint_index) in
      let builder := tmp0 in
      let hoist33 := out in
      let hoist34 := f_branch (hoist33) in
      let c := match hoist34 with
      | ControlFlow_Break (residual) =>
        let hoist32 := ControlFlow_Break ((builder,f_from_residual (residual))) in
        ControlFlow_Continue (never_to_any (hoist32))
      | ControlFlow_Continue (val) =>
        ControlFlow_Continue (val)
      end in
      let builder := builder_add_row (builder) (a) (b) (c) in
      let hoist35 := ControlFlow_Break ((builder,Result_Ok (tt))) in
      ControlFlow_Continue (builder)
    | _ =>
      ControlFlow_Continue (builder)
    end in
    let builder := match rhs with
    | SpecCcsExpr_Mul (left) (right) =>
      let (tmp0,out) := builder_expr_to_lc (builder) (left) (constraint_index) in
      let builder := tmp0 in
      let hoist37 := out in
      let hoist38 := f_branch (hoist37) in
      let a := match hoist38 with
      | ControlFlow_Break (residual) =>
        let hoist36 := ControlFlow_Break ((builder,f_from_residual (residual))) in
        ControlFlow_Continue (never_to_any (hoist36))
      | ControlFlow_Continue (val) =>
        ControlFlow_Continue (val)
      end in
      let (tmp0,out) := builder_expr_to_lc (builder) (right) (constraint_index) in
      let builder := tmp0 in
      let hoist40 := out in
      let hoist41 := f_branch (hoist40) in
      let b := match hoist41 with
      | ControlFlow_Break (residual) =>
        let hoist39 := ControlFlow_Break ((builder,f_from_residual (residual))) in
        ControlFlow_Continue (never_to_any (hoist39))
      | ControlFlow_Continue (val) =>
        ControlFlow_Continue (val)
      end in
      let (tmp0,out) := builder_expr_to_lc (builder) (lhs) (constraint_index) in
      let builder := tmp0 in
      let hoist43 := out in
      let hoist44 := f_branch (hoist43) in
      let c := match hoist44 with
      | ControlFlow_Break (residual) =>
        let hoist42 := ControlFlow_Break ((builder,f_from_residual (residual))) in
        ControlFlow_Continue (never_to_any (hoist42))
      | ControlFlow_Continue (val) =>
        ControlFlow_Continue (val)
      end in
      let builder := builder_add_row (builder) (a) (b) (c) in
      let hoist45 := ControlFlow_Break ((builder,Result_Ok (tt))) in
      ControlFlow_Continue (builder)
    | _ =>
      ControlFlow_Continue (builder)
    end in
    let (tmp0,out) := builder_expr_to_lc (builder) (lhs) (constraint_index) in
    let builder := tmp0 in
    let hoist47 := out in
    let hoist48 := f_branch (hoist47) in
    let lhs_lc := match hoist48 with
    | ControlFlow_Break (residual) =>
      let hoist46 := ControlFlow_Break ((builder,f_from_residual (residual))) in
      ControlFlow_Continue (never_to_any (hoist46))
    | ControlFlow_Continue (val) =>
      ControlFlow_Continue (val)
    end in
    let (tmp0,out) := builder_expr_to_lc (builder) (rhs) (constraint_index) in
    let builder := tmp0 in
    let hoist50 := out in
    let hoist51 := f_branch (hoist50) in
    let rhs_lc := match hoist51 with
    | ControlFlow_Break (residual) =>
      let hoist49 := ControlFlow_Break ((builder,f_from_residual (residual))) in
      ControlFlow_Continue (never_to_any (hoist49))
    | ControlFlow_Continue (val) =>
      ControlFlow_Continue (val)
    end in
    ControlFlow_Continue (let diff := lhs_lc in
    let diff := lc_sub_assign (diff) (rhs_lc) in
    let builder := builder_add_row (builder) (diff) (lc_one (tt)) (impl_18__new (tt)) in
    (builder,Result_Ok (tt)))
  | SpecCcsConstraint_Boolean (signal_index) =>
    let value := match f_branch (builder_signal_lc (builder) (signal_index) (constraint_index)) with
    | ControlFlow_Break (residual) =>
      let hoist52 := ControlFlow_Break ((builder,f_from_residual (residual))) in
      ControlFlow_Continue (never_to_any (hoist52))
    | ControlFlow_Continue (val) =>
      ControlFlow_Continue (val)
    end in
    let col := match f_branch (impl__ok_or (impl_2__copied (impl__get (f_deref (f_signal_columns builder)) (signal_index))) (SpecCcsSynthesisError (constraint_index) (SpecCcsSynthesisErrorKind_InvalidSignalIndex))) with
    | ControlFlow_Break (residual) =>
      let hoist53 := ControlFlow_Break ((builder,f_from_residual (residual))) in
      ControlFlow_Continue (never_to_any (hoist53))
    | ControlFlow_Continue (val) =>
      ControlFlow_Continue (val)
    end in
    ControlFlow_Continue (let builder := builder_add_row (builder) (value) (lc_one_minus_var (col)) (impl_18__new (tt)) in
    (builder,Result_Ok (tt)))
  | SpecCcsConstraint_Range (signal_index) (bits) =>
    let signal_value := match f_branch (builder_signal_lc (builder) (signal_index) (constraint_index)) with
    | ControlFlow_Break (residual) =>
      let hoist54 := ControlFlow_Break ((builder,f_from_residual (residual))) in
      ControlFlow_Continue (never_to_any (hoist54))
    | ControlFlow_Continue (val) =>
      ControlFlow_Continue (val)
    end in
    ControlFlow_Continue (let recomposed := impl_18__new (tt) in
    let (builder,recomposed) := fold_range ((0 : t_u32)) (bits) (fun (builder,recomposed) _ =>
      (true : bool)) ((builder,recomposed)) (fun (builder,recomposed) bit =>
      let (tmp0,out) := builder_allocate_aux (builder) in
      let builder := tmp0 in
      let bit_col := out in
      let builder := builder_add_row (builder) (lc_var (bit_col)) (lc_one_minus_var (bit_col)) (impl_18__new (tt)) in
      let recomposed := lc_add_term (recomposed) (bit_col) (f_shl (f_one (tt)) (impl__unwrap_or (f_try_from (bit)) ((0 : t_usize)))) in
      (builder,recomposed)) in
    let builder := builder_add_row (builder) (signal_value) (lc_one (tt)) (recomposed) in
    (builder,Result_Ok (tt)))
  | SpecCcsConstraint_Lookup =>
    ControlFlow_Continue ((builder,Result_Err (SpecCcsSynthesisError (constraint_index) (SpecCcsSynthesisErrorKind_LookupRequiresLowering))))
  | SpecCcsConstraint_BlackBox (SpecCcsBlackBoxKind_RecursiveAggregationMarker) =>
    ControlFlow_Continue ((builder,Result_Ok (tt)))
  | SpecCcsConstraint_BlackBox =>
    ControlFlow_Continue ((builder,Result_Err (SpecCcsSynthesisError (constraint_index) (SpecCcsSynthesisErrorKind_BlackBoxRequiresLowering))))
  end in
  ControlFlow_Continue ((builder,hax_temp_output))).

Fixpoint synthesize_constraints_from (builder : t_SpecCcsBuilder) (constraints : t_Slice t_SpecCcsConstraint) (constraint_index : t_usize) : t_Result ((t_SpecCcsBuilder)) ((t_SpecCcsSynthesisError)) :=
  run (match impl__split_first (constraints) with
  | Option_Some ((constraint,remaining_constraints)) =>
    ControlFlow_Continue (let builder := builder in
    let (tmp0,out) := encode_constraint_runtime (builder) (constraint) (constraint_index) in
    let builder := tmp0 in
    let hoist55 := out in
    match hoist55 with
    | Result_Ok (()) =>
      synthesize_constraints_from (builder) (remaining_constraints) (impl_usize__saturating_add (constraint_index) ((1 : t_usize)))
    | Result_Err (error) =>
      Result_Err (error)
    end)
  | _ =>
    let _ := ControlFlow_Break (Result_Ok (builder)) in
    ControlFlow_Continue (tt)
  end).

Definition synthesize_ccs_program (program : t_SpecCcsConstraintProgram) : t_Result ((t_SpecCcsProgram)) ((t_SpecCcsSynthesisError)) :=
  let builder := builder_new (program) in
  match synthesize_constraints_from (builder) (f_deref (f_constraints program)) ((0 : t_usize)) with
  | Result_Ok (builder) =>
    Result_Ok (builder_finish (builder) (f_field program))
  | Result_Err (error) =>
    Result_Err (error)
  end.
