(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

Inductive t_FieldId : Type :=
| FieldId_Bn254
| FieldId_Bls12_381_
| FieldId_PastaFp
| FieldId_PastaFq
| FieldId_Goldilocks
| FieldId_BabyBear
| FieldId_Mersenne31.








Record FieldElement_record : Type :=
  {
    FieldElement_f_bytes : t_Array (t_u8) ((32 : t_usize));
    FieldElement_f_len : t_u8;
    FieldElement_f_negative : bool;
  }.




#[export] Instance settable_FieldElement_record : Settable _ :=
  settable! (Build_FieldElement_record) <FieldElement_f_bytes; FieldElement_f_len; FieldElement_f_negative>.
