(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.
Require Import KernelCompat.

(* NotImplementedYet *)

Definition preserve_successful_artifact_bytes (artifact : t_Vec ((t_u8)) ((t_Global))) : t_Vec ((t_u8)) ((t_Global)) :=
  artifact.

Fixpoint u8_list_eq (left : list t_u8) (right : list t_u8) : bool :=
  match left, right with
  | [], [] =>
    (true : bool)
  | left_head :: left_tail, right_head :: right_tail =>
    andb
      (N.eqb (U8_f_v (u8_0 left_head)) (U8_f_v (u8_0 right_head)))
      (u8_list_eq left_tail right_tail)
  | _, _ =>
    (false : bool)
  end.

Definition artifact_bytes_eq (left : t_Array (t_u8) ((4 : t_usize))) (right : t_Array (t_u8) ((4 : t_usize))) : bool :=
  u8_list_eq
    (Slice_f_v (Array_f_v left))
    (Slice_f_v (Array_f_v right)).

Inductive t_ProofSwarmActivationLevel : Type :=
| ProofSwarmActivationLevel_Dormant
| ProofSwarmActivationLevel_Alert
| ProofSwarmActivationLevel_Active
| ProofSwarmActivationLevel_Emergency.





Record ProofDisabledSwarmSurfaceState_record : Type :=
  {
    ProofDisabledSwarmSurfaceState_f_activation_level : t_ProofSwarmActivationLevel;
    ProofDisabledSwarmSurfaceState_f_verdict_activation_level : t_ProofSwarmActivationLevel;
    ProofDisabledSwarmSurfaceState_f_threat_digest_count : t_usize;
    ProofDisabledSwarmSurfaceState_f_consensus_confirmed : bool;
    ProofDisabledSwarmSurfaceState_f_telemetry_present : bool;
    ProofDisabledSwarmSurfaceState_f_bias_basis_points : t_u16;
  }.
Definition t_ProofDisabledSwarmSurfaceState := ProofDisabledSwarmSurfaceState_record.







#[export] Instance settable_ProofDisabledSwarmSurfaceState_record : Settable _ :=
  settable! (Build_ProofDisabledSwarmSurfaceState_record) <ProofDisabledSwarmSurfaceState_f_activation_level; ProofDisabledSwarmSurfaceState_f_verdict_activation_level; ProofDisabledSwarmSurfaceState_f_threat_digest_count; ProofDisabledSwarmSurfaceState_f_consensus_confirmed; ProofDisabledSwarmSurfaceState_f_telemetry_present; ProofDisabledSwarmSurfaceState_f_bias_basis_points>.
Definition ProofDisabledSwarmSurfaceState := Build_ProofDisabledSwarmSurfaceState_record.
Notation f_activation_level := ProofDisabledSwarmSurfaceState_f_activation_level.
Notation t_ProofDisabledSwarmSurfaceStatef_activation_level := ProofDisabledSwarmSurfaceState_f_activation_level.
Notation f_verdict_activation_level := ProofDisabledSwarmSurfaceState_f_verdict_activation_level.
Notation t_ProofDisabledSwarmSurfaceStatef_verdict_activation_level := ProofDisabledSwarmSurfaceState_f_verdict_activation_level.
Notation f_threat_digest_count := ProofDisabledSwarmSurfaceState_f_threat_digest_count.
Notation t_ProofDisabledSwarmSurfaceStatef_threat_digest_count := ProofDisabledSwarmSurfaceState_f_threat_digest_count.
Notation f_consensus_confirmed := ProofDisabledSwarmSurfaceState_f_consensus_confirmed.
Notation t_ProofDisabledSwarmSurfaceStatef_consensus_confirmed := ProofDisabledSwarmSurfaceState_f_consensus_confirmed.
Notation f_telemetry_present := ProofDisabledSwarmSurfaceState_f_telemetry_present.
Notation t_ProofDisabledSwarmSurfaceStatef_telemetry_present := ProofDisabledSwarmSurfaceState_f_telemetry_present.
Notation f_bias_basis_points := ProofDisabledSwarmSurfaceState_f_bias_basis_points.
Notation t_ProofDisabledSwarmSurfaceStatef_bias_basis_points := ProofDisabledSwarmSurfaceState_f_bias_basis_points.

Definition activation_level_rank (level : t_ProofSwarmActivationLevel) : t_u8 :=
  match level with
  | ProofSwarmActivationLevel_Dormant =>
    (0 : t_u8)
  | ProofSwarmActivationLevel_Alert =>
    (1 : t_u8)
  | ProofSwarmActivationLevel_Active =>
    (2 : t_u8)
  | ProofSwarmActivationLevel_Emergency =>
    (3 : t_u8)
  end.

Definition disabled_surface_state_spec '(_ : unit) : t_ProofDisabledSwarmSurfaceState :=
  ProofDisabledSwarmSurfaceState (ProofSwarmActivationLevel_Dormant) (ProofSwarmActivationLevel_Dormant) ((0 : t_usize)) ((false : bool)) ((false : bool)) ((1000 : t_u16)).

Definition controller_artifact_path (enabled : bool) (artifact : t_Array (t_u8) ((4 : t_usize))) (reject : bool) : t_Result ((t_Array (t_u8) ((4 : t_usize)))) ((unit)) :=
  match (enabled,reject) with
  | (false,_) =>
    Result_Ok (artifact)
  | (true,true) =>
    Result_Err (tt)
  | (true,false) =>
    Result_Ok (artifact)
  end.

Definition controller_artifact_path_matches_pure_helper (enabled : bool) (artifact : t_Array (t_u8) ((4 : t_usize))) (reject : bool) : bool :=
  match controller_artifact_path (enabled) (artifact) (reject) with
  | Result_Ok (artifact_out) =>
    artifact_bytes_eq (artifact_out) (artifact)
  | Result_Err _ =>
    andb (enabled) (reject)
  end.

Definition successful_artifact_path_preserves_bytes (enabled : bool) (artifact : t_Array (t_u8) ((4 : t_usize))) : bool :=
  match controller_artifact_path (enabled) (artifact) ((false : bool)) with
  | Result_Ok (artifact_out) =>
    artifact_bytes_eq (artifact_out) (artifact)
  | Result_Err _ =>
    (false : bool)
  end.

Definition encrypted_gossip_artifact_projection (artifact : t_Array (t_u8) ((4 : t_usize))) : t_Array (t_u8) ((4 : t_usize)) :=
  artifact.

Definition encrypted_gossip_surface_preserves_artifact_bytes (artifact : t_Array (t_u8) ((4 : t_usize))) : bool :=
  artifact_bytes_eq (encrypted_gossip_artifact_projection (artifact)) (artifact).

Definition encrypted_gossip_fail_closed_spec (negotiated : bool) (plaintext_present : bool) (encrypted_payload_present : bool) : bool :=
  if
    negotiated
  then
    f_not (plaintext_present)
  else
    andb (f_not (plaintext_present)) (f_not (encrypted_payload_present)).

Definition controller_artifact_mutation_surface_count '(_ : unit) : t_usize :=
  (0 : t_usize).

Definition cooldown_tick_level (level : t_ProofSwarmActivationLevel) (cooldown_active : bool) : t_ProofSwarmActivationLevel :=
  if
    cooldown_active
  then
    level
  else
    match level with
    | ProofSwarmActivationLevel_Dormant =>
      ProofSwarmActivationLevel_Dormant
    | ProofSwarmActivationLevel_Alert =>
      ProofSwarmActivationLevel_Dormant
    | ProofSwarmActivationLevel_Active =>
      ProofSwarmActivationLevel_Alert
    | ProofSwarmActivationLevel_Emergency =>
      ProofSwarmActivationLevel_Active
    end.

Definition cooldown_tick_is_non_deescalating (level : t_ProofSwarmActivationLevel) : bool :=
  match level with
  | ProofSwarmActivationLevel_Dormant =>
    match cooldown_tick_level (level) ((true : bool)) with
    | ProofSwarmActivationLevel_Dormant =>
      (true : bool)
    | _ =>
      (false : bool)
    end
  | ProofSwarmActivationLevel_Alert =>
    match cooldown_tick_level (level) ((true : bool)) with
    | ProofSwarmActivationLevel_Alert =>
      (true : bool)
    | _ =>
      (false : bool)
    end
  | ProofSwarmActivationLevel_Active =>
    match cooldown_tick_level (level) ((true : bool)) with
    | ProofSwarmActivationLevel_Active =>
      (true : bool)
    | _ =>
      (false : bool)
    end
  | ProofSwarmActivationLevel_Emergency =>
    match cooldown_tick_level (level) ((true : bool)) with
    | ProofSwarmActivationLevel_Emergency =>
      (true : bool)
    | _ =>
      (false : bool)
    end
  end.

Definition cooldown_tick_drops_at_most_one_level (level : t_ProofSwarmActivationLevel) : bool :=
  match level with
  | ProofSwarmActivationLevel_Dormant =>
    match cooldown_tick_level (level) ((false : bool)) with
    | ProofSwarmActivationLevel_Dormant =>
      (true : bool)
    | _ =>
      (false : bool)
    end
  | ProofSwarmActivationLevel_Alert =>
    match cooldown_tick_level (level) ((false : bool)) with
    | ProofSwarmActivationLevel_Dormant =>
      (true : bool)
    | _ =>
      (false : bool)
    end
  | ProofSwarmActivationLevel_Active =>
    match cooldown_tick_level (level) ((false : bool)) with
    | ProofSwarmActivationLevel_Alert =>
      (true : bool)
    | _ =>
      (false : bool)
    end
  | ProofSwarmActivationLevel_Emergency =>
    match cooldown_tick_level (level) ((false : bool)) with
    | ProofSwarmActivationLevel_Active =>
      (true : bool)
    | _ =>
      (false : bool)
    end
  end.
