(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.
Require Import KernelCompat.

(* NotImplementedYet *)

Inductive t_ProofRuntimeFieldId : Type :=
| ProofRuntimeFieldId_Bn254
| ProofRuntimeFieldId_Bls12_381_
| ProofRuntimeFieldId_PastaFp
| ProofRuntimeFieldId_PastaFq
| ProofRuntimeFieldId_Goldilocks
| ProofRuntimeFieldId_BabyBear
| ProofRuntimeFieldId_Mersenne31.








Inductive t_ProofRuntimeBackendKind : Type :=
| ProofRuntimeBackendKind_ArkworksGroth16
| ProofRuntimeBackendKind_Plonky3
| ProofRuntimeBackendKind_Nova
| ProofRuntimeBackendKind_HyperNova
| ProofRuntimeBackendKind_Halo2
| ProofRuntimeBackendKind_Halo2Bls12381
| ProofRuntimeBackendKind_Sp1
| ProofRuntimeBackendKind_RiscZero
| ProofRuntimeBackendKind_MidnightCompact.










Definition preferred_backend_for_proof_field_spec (field : t_ProofRuntimeFieldId) : t_ProofRuntimeBackendKind :=
  match field with
  | ProofRuntimeFieldId_Bn254 =>
    ProofRuntimeBackendKind_ArkworksGroth16
  | ProofRuntimeFieldId_Bls12_381_ =>
    ProofRuntimeBackendKind_Halo2Bls12381
  | ProofRuntimeFieldId_PastaFp
  | ProofRuntimeFieldId_PastaFq =>
    ProofRuntimeBackendKind_Halo2
  | ProofRuntimeFieldId_Goldilocks
  | ProofRuntimeFieldId_BabyBear
  | ProofRuntimeFieldId_Mersenne31 =>
    ProofRuntimeBackendKind_Plonky3
  end.

Definition default_backend_candidates_for_proof_field (field : t_ProofRuntimeFieldId) : t_Vec ((t_ProofRuntimeBackendKind)) ((t_Global)) :=
  match field with
  | ProofRuntimeFieldId_Bn254 =>
    impl__into_vec (unsize ([ProofRuntimeBackendKind_ArkworksGroth16; ProofRuntimeBackendKind_Plonky3; ProofRuntimeBackendKind_Nova; ProofRuntimeBackendKind_HyperNova; ProofRuntimeBackendKind_Halo2; ProofRuntimeBackendKind_Halo2Bls12381; ProofRuntimeBackendKind_Sp1; ProofRuntimeBackendKind_RiscZero; ProofRuntimeBackendKind_MidnightCompact]))
  | ProofRuntimeFieldId_Bls12_381_ =>
    impl__into_vec (unsize ([ProofRuntimeBackendKind_Halo2Bls12381; ProofRuntimeBackendKind_ArkworksGroth16; ProofRuntimeBackendKind_Plonky3; ProofRuntimeBackendKind_Nova; ProofRuntimeBackendKind_HyperNova; ProofRuntimeBackendKind_Halo2; ProofRuntimeBackendKind_Sp1; ProofRuntimeBackendKind_RiscZero; ProofRuntimeBackendKind_MidnightCompact]))
  | ProofRuntimeFieldId_PastaFp
  | ProofRuntimeFieldId_PastaFq =>
    impl__into_vec (unsize ([ProofRuntimeBackendKind_Halo2; ProofRuntimeBackendKind_ArkworksGroth16; ProofRuntimeBackendKind_Plonky3; ProofRuntimeBackendKind_Nova; ProofRuntimeBackendKind_HyperNova; ProofRuntimeBackendKind_Halo2Bls12381; ProofRuntimeBackendKind_Sp1; ProofRuntimeBackendKind_RiscZero; ProofRuntimeBackendKind_MidnightCompact]))
  | ProofRuntimeFieldId_Goldilocks
  | ProofRuntimeFieldId_BabyBear
  | ProofRuntimeFieldId_Mersenne31 =>
    impl__into_vec (unsize ([ProofRuntimeBackendKind_Plonky3; ProofRuntimeBackendKind_ArkworksGroth16; ProofRuntimeBackendKind_Nova; ProofRuntimeBackendKind_HyperNova; ProofRuntimeBackendKind_Halo2; ProofRuntimeBackendKind_Halo2Bls12381; ProofRuntimeBackendKind_Sp1; ProofRuntimeBackendKind_RiscZero; ProofRuntimeBackendKind_MidnightCompact]))
  end.

Definition runtime_default_backend_candidates_are_nonempty (e_field : t_ProofRuntimeFieldId) : bool :=
  (true : bool).

Definition hybrid_verify_decision_spec (primary_ok : bool) (companion_ok : bool) : bool :=
  andb (primary_ok) (companion_ok).

Record ProofRuntimeHardwareProbeSummary_record : Type :=
  {
    ProofRuntimeHardwareProbeSummary_f_ok : bool;
    ProofRuntimeHardwareProbeSummary_f_mismatch_free : bool;
  }.
Definition t_ProofRuntimeHardwareProbeSummary := ProofRuntimeHardwareProbeSummary_record.



#[export] Instance settable_ProofRuntimeHardwareProbeSummary_record : Settable _ :=
  settable! (Build_ProofRuntimeHardwareProbeSummary_record) <ProofRuntimeHardwareProbeSummary_f_ok; ProofRuntimeHardwareProbeSummary_f_mismatch_free>.
Definition ProofRuntimeHardwareProbeSummary := Build_ProofRuntimeHardwareProbeSummary_record.
Notation f_ok := ProofRuntimeHardwareProbeSummary_f_ok.
Notation t_ProofRuntimeHardwareProbeSummaryf_ok := ProofRuntimeHardwareProbeSummary_f_ok.
Notation f_mismatch_free := ProofRuntimeHardwareProbeSummary_f_mismatch_free.
Notation t_ProofRuntimeHardwareProbeSummaryf_mismatch_free := ProofRuntimeHardwareProbeSummary_f_mismatch_free.

Definition hardware_probes_clean_spec (summary : t_ProofRuntimeHardwareProbeSummary) : bool :=
  andb (f_ok summary) (f_mismatch_free summary).

Record ProofRuntimeReplayManifestIdentity_record : Type :=
  {
    ProofRuntimeReplayManifestIdentity_f_replay_id : t_String;
    ProofRuntimeReplayManifestIdentity_f_transcript_hash : t_String;
    ProofRuntimeReplayManifestIdentity_f_backend_route : t_String;
    ProofRuntimeReplayManifestIdentity_f_hardware_profile : t_String;
    ProofRuntimeReplayManifestIdentity_f_stage_manifest_digest : t_String;
  }.
Definition t_ProofRuntimeReplayManifestIdentity := ProofRuntimeReplayManifestIdentity_record.






#[export] Instance settable_ProofRuntimeReplayManifestIdentity_record : Settable _ :=
  settable! (Build_ProofRuntimeReplayManifestIdentity_record) <ProofRuntimeReplayManifestIdentity_f_replay_id; ProofRuntimeReplayManifestIdentity_f_transcript_hash; ProofRuntimeReplayManifestIdentity_f_backend_route; ProofRuntimeReplayManifestIdentity_f_hardware_profile; ProofRuntimeReplayManifestIdentity_f_stage_manifest_digest>.
Definition ProofRuntimeReplayManifestIdentity := Build_ProofRuntimeReplayManifestIdentity_record.
Notation f_replay_id := ProofRuntimeReplayManifestIdentity_f_replay_id.
Notation t_ProofRuntimeReplayManifestIdentityf_replay_id := ProofRuntimeReplayManifestIdentity_f_replay_id.
Notation f_transcript_hash := ProofRuntimeReplayManifestIdentity_f_transcript_hash.
Notation t_ProofRuntimeReplayManifestIdentityf_transcript_hash := ProofRuntimeReplayManifestIdentity_f_transcript_hash.
Notation f_backend_route := ProofRuntimeReplayManifestIdentity_f_backend_route.
Notation t_ProofRuntimeReplayManifestIdentityf_backend_route := ProofRuntimeReplayManifestIdentity_f_backend_route.
Notation f_hardware_profile := ProofRuntimeReplayManifestIdentity_f_hardware_profile.
Notation t_ProofRuntimeReplayManifestIdentityf_hardware_profile := ProofRuntimeReplayManifestIdentity_f_hardware_profile.
Notation f_stage_manifest_digest := ProofRuntimeReplayManifestIdentity_f_stage_manifest_digest.
Notation t_ProofRuntimeReplayManifestIdentityf_stage_manifest_digest := ProofRuntimeReplayManifestIdentity_f_stage_manifest_digest.

Definition replay_manifest_identity_is_deterministic_spec (e_manifest : t_ProofRuntimeReplayManifestIdentity) : bool :=
  (true : bool).

Fixpoint runtime_digest_bytes_match_lists (expected : list t_u8) (found : list t_u8) : bool :=
  match expected, found with
  | [], [] =>
    (true : bool)
  | expected_head :: expected_tail, found_head :: found_tail =>
    andb
      (N.eqb (U8_f_v (u8_0 expected_head)) (U8_f_v (u8_0 found_head)))
      (runtime_digest_bytes_match_lists expected_tail found_tail)
  | _, _ =>
    (false : bool)
  end.

Definition runtime_digest_bytes_match_slices (expected : t_Slice t_u8) (found : t_Slice t_u8) : bool :=
  runtime_digest_bytes_match_lists (Slice_f_v expected) (Slice_f_v found).

Definition runtime_digest_bytes_match (expected : t_Vec ((t_u8)) ((t_Global))) (found : t_Vec ((t_u8)) ((t_Global))) : bool :=
  runtime_digest_bytes_match_lists expected found.

Definition digest_matches_recorded_hash_spec (recorded_hash : t_Option ((t_Vec ((t_u8)) ((t_Global))))) (expected_hash : t_Vec ((t_u8)) ((t_Global))) : bool :=
  match recorded_hash with
  | Option_Some (recorded) =>
    runtime_digest_bytes_match (recorded) (expected_hash)
  | Option_None =>
    (false : bool)
  end.

Definition hybrid_primary_leg_byte_components_match_spec (artifact_proof : t_Vec ((t_u8)) ((t_Global))) (artifact_verification_key : t_Vec ((t_u8)) ((t_Global))) (primary_leg_proof : t_Vec ((t_u8)) ((t_Global))) (primary_leg_verification_key : t_Vec ((t_u8)) ((t_Global))) : bool :=
  andb (runtime_digest_bytes_match (artifact_proof) (primary_leg_proof)) (runtime_digest_bytes_match (artifact_verification_key) (primary_leg_verification_key)).
