(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

Inductive t_SupportedCriticalEcdsaCurve : Type :=
| SupportedCriticalEcdsaCurve_Secp256k1
| SupportedCriticalEcdsaCurve_Secp256r1.



Inductive t_CriticalEcdsaAuxWitnessMode : Type :=
| CriticalEcdsaAuxWitnessMode_ArithmeticAuxWitness.


Record CriticalEcdsaRuntimeRelation_record : Type :=
  {
    CriticalEcdsaRuntimeRelation_f_valid_signature_forces_one : bool;
    CriticalEcdsaRuntimeRelation_f_invalid_signature_forces_zero : bool;
    CriticalEcdsaRuntimeRelation_f_malformed_abi_fails_closed : bool;
    CriticalEcdsaRuntimeRelation_f_low_s_is_required : bool;
  }.





#[export] Instance settable_CriticalEcdsaRuntimeRelation_record : Settable _ :=
  settable! (Build_CriticalEcdsaRuntimeRelation_record) <CriticalEcdsaRuntimeRelation_f_valid_signature_forces_one; CriticalEcdsaRuntimeRelation_f_invalid_signature_forces_zero; CriticalEcdsaRuntimeRelation_f_malformed_abi_fails_closed; CriticalEcdsaRuntimeRelation_f_low_s_is_required>.

Inductive t_SpecCriticalEcdsaOp : Type :=
| SpecCriticalEcdsaOp_Secp256k1
| SpecCriticalEcdsaOp_Secp256r1
| SpecCriticalEcdsaOp_Other.




Inductive t_SpecCriticalEcdsaFieldId : Type :=
| SpecCriticalEcdsaFieldId_Bn254
| SpecCriticalEcdsaFieldId_Other.



Record CriticalEcdsaByteAbiSemantics_record : Type :=
  {
    CriticalEcdsaByteAbiSemantics_f_supported_curve : t_SupportedCriticalEcdsaCurve;
    CriticalEcdsaByteAbiSemantics_f_supported_field : t_SpecCriticalEcdsaFieldId;
    CriticalEcdsaByteAbiSemantics_f_supported_inputs_len : t_usize;
    CriticalEcdsaByteAbiSemantics_f_supported_outputs_len : t_usize;
    CriticalEcdsaByteAbiSemantics_f_result_is_boolean : bool;
    CriticalEcdsaByteAbiSemantics_f_aux_witness_mode : t_CriticalEcdsaAuxWitnessMode;
    CriticalEcdsaByteAbiSemantics_f_runtime_relation : t_CriticalEcdsaRuntimeRelation;
  }.








#[export] Instance settable_CriticalEcdsaByteAbiSemantics_record : Settable _ :=
  settable! (Build_CriticalEcdsaByteAbiSemantics_record) <CriticalEcdsaByteAbiSemantics_f_supported_curve; CriticalEcdsaByteAbiSemantics_f_supported_field; CriticalEcdsaByteAbiSemantics_f_supported_inputs_len; CriticalEcdsaByteAbiSemantics_f_supported_outputs_len; CriticalEcdsaByteAbiSemantics_f_result_is_boolean; CriticalEcdsaByteAbiSemantics_f_aux_witness_mode; CriticalEcdsaByteAbiSemantics_f_runtime_relation>.

Definition critical_ecdsa_proof_surface (op : t_SpecCriticalEcdsaOp) (field : t_SpecCriticalEcdsaFieldId) (inputs_len : t_usize) (outputs_len : t_usize) : t_Option ((t_SupportedCriticalEcdsaCurve)) :=
  match field with
  | SpecCriticalEcdsaFieldId_Bn254 =>
    match match op with
    | SpecCriticalEcdsaOp_Secp256k1 =>
      match andb (f_eq (inputs_len) ((160 : t_usize))) (f_eq (outputs_len) ((1 : t_usize))) with
      | true =>
        Option_Some (Option_Some (SupportedCriticalEcdsaCurve_Secp256k1))
      | _ =>
        Option_None
      end
    | _ =>
      Option_None
    end with
    | Option_Some (x) =>
      x
    | Option_None =>
      match match op with
      | SpecCriticalEcdsaOp_Secp256r1 =>
        match andb (f_eq (inputs_len) ((160 : t_usize))) (f_eq (outputs_len) ((1 : t_usize))) with
        | true =>
          Option_Some (Option_Some (SupportedCriticalEcdsaCurve_Secp256r1))
        | _ =>
          Option_None
        end
      | _ =>
        Option_None
      end with
      | Option_Some (x) =>
        x
      | Option_None =>
        Option_None
      end
    end
  | SpecCriticalEcdsaFieldId_Other =>
    Option_None
  end.

Definition critical_ecdsa_aux_witness_mode (curve : t_SupportedCriticalEcdsaCurve) : t_CriticalEcdsaAuxWitnessMode :=
  let _ := curve in
  CriticalEcdsaAuxWitnessMode_ArithmeticAuxWitness.

Definition critical_ecdsa_runtime_relation (curve : t_SupportedCriticalEcdsaCurve) : t_CriticalEcdsaRuntimeRelation :=
  let _ := curve in
  CriticalEcdsaRuntimeRelation ((true : bool)) ((true : bool)) ((true : bool)) ((true : bool)).

Definition critical_ecdsa_byte_abi_semantics (op : t_SpecCriticalEcdsaOp) (field : t_SpecCriticalEcdsaFieldId) (inputs_len : t_usize) (outputs_len : t_usize) : t_Option ((t_CriticalEcdsaByteAbiSemantics)) :=
  match critical_ecdsa_proof_surface (op) (field) (inputs_len) (outputs_len) with
  | Option_Some (curve) =>
    Option_Some (CriticalEcdsaByteAbiSemantics (curve) (field) (inputs_len) (outputs_len) ((true : bool)) (critical_ecdsa_aux_witness_mode (curve)) (critical_ecdsa_runtime_relation (curve)))
  | Option_None =>
    Option_None
  end.

Definition ecdsa_curve_name (curve : t_SupportedCriticalEcdsaCurve) : string :=
  match curve with
  | SupportedCriticalEcdsaCurve_Secp256k1 =>
    ("secp256k1"%string : string)
  | SupportedCriticalEcdsaCurve_Secp256r1 =>
    ("secp256r1"%string : string)
  end.
