export const TOOL_DEFINITIONS = [
  { name: "post_tweet", description: "Post a tweet.", inputSchema: { type: "object", properties: { text: { type: "string" }, poll_options: { type: "array", items: { type: "string" } }, poll_duration: { type: "number" } }, required: ["text"] } },
  { name: "reply_to_tweet", description: "Reply to a tweet.", inputSchema: { type: "object", properties: { tweet_id: { type: "string" }, text: { type: "string" } }, required: ["tweet_id", "text"] } },
  { name: "quote_tweet", description: "Quote a tweet.", inputSchema: { type: "object", properties: { tweet_id: { type: "string" }, text: { type: "string" } }, required: ["tweet_id", "text"] } },
  { name: "delete_tweet", description: "Delete a tweet you own.", inputSchema: { type: "object", properties: { tweet_id: { type: "string" } }, required: ["tweet_id"] } },
  { name: "post_thread", description: "Post a multi-tweet thread.", inputSchema: { type: "object", properties: { tweets: { type: "array", items: { type: "string" } } }, required: ["tweets"] } },
  { name: "like_tweet", description: "Like a tweet.", inputSchema: { type: "object", properties: { tweet_id: { type: "string" } }, required: ["tweet_id"] } },
  { name: "unlike_tweet", description: "Unlike a tweet.", inputSchema: { type: "object", properties: { tweet_id: { type: "string" } }, required: ["tweet_id"] } },
  { name: "retweet", description: "Retweet a tweet.", inputSchema: { type: "object", properties: { tweet_id: { type: "string" } }, required: ["tweet_id"] } },
  { name: "unretweet", description: "Undo a retweet.", inputSchema: { type: "object", properties: { tweet_id: { type: "string" } }, required: ["tweet_id"] } },
  { name: "bookmark_tweet", description: "Bookmark a tweet.", inputSchema: { type: "object", properties: { tweet_id: { type: "string" } }, required: ["tweet_id"] } },
  { name: "search_tweets", description: "Search recent tweets.", inputSchema: { type: "object", properties: { query: { type: "string" }, max_results: { type: "number" }, sort_order: { type: "string" } }, required: ["query"] } },
  { name: "get_mentions", description: "Get mentions for the configured account.", inputSchema: { type: "object", properties: { max_results: { type: "number" } } } },
  { name: "search_hashtag", description: "Search a hashtag.", inputSchema: { type: "object", properties: { hashtag: { type: "string" }, max_results: { type: "number" } }, required: ["hashtag"] } },
  { name: "get_home_timeline", description: "Get the authenticated user's home timeline.", inputSchema: { type: "object", properties: { max_results: { type: "number" } } } },
  { name: "lookup_user", description: "Look up a user by username.", inputSchema: { type: "object", properties: { username: { type: "string" } }, required: ["username"] } },
  { name: "lookup_user_by_id", description: "Look up a user by numeric ID.", inputSchema: { type: "object", properties: { user_id: { type: "string" } }, required: ["user_id"] } },
  { name: "get_followers", description: "Get a user's followers.", inputSchema: { type: "object", properties: { username: { type: "string" }, max_results: { type: "number" } }, required: ["username"] } },
  { name: "get_following", description: "Get who a user follows.", inputSchema: { type: "object", properties: { username: { type: "string" }, max_results: { type: "number" } }, required: ["username"] } },
  { name: "follow_user", description: "Follow a user.", inputSchema: { type: "object", properties: { username: { type: "string" } }, required: ["username"] } },
  { name: "unfollow_user", description: "Unfollow a user.", inputSchema: { type: "object", properties: { username: { type: "string" } }, required: ["username"] } },
  { name: "block_user", description: "Block a user.", inputSchema: { type: "object", properties: { username: { type: "string" } }, required: ["username"] } },
  { name: "mute_user", description: "Mute a user.", inputSchema: { type: "object", properties: { username: { type: "string" } }, required: ["username"] } },
  { name: "upload_image", description: "Upload an image and return a media id.", inputSchema: { type: "object", properties: { file_path: { type: "string" }, alt_text: { type: "string" } }, required: ["file_path"] } },
  { name: "upload_video", description: "Upload a video and return a media id.", inputSchema: { type: "object", properties: { file_path: { type: "string" } }, required: ["file_path"] } },
  { name: "tweet_with_media", description: "Post a tweet with media.", inputSchema: { type: "object", properties: { text: { type: "string" }, media_ids: { type: "array", items: { type: "string" } } }, required: ["text", "media_ids"] } },
  { name: "create_list", description: "Create a Twitter list.", inputSchema: { type: "object", properties: { name: { type: "string" }, description: { type: "string" }, private: { type: "boolean" } }, required: ["name"] } },
  { name: "add_to_list", description: "Add a user to a list.", inputSchema: { type: "object", properties: { list_id: { type: "string" }, username: { type: "string" } }, required: ["list_id", "username"] } },
  { name: "remove_from_list", description: "Remove a user from a list.", inputSchema: { type: "object", properties: { list_id: { type: "string" }, username: { type: "string" } }, required: ["list_id", "username"] } },
  { name: "get_list_tweets", description: "Get recent tweets from a list.", inputSchema: { type: "object", properties: { list_id: { type: "string" }, max_results: { type: "number" } }, required: ["list_id"] } },
  { name: "get_tweet_metrics", description: "Get metrics for a tweet.", inputSchema: { type: "object", properties: { tweet_id: { type: "string" } }, required: ["tweet_id"] } },
  { name: "get_engagement_log", description: "Read the local engagement log.", inputSchema: { type: "object", properties: { limit: { type: "number" }, action_filter: { type: "string" } } } },
  { name: "get_rate_limits", description: "Inspect tracked rate limits.", inputSchema: { type: "object", properties: {} } },
  { name: "get_profile", description: "Get the authenticated profile.", inputSchema: { type: "object", properties: {} } },
  { name: "tweet_proof_result", description: "Format and post a proof announcement.", inputSchema: { type: "object", properties: { circuit_name: { type: "string" }, backend: { type: "string" }, proof_size: { type: "string" }, proving_time_ms: { type: "number" }, constraints: { type: "number" }, verified: { type: "boolean" } }, required: ["circuit_name", "backend", "proof_size", "proving_time_ms", "constraints", "verified"] } },
  { name: "tweet_attestation", description: "Format and post an attestation announcement.", inputSchema: { type: "object", properties: { tx_hash: { type: "string" }, explorer_url: { type: "string" }, theorem_count: { type: "number" }, conformance_count: { type: "number" } }, required: ["tx_hash", "explorer_url", "theorem_count", "conformance_count"] } },
  { name: "tweet_conformance", description: "Format and post a conformance announcement.", inputSchema: { type: "object", properties: { backend: { type: "string" }, tests_passed: { type: "number" }, tests_total: { type: "number" }, pass_rate: { type: "number" } }, required: ["backend", "tests_passed", "tests_total", "pass_rate"] } }
] as const;
