(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

Record HyperNovaExactSurfaceModel_record : Type :=
  {
    HyperNovaExactSurfaceModel_f_ccs_metadata_complete : bool;
    HyperNovaExactSurfaceModel_f_verifier_guards_match : bool;
    HyperNovaExactSurfaceModel_f_fold_profile_matches : bool;
    HyperNovaExactSurfaceModel_f_verifier_accepts : bool;
  }.





#[export] Instance settable_HyperNovaExactSurfaceModel_record : Settable _ :=
  settable! (Build_HyperNovaExactSurfaceModel_record) <HyperNovaExactSurfaceModel_f_ccs_metadata_complete; HyperNovaExactSurfaceModel_f_verifier_guards_match; HyperNovaExactSurfaceModel_f_fold_profile_matches; HyperNovaExactSurfaceModel_f_verifier_accepts>.













Definition t_HyperNovaExactSurfaceModel := HyperNovaExactSurfaceModel_record.
Notation f_ccs_metadata_complete := HyperNovaExactSurfaceModel_f_ccs_metadata_complete.
Notation f_verifier_guards_match := HyperNovaExactSurfaceModel_f_verifier_guards_match.
Notation f_fold_profile_matches := HyperNovaExactSurfaceModel_f_fold_profile_matches.
Notation f_verifier_accepts := HyperNovaExactSurfaceModel_f_verifier_accepts.
Definition f_not (value : bool) : bool := negb value.
Definition HyperNovaExactSurfaceModel := Build_HyperNovaExactSurfaceModel_record.

Definition hypernova_exact_verifier_guard (model : t_HyperNovaExactSurfaceModel) : bool :=
  andb (andb (f_ccs_metadata_complete model) (f_verifier_guards_match model)) (f_fold_profile_matches model).

Definition hypernova_exact_completeness_reduction (model : t_HyperNovaExactSurfaceModel) : bool :=
  orb (f_not (hypernova_exact_verifier_guard (model))) (f_verifier_accepts model).

Definition hypernova_exact_folding_soundness_reduction (model : t_HyperNovaExactSurfaceModel) : bool :=
  orb (f_not (f_verifier_accepts model)) (f_fold_profile_matches model).
