(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

Record Groth16ExactSurfaceModel_record : Type :=
  {
    Groth16ExactSurfaceModel_f_imported_crs_valid : bool;
    Groth16ExactSurfaceModel_f_public_input_arity_matches : bool;
    Groth16ExactSurfaceModel_f_encoding_matches : bool;
    Groth16ExactSurfaceModel_f_verifier_accepts : bool;
    Groth16ExactSurfaceModel_f_simulator_view_matches : bool;
  }.






#[export] Instance settable_Groth16ExactSurfaceModel_record : Settable _ :=
  settable! (Build_Groth16ExactSurfaceModel_record) <Groth16ExactSurfaceModel_f_imported_crs_valid; Groth16ExactSurfaceModel_f_public_input_arity_matches; Groth16ExactSurfaceModel_f_encoding_matches; Groth16ExactSurfaceModel_f_verifier_accepts; Groth16ExactSurfaceModel_f_simulator_view_matches>.













Definition t_Groth16ExactSurfaceModel := Groth16ExactSurfaceModel_record.
Notation f_imported_crs_valid := Groth16ExactSurfaceModel_f_imported_crs_valid.
Notation f_public_input_arity_matches := Groth16ExactSurfaceModel_f_public_input_arity_matches.
Notation f_encoding_matches := Groth16ExactSurfaceModel_f_encoding_matches.
Notation f_verifier_accepts := Groth16ExactSurfaceModel_f_verifier_accepts.
Notation f_simulator_view_matches := Groth16ExactSurfaceModel_f_simulator_view_matches.
Definition f_not (value : bool) : bool := negb value.
Definition Groth16ExactSurfaceModel := Build_Groth16ExactSurfaceModel_record.

Definition groth16_verifier_guard (model : t_Groth16ExactSurfaceModel) : bool :=
  andb (f_public_input_arity_matches model) (f_encoding_matches model).

Definition groth16_exact_completeness_reduction (model : t_Groth16ExactSurfaceModel) : bool :=
  orb (orb (f_not (f_imported_crs_valid model)) (f_not (groth16_verifier_guard (model)))) (f_verifier_accepts model).

Definition groth16_exact_knowledge_soundness_reduction (model : t_Groth16ExactSurfaceModel) : bool :=
  orb (orb (f_not (f_imported_crs_valid model)) (f_not (f_verifier_accepts model))) (f_public_input_arity_matches model).

Definition groth16_exact_zero_knowledge_reduction (model : t_Groth16ExactSurfaceModel) : bool :=
  orb (f_not (f_imported_crs_valid model)) (f_simulator_view_matches model).
