(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

Record FriExactSurfaceModel_record : Type :=
  {
    FriExactSurfaceModel_f_transcript_matches : bool;
    FriExactSurfaceModel_f_seed_replay_matches : bool;
    FriExactSurfaceModel_f_merkle_queries_match : bool;
    FriExactSurfaceModel_f_verifier_accepts : bool;
  }.





#[export] Instance settable_FriExactSurfaceModel_record : Settable _ :=
  settable! (Build_FriExactSurfaceModel_record) <FriExactSurfaceModel_f_transcript_matches; FriExactSurfaceModel_f_seed_replay_matches; FriExactSurfaceModel_f_merkle_queries_match; FriExactSurfaceModel_f_verifier_accepts>.













Definition t_FriExactSurfaceModel := FriExactSurfaceModel_record.
Notation f_transcript_matches := FriExactSurfaceModel_f_transcript_matches.
Notation f_seed_replay_matches := FriExactSurfaceModel_f_seed_replay_matches.
Notation f_merkle_queries_match := FriExactSurfaceModel_f_merkle_queries_match.
Notation f_verifier_accepts := FriExactSurfaceModel_f_verifier_accepts.
Definition f_not (value : bool) : bool := negb value.
Definition FriExactSurfaceModel := Build_FriExactSurfaceModel_record.

Definition fri_exact_verifier_guard (model : t_FriExactSurfaceModel) : bool :=
  andb (andb (f_transcript_matches model) (f_seed_replay_matches model)) (f_merkle_queries_match model).

Definition fri_exact_completeness_reduction (model : t_FriExactSurfaceModel) : bool :=
  orb (f_not (fri_exact_verifier_guard (model))) (f_verifier_accepts model).

Definition fri_exact_proximity_soundness_reduction (model : t_FriExactSurfaceModel) : bool :=
  orb (f_not (f_verifier_accepts model)) (f_merkle_queries_match model).
