// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title Pairing library for BN254 elliptic curve operations.
/// @dev Provides G1, G2 point types and precompiled pairing check.
library Pairing {
    struct G1Point {
        uint256 X;
        uint256 Y;
    }

    struct G2Point {
        uint256[2] X;
        uint256[2] Y;
    }

    /// @return the generator of G1.
    function P1() internal pure returns (G1Point memory) {
        return G1Point(1, 2);
    }

    /// @return the generator of G2.
    function P2() internal pure returns (G2Point memory) {
        return G2Point(
            [11559732032986387107991004021392285783925812861821192530917403151452391805634,
             10857046999023057135944570762232829481370756359578518086990519993285655852781],
            [4082367875863433681332203403145435568316851327593401208105741076214120093531,
             8495653923123431417604973247489272438418190587263600148770280649306958101930]
        );
    }

    /// @return r the negation of p, i.e. p.add(p.negate()) should be zero.
    function negate(G1Point memory p) internal pure returns (G1Point memory r) {
        // The prime q in the base field F_q for G1
        uint256 q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;
        if (p.X == 0 && p.Y == 0) return G1Point(0, 0);
        return G1Point(p.X, q - (p.Y % q));
    }

    /// @return r the sum of two points of G1.
    function addition(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {
        uint256[4] memory input;
        input[0] = p1.X;
        input[1] = p1.Y;
        input[2] = p2.X;
        input[3] = p2.Y;
        bool success;
        // solhint-disable-next-line no-inline-assembly
        assembly {
            success := staticcall(sub(gas(), 2000), 6, input, 0xc0, r, 0x60)
            switch success case 0 { invalid() }
        }
        require(success, "pairing-add-failed");
    }

    /// @return r the product of a point on G1 and a scalar, i.e. p == p.scalar_mul(1).
    function scalar_mul(G1Point memory p, uint256 s) internal view returns (G1Point memory r) {
        uint256[3] memory input;
        input[0] = p.X;
        input[1] = p.Y;
        input[2] = s;
        bool success;
        // solhint-disable-next-line no-inline-assembly
        assembly {
            success := staticcall(sub(gas(), 2000), 7, input, 0x60, r, 0x40)
            switch success case 0 { invalid() }
        }
        require(success, "pairing-mul-failed");
    }

    /// @return the result of computing the pairing check
    /// e(p1[0], p2[0]) *.... * e(p1[n], p2[n]) == 1
    /// For example pairing([P1(), P1().negate()], [P2(), P2()]) should return true.
    function pairing(G1Point[] memory p1, G2Point[] memory p2) internal view returns (bool) {
        require(p1.length == p2.length, "pairing-lengths-failed");
        uint256 elements = p1.length;
        uint256 inputSize = elements * 6;
        uint256[] memory input = new uint256[](inputSize);
        for (uint256 i = 0; i < elements; i++) {
            input[i * 6 + 0] = p1[i].X;
            input[i * 6 + 1] = p1[i].Y;
            input[i * 6 + 2] = p2[i].X[0];
            input[i * 6 + 3] = p2[i].X[1];
            input[i * 6 + 4] = p2[i].Y[0];
            input[i * 6 + 5] = p2[i].Y[1];
        }
        uint256[1] memory out;
        bool success;
        // solhint-disable-next-line no-inline-assembly
        assembly {
            success := staticcall(sub(gas(), 2000), 8, add(input, 0x20), mul(inputSize, 0x20), out, 0x20)
            switch success case 0 { invalid() }
        }
        require(success, "pairing-opcode-failed");
        return out[0] != 0;
    }

    /// Convenience method for a pairing check for four pairs.
    function pairingProd4(
        G1Point memory a1, G2Point memory a2,
        G1Point memory b1, G2Point memory b2,
        G1Point memory c1, G2Point memory c2,
        G1Point memory d1, G2Point memory d2
    ) internal view returns (bool) {
        G1Point[] memory p1 = new G1Point[](4);
        G2Point[] memory p2 = new G2Point[](4);
        p1[0] = a1; p2[0] = a2;
        p1[1] = b1; p2[1] = b2;
        p1[2] = c1; p2[2] = c2;
        p1[3] = d1; p2[3] = d2;
        return pairing(p1, p2);
    }
}

/// @title ZkfGroth16Verifier
/// @notice Generated Groth16 verifier for BN254 (alt_bn128).
/// @dev Generated by `zkf deploy --backend groth16`.
///      Verification checks: e(A, B) = e(alpha, beta) * e(IC, gamma) * e(C, delta)
contract ZkfGroth16Verifier {
    using Pairing for *;

    struct VerifyingKey {
        Pairing.G1Point alpha1;
        Pairing.G2Point beta2;
        Pairing.G2Point gamma2;
        Pairing.G2Point delta2;
        Pairing.G1Point[] IC;
    }

    struct Proof {
        Pairing.G1Point A;
        Pairing.G2Point B;
        Pairing.G1Point C;
    }

    function verifyingKey() internal pure returns (VerifyingKey memory vk) {
        vk.alpha1 = Pairing.G1Point(
            uint256(0x259aa294d0196e7eee29d5010f622bdc2eebab8a69725c941f7094f3d3a45bdf),
            uint256(0x15e8ca0e5a25dfbeea574cf0eb679378abf6b8024432bda7ce6bd16e01cb0a98)
        );

        vk.beta2 = Pairing.G2Point(
            [uint256(0x1b1423fd6a3fda91b74b4f00eb01a3fb0495053db5de545660e69ce8cbb3561f),
             uint256(0x1316a12c5fb5cd20f1a10a92fa5973f189d4c38c7779819bb095abb03be46140)],
            [uint256(0x0606329618472a7bdba10341da20f435bdb6fc283a028d96ddc4b767fc3142d7),
             uint256(0x07efb78d58cb8e9ddb8ae63ce9b0c048f250b9d623f78c8a7240e97ee08cc084)]
        );

        vk.gamma2 = Pairing.G2Point(
            [uint256(0x2d8144cfc36ce754e33a5814d738725662783accce9d876b3d0579cd8fa8fb63),
             uint256(0x17078c456bd776b15129886e7f86bda43c16bc052c320637ea4c41ffbb0b726e)],
            [uint256(0x281de61324a0305819d0f13a282dd0a4652609f00307099e54e2eeb489fb3142),
             uint256(0x2b7f77b661dc591739073041612f4d0453a40f1b74f6394a7916ad31b0cb816f)]
        );

        vk.delta2 = Pairing.G2Point(
            [uint256(0x1bf1a87ad7d338e90f197838f778c38175aa8c0f36dff60cb5bfe69036334a75),
             uint256(0x0d7d286f079cd7f72b1a1387af243aedd88944a077576ded221dac77d164ae9e)],
            [uint256(0x030de588a43123f948aa8109d271294ae5cbc5ce6704f3a63ec4d209af3fa4bf),
             uint256(0x24e8ce58fa7db49e56641e73e5facf08b603bc277d87b52c55de1894cbddd018)]
        );

        vk.IC = new Pairing.G1Point[](5);
        vk.IC[0] = Pairing.G1Point(uint256(0x05241e7e93ab69f53a23a65c5bc24420ecfac3510c5cd64b3efa9aa83ccb5c01), uint256(0x284bb3ce39bc0a0a74e0c21317f39be32ba6ed0bcfd68a66b7c325cb72051f32));
        vk.IC[1] = Pairing.G1Point(uint256(0x290d55a38e1ff3d43e88b0b86271ddb97ddfd301c5635d386b40cce8caa8bad4), uint256(0x24cfd5f768cf4e4f3cfe1be2213b80f219ccd2e8c2b64a8a2814a534fc6f16f1));
        vk.IC[2] = Pairing.G1Point(uint256(0x1ccd7809ea57a7ab024781e7228e9dc47f68ccbec4154174324dd319affac2e6), uint256(0x0bd61946fd9f6359dcca85bcd0a75f052d31c0521f391bcbc02a2e66a0c00112));
        vk.IC[3] = Pairing.G1Point(uint256(0x052961780a5abffdf4c648b07671829a123f0c2bf8e63351a060b01f342302fc), uint256(0x280a121df92efc88294ecc8d3e8ffbb269d4e20530ddaaca6d0d965d19cf857f));
        vk.IC[4] = Pairing.G1Point(uint256(0x1a80c1f8b0dc2055a2e6e475b2633d9c583a2ce24ada28400b38ffd504965fa1), uint256(0x272a6faf59262ac7e54192a40726689f4882c6245509218b352a0c5ddefa46b3));
    }

    function verify(uint[] memory input, Proof memory proof) internal view returns (bool) {
        uint256 snark_scalar_field = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
        VerifyingKey memory vk = verifyingKey();
        require(input.length + 1 == vk.IC.length, "verifier-bad-input");
        // Compute the linear combination vk_x
        Pairing.G1Point memory vk_x = Pairing.G1Point(0, 0);
        for (uint i = 0; i < input.length; i++) {
            require(input[i] < snark_scalar_field, "verifier-gte-snark-scalar-field");
            vk_x = Pairing.addition(vk_x, Pairing.scalar_mul(vk.IC[i + 1], input[i]));
        }
        vk_x = Pairing.addition(vk_x, vk.IC[0]);
        // Pairing check: e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1
        if (!Pairing.pairingProd4(
            Pairing.negate(proof.A), proof.B,
            vk.alpha1, vk.beta2,
            vk_x, vk.gamma2,
            proof.C, vk.delta2
        )) return false;
        return true;
    }

    /// @notice Verify a Groth16 proof.
    /// @param a The A point of the proof (2 uint256 values).
    /// @param b The B point of the proof (2x2 uint256 values).
    /// @param c The C point of the proof (2 uint256 values).
    /// @param input The public inputs to the circuit.
    /// @return r True if the proof is valid.
    function verifyProof(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory input
    ) public view returns (bool r) {
        Proof memory proof;
        proof.A = Pairing.G1Point(a[0], a[1]);
        proof.B = Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]);
        proof.C = Pairing.G1Point(c[0], c[1]);
        return verify(input, proof);
    }
}
