// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;
import "../src/PoweredDescentVerifier.sol";

/// @title PoweredDescentVerifierTest
/// @notice Auto-generated Foundry test for Groth16 verifier behavioral correctness.
/// @dev Generated by ZKF. The suite locks valid verification plus fail-closed
///      rejection for tampering, wrong public inputs, wrong arity, and field overflow.
contract PoweredDescentVerifierTest {
    uint256 internal constant SNARK_SCALAR_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    PoweredDescentVerifier verifier;

    function assertTrue(bool condition, string memory message) internal pure {
        require(condition, message);
    }

    function assertFalse(bool condition, string memory message) internal pure {
        require(!condition, message);
    }

    function setUp() public {
        verifier = new PoweredDescentVerifier();
    }

    function proofFixture()
        internal
        pure
        returns (uint[2] memory a, uint[2][2] memory b, uint[2] memory c)
    {
        a = [
            uint256(0x0e68002b6ae45189e9d2397668daf252f7aa8c201f111e45c46b8d57af8a12dc),
            uint256(0x035246f32da01378ad1d5ef549a33f55075657027cf6c8dc6c3af5aafa0e11a8)
        ];
        b = [
            [uint256(0x16856174d4f91b704dba6f6d3888cb03c2ded79905bd44a1fe6943515922630d), uint256(0x2e10e6cb8f9866c28f18ba83e87af0512a84a53e29f5cac4cd85b7d241459297)],
            [uint256(0x268683bcca151504d5d4f83a5e884d4637b836fa2a9cb5a79acf4dae53775fa6), uint256(0x1b928e0a07da9b9980d7a2f768774feb90f488cc8b807482d184fb1aee7c8990)]
        ];
        c = [
            uint256(0x2103d519daa63cd901f274b04fb59f535ef5906504d7ef2d9faf8a2e70e26a25),
            uint256(0x0a411a7260770ea2ebbca52943eba442afeac2358fe3ab59091472038100ec90)
        ];
    }

    function validInputFixture() internal pure returns (uint[] memory) {
        uint[] memory input = new uint[](13);
        input[0] = uint256(0x000000000000000000000000000000000000000000003f870857a3e0e3800000);
        input[1] = uint256(0x00000000000000000000000000000000000000000000b2ef8ab2961fd6200000);
        input[2] = uint256(0x0000000000000000000000000000000000000000000000006f05b59d3b200000);
        input[3] = uint256(0x0000000000000000000000000000000000000000000000008ac7230489e80000);
        input[4] = uint256(0x000000000000000000000000000000000000000000000000d02ab486cedc0000);
        input[5] = uint256(0x0000000000000000000000000000000000000000000000000000000000000000);
        input[6] = uint256(0x0000000000000000000000000000000000000000000000000000000000000000);
        input[7] = uint256(0x000000000000000000000000000000000000000000000000881838379695a000);
        input[8] = uint256(0x000000000000000000000000000000000000000000000000172e6443a5bc0285);
        input[9] = uint256(0x1b6ddc616e36fbd07183c4f7556b24ca1438e47fa538a4bd44d477b3b4352894);
        input[10] = uint256(0x012ee5fd71f47fbbf12310b2a4c4d05521e80a5d4dc01a67358bd8e12ee37613);
        input[11] = uint256(0x0000000000000000000000000000000000000000000000000000000000000001);
        input[12] = uint256(0x00000000000000000000000000000000000000000000046005f3155d383e8c00);
        return input;
    }

    function wrongInputFixture(uint256 delta) internal pure returns (uint[] memory) {
        uint[] memory wrongInput = new uint[](13);
        wrongInput[0] = (uint256(0x000000000000000000000000000000000000000000003f870857a3e0e3800000) + delta) % SNARK_SCALAR_FIELD;
        wrongInput[1] = uint256(0x00000000000000000000000000000000000000000000b2ef8ab2961fd6200000);
        wrongInput[2] = uint256(0x0000000000000000000000000000000000000000000000006f05b59d3b200000);
        wrongInput[3] = uint256(0x0000000000000000000000000000000000000000000000008ac7230489e80000);
        wrongInput[4] = uint256(0x000000000000000000000000000000000000000000000000d02ab486cedc0000);
        wrongInput[5] = uint256(0x0000000000000000000000000000000000000000000000000000000000000000);
        wrongInput[6] = uint256(0x0000000000000000000000000000000000000000000000000000000000000000);
        wrongInput[7] = uint256(0x000000000000000000000000000000000000000000000000881838379695a000);
        wrongInput[8] = uint256(0x000000000000000000000000000000000000000000000000172e6443a5bc0285);
        wrongInput[9] = uint256(0x1b6ddc616e36fbd07183c4f7556b24ca1438e47fa538a4bd44d477b3b4352894);
        wrongInput[10] = uint256(0x012ee5fd71f47fbbf12310b2a4c4d05521e80a5d4dc01a67358bd8e12ee37613);
        wrongInput[11] = uint256(0x0000000000000000000000000000000000000000000000000000000000000001);
        wrongInput[12] = uint256(0x00000000000000000000000000000000000000000000046005f3155d383e8c00);
        return wrongInput;
    }

    function wrongArityInputFixture() internal pure returns (uint[] memory) {
        uint[] memory wrongArity = new uint[](14);
        wrongArity[0] = uint256(0x000000000000000000000000000000000000000000003f870857a3e0e3800000);
        wrongArity[1] = uint256(0x00000000000000000000000000000000000000000000b2ef8ab2961fd6200000);
        wrongArity[2] = uint256(0x0000000000000000000000000000000000000000000000006f05b59d3b200000);
        wrongArity[3] = uint256(0x0000000000000000000000000000000000000000000000008ac7230489e80000);
        wrongArity[4] = uint256(0x000000000000000000000000000000000000000000000000d02ab486cedc0000);
        wrongArity[5] = uint256(0x0000000000000000000000000000000000000000000000000000000000000000);
        wrongArity[6] = uint256(0x0000000000000000000000000000000000000000000000000000000000000000);
        wrongArity[7] = uint256(0x000000000000000000000000000000000000000000000000881838379695a000);
        wrongArity[8] = uint256(0x000000000000000000000000000000000000000000000000172e6443a5bc0285);
        wrongArity[9] = uint256(0x1b6ddc616e36fbd07183c4f7556b24ca1438e47fa538a4bd44d477b3b4352894);
        wrongArity[10] = uint256(0x012ee5fd71f47fbbf12310b2a4c4d05521e80a5d4dc01a67358bd8e12ee37613);
        wrongArity[11] = uint256(0x0000000000000000000000000000000000000000000000000000000000000001);
        wrongArity[12] = uint256(0x00000000000000000000000000000000000000000000046005f3155d383e8c00);
        wrongArity[13] = 1;
        return wrongArity;
    }

    function overflowInputFixture() internal pure returns (uint[] memory) {
        uint[] memory overflowInput = new uint[](13);
        overflowInput[0] = SNARK_SCALAR_FIELD;
        overflowInput[1] = uint256(0x00000000000000000000000000000000000000000000b2ef8ab2961fd6200000);
        overflowInput[2] = uint256(0x0000000000000000000000000000000000000000000000006f05b59d3b200000);
        overflowInput[3] = uint256(0x0000000000000000000000000000000000000000000000008ac7230489e80000);
        overflowInput[4] = uint256(0x000000000000000000000000000000000000000000000000d02ab486cedc0000);
        overflowInput[5] = uint256(0x0000000000000000000000000000000000000000000000000000000000000000);
        overflowInput[6] = uint256(0x0000000000000000000000000000000000000000000000000000000000000000);
        overflowInput[7] = uint256(0x000000000000000000000000000000000000000000000000881838379695a000);
        overflowInput[8] = uint256(0x000000000000000000000000000000000000000000000000172e6443a5bc0285);
        overflowInput[9] = uint256(0x1b6ddc616e36fbd07183c4f7556b24ca1438e47fa538a4bd44d477b3b4352894);
        overflowInput[10] = uint256(0x012ee5fd71f47fbbf12310b2a4c4d05521e80a5d4dc01a67358bd8e12ee37613);
        overflowInput[11] = uint256(0x0000000000000000000000000000000000000000000000000000000000000001);
        overflowInput[12] = uint256(0x00000000000000000000000000000000000000000000046005f3155d383e8c00);
        return overflowInput;
    }

    function assertRejected(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory input,
        string memory message
    ) internal view {
        try verifier.verifyProof(a, b, c, input) returns (bool result) {
            assertFalse(result, message);
        } catch {
            assertTrue(true, message);
        }
    }

    /// @notice Valid proof must pass.
    function test_validProof() public view {
        (uint[2] memory a, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        uint[] memory input = validInputFixture();

        bool result = verifier.verifyProof(a, b, c, input);
        assertTrue(result, "valid proof must pass");
    }

    /// @notice Tampered proof (A.x mutated) must not verify.
    /// An off-curve point causes the EVM pairing precompile to revert,
    /// while a still-on-curve but wrong point returns false. Both are correct rejections.
    function test_tamperedProofFails() public view {
        (, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        uint[2] memory a = [
            uint256(0x0e68002b6ae45189e9d2397668daf252f7aa8c201f111e45c46b8d57af8a12d0),
            uint256(0x035246f32da01378ad1d5ef549a33f55075657027cf6c8dc6c3af5aafa0e11a8)
        ];
        uint[] memory input = validInputFixture();

        assertRejected(a, b, c, input, "tampered proof must fail closed");
    }

    /// @notice Wrong public input must fail.
    function test_wrongInputFails() public view {
        (uint[2] memory a, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        uint[] memory wrongInput = wrongInputFixture(1);

        assertRejected(a, b, c, wrongInput, "wrong input must fail closed");
    }

    /// @notice Wrong public-input arity must fail closed.
    function test_wrongPublicInputArityFails() public view {
        (uint[2] memory a, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        uint[] memory wrongArity = wrongArityInputFixture();

        assertRejected(a, b, c, wrongArity, "wrong public-input arity must fail closed");
    }

    /// @notice Inputs equal to the scalar field modulus must fail closed.
    function test_scalarFieldOverflowInputFails() public view {
        (uint[2] memory a, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        uint[] memory overflowInput = overflowInputFixture();

        assertRejected(a, b, c, overflowInput, "scalar-field overflow input must fail closed");
    }

    /// @notice Fuzzing a nonzero public-input delta must always fail closed.
    function testFuzz_nonZeroPublicInputDeltaFails(uint256 deltaRaw) public view {
        uint256 delta = deltaRaw % SNARK_SCALAR_FIELD;
        if (delta == 0) {
            delta = 1;
        }
        (uint[2] memory a, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        uint[] memory wrongInput = wrongInputFixture(delta);

        assertRejected(a, b, c, wrongInput, "fuzzed nonzero public-input delta must fail closed");
    }

    /// @notice Fuzzing proof-coordinate tampering must always fail closed.
    function testFuzz_proofCoordinateTamperingFails(uint256 deltaRaw) public view {
        uint256 delta = (deltaRaw % 17) + 1;
        (uint[2] memory a, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        if (a[0] > delta) {
            a[0] = a[0] - delta;
        } else {
            a[0] = a[0] + delta;
        }
        uint[] memory input = validInputFixture();

        assertRejected(a, b, c, input, "fuzzed proof-coordinate tampering must fail closed");
    }
}
