(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.
From ZkfCoreExtraction Require Import Zkf_core_Proof_kernel_spec_Bundle.

Notation "'t_SpecFieldValue'" := (t_SpecFieldValue).

Notation "'spec_field_value_raw_bigint'" := (spec_field_value_raw_bigint).

Notation "'spec_field_value_from_bigint_with_field'" := (spec_field_value_from_bigint_with_field).

Notation "'spec_field_value_zero'" := (spec_field_value_zero).

Notation "'spec_field_value_is_zero_raw'" := (spec_field_value_is_zero_raw).

Notation "'spec_field_value_is_one_raw'" := (spec_field_value_is_one_raw).

Notation "'spec_normalize_mod_bigint'" := (spec_normalize_mod_bigint).

Notation "'spec_mod_inverse_bigint'" := (spec_mod_inverse_bigint).

Notation "'t_SpecKernelExpr'" := (t_SpecKernelExpr).

Notation "'SpecKernelExpr_Const'" := (SpecKernelExpr_Const).

Notation "'SpecKernelExpr_Signal'" := (SpecKernelExpr_Signal).

Notation "'SpecKernelExpr_Add'" := (SpecKernelExpr_Add).

Notation "'SpecKernelExpr_Sub'" := (SpecKernelExpr_Sub).

Notation "'SpecKernelExpr_Mul'" := (SpecKernelExpr_Mul).

Notation "'SpecKernelExpr_Div'" := (SpecKernelExpr_Div).

Notation "'t_SpecKernelConstraint'" := (t_SpecKernelConstraint).

Notation "'SpecKernelConstraint_Equal'" := (SpecKernelConstraint_Equal).

Notation "'SpecKernelConstraint_Boolean'" := (SpecKernelConstraint_Boolean).

Notation "'SpecKernelConstraint_Range'" := (SpecKernelConstraint_Range).

Notation "'SpecKernelConstraint_Lookup'" := (SpecKernelConstraint_Lookup).

Notation "'t_SpecKernelLookupTable'" := (t_SpecKernelLookupTable).

Notation "'t_SpecKernelProgram'" := (t_SpecKernelProgram).

Notation "'t_SpecKernelWitness'" := (t_SpecKernelWitness).

Notation "'t_SpecLookupFailureKind'" := (t_SpecLookupFailureKind).

Notation "'SpecLookupFailureKind_InputArityMismatch'" := (SpecLookupFailureKind_InputArityMismatch).

Notation "'SpecLookupFailureKind_NoMatchingRow'" := (SpecLookupFailureKind_NoMatchingRow).

Notation "'t_SpecKernelCheckError'" := (t_SpecKernelCheckError).

Notation "'SpecKernelCheckError_MissingSignal'" := (SpecKernelCheckError_MissingSignal).

Notation "'SpecKernelCheckError_DivisionByZero'" := (SpecKernelCheckError_DivisionByZero).

Notation "'SpecKernelCheckError_UnknownLookupTable'" := (SpecKernelCheckError_UnknownLookupTable).

Notation "'SpecKernelCheckError_EqualViolation'" := (SpecKernelCheckError_EqualViolation).

Notation "'SpecKernelCheckError_BooleanViolation'" := (SpecKernelCheckError_BooleanViolation).

Notation "'SpecKernelCheckError_RangeViolation'" := (SpecKernelCheckError_RangeViolation).

Notation "'SpecKernelCheckError_LookupViolation'" := (SpecKernelCheckError_LookupViolation).

Notation "'kernel_signal_value'" := (kernel_signal_value).

Notation "'render_lookup_outputs_from'" := (render_lookup_outputs_from).

Notation "'render_lookup_outputs'" := (render_lookup_outputs).

Notation "'collect_evaluated_inputs_from'" := (collect_evaluated_inputs_from).

Notation "'collect_evaluated_inputs'" := (collect_evaluated_inputs).

Notation "'row_matches_inputs_from'" := (row_matches_inputs_from).

Notation "'row_matches_inputs'" := (row_matches_inputs).

Notation "'skip_row_prefix'" := (skip_row_prefix).

Notation "'row_matches_outputs_from'" := (row_matches_outputs_from).

Notation "'row_matches_outputs'" := (row_matches_outputs).

Notation "'lookup_has_matching_row_from'" := (lookup_has_matching_row_from).

Notation "'eval_expr'" := (eval_expr).

Notation "'check_constraints_from'" := (check_constraints_from).

Notation "'check_program'" := (check_program).
