(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.
From ZkfCoreExtraction Require Import Zkf_core_Field.
From ZkfCoreExtraction Require Import Zkf_core_Proof_kernel_spec_Bundle.
Require Import KernelCompat.
Definition t_BigInt := Z.
Definition t_BTreeMap (A B : Type) (_ : globality) := list (A * B).

Definition impl_18__new '(_ : unit) : t_BTreeMap t_usize t_BigInt t_Global := [].

Fixpoint impl_20__remove
  (target : t_BTreeMap t_usize t_BigInt t_Global)
  (key : t_usize)
  : t_BTreeMap t_usize t_BigInt t_Global * t_Option t_BigInt :=
  match target with
  | [] =>
      ([], Option_None)
  | (current_key, current_value) :: remaining =>
      if f_eq current_key key then
        (remaining, Option_Some current_value)
      else
        let '(updated, removed) := impl_20__remove remaining key in
        ((current_key, current_value) :: updated, removed)
  end.

Definition impl_20__insert
  (target : t_BTreeMap t_usize t_BigInt t_Global)
  (key : t_usize)
  (value : t_BigInt)
  : t_BTreeMap t_usize t_BigInt t_Global * t_Option t_BigInt :=
  ((key, value) :: target, Option_None).

Definition impl_FieldId__modulus (field : t_FieldId) : t_BigInt :=
  spec_field_modulus field.

Definition normalize_mod (value modulus : t_BigInt) : t_BigInt :=
  spec_normalize_z value modulus.

Definition f_one '(_ : unit) : t_BigInt := 1%Z.
Definition f_neg (value : t_BigInt) : t_BigInt := Z.opp value.
Definition f_is_zero (value : t_BigInt) : bool := Z.eqb value 0%Z.
Definition f_shl (value : t_BigInt) (amount : t_usize) : t_BigInt :=
  Z.shiftl value (Z.of_N (U64_f_v (usize_0 amount))).

Inductive t_SpecCcsVisibility : Type :=
| SpecCcsVisibility_Public
| SpecCcsVisibility_NonPublic.



Record SpecCcsSignal_record : Type :=
  {
    SpecCcsSignal_f_visibility : t_SpecCcsVisibility;
  }.


#[export] Instance settable_SpecCcsSignal_record : Settable _ :=
  settable! (Build_SpecCcsSignal_record) <SpecCcsSignal_f_visibility>.
Notation "'t_SpecCcsSignal'" := (SpecCcsSignal_record).

Inductive t_SpecCcsBlackBoxKind : Type :=
| SpecCcsBlackBoxKind_RecursiveAggregationMarker
| SpecCcsBlackBoxKind_Other.



Record SpecCcsMatrixEntry_record : Type :=
  {
    SpecCcsMatrixEntry_f_row : t_usize;
    SpecCcsMatrixEntry_f_col : t_usize;
    SpecCcsMatrixEntry_f_value : t_SpecFieldValue;
  }.




#[export] Instance settable_SpecCcsMatrixEntry_record : Settable _ :=
  settable! (Build_SpecCcsMatrixEntry_record) <SpecCcsMatrixEntry_f_row; SpecCcsMatrixEntry_f_col; SpecCcsMatrixEntry_f_value>.
Definition SpecCcsMatrixEntry := Build_SpecCcsMatrixEntry_record.
Notation "'t_SpecCcsMatrixEntry'" := (SpecCcsMatrixEntry_record).

Record SpecCcsMatrix_record : Type :=
  {
    SpecCcsMatrix_f_rows : t_usize;
    SpecCcsMatrix_f_cols : t_usize;
    SpecCcsMatrix_f_entries : t_Vec ((t_SpecCcsMatrixEntry)) ((t_Global));
  }.




#[export] Instance settable_SpecCcsMatrix_record : Settable _ :=
  settable! (Build_SpecCcsMatrix_record) <SpecCcsMatrix_f_rows; SpecCcsMatrix_f_cols; SpecCcsMatrix_f_entries>.
Definition SpecCcsMatrix := Build_SpecCcsMatrix_record.
Notation "'t_SpecCcsMatrix'" := (SpecCcsMatrix_record).

Record SpecCcsMultiset_record : Type :=
  {
    SpecCcsMultiset_f_matrix_indices : t_Vec ((t_usize)) ((t_Global));
    SpecCcsMultiset_f_coefficient : t_SpecFieldValue;
  }.



#[export] Instance settable_SpecCcsMultiset_record : Settable _ :=
  settable! (Build_SpecCcsMultiset_record) <SpecCcsMultiset_f_matrix_indices; SpecCcsMultiset_f_coefficient>.
Definition SpecCcsMultiset := Build_SpecCcsMultiset_record.
Notation "'t_SpecCcsMultiset'" := (SpecCcsMultiset_record).

Record SpecCcsProgram_record : Type :=
  {
    SpecCcsProgram_f_field : t_FieldId;
    SpecCcsProgram_f_num_constraints : t_usize;
    SpecCcsProgram_f_num_variables : t_usize;
    SpecCcsProgram_f_num_public : t_usize;
    SpecCcsProgram_f_matrices : t_Vec ((t_SpecCcsMatrix)) ((t_Global));
    SpecCcsProgram_f_multisets : t_Vec ((t_SpecCcsMultiset)) ((t_Global));
  }.







#[export] Instance settable_SpecCcsProgram_record : Settable _ :=
  settable! (Build_SpecCcsProgram_record) <SpecCcsProgram_f_field; SpecCcsProgram_f_num_constraints; SpecCcsProgram_f_num_variables; SpecCcsProgram_f_num_public; SpecCcsProgram_f_matrices; SpecCcsProgram_f_multisets>.
Definition SpecCcsProgram := Build_SpecCcsProgram_record.
Notation "'t_SpecCcsProgram'" := (SpecCcsProgram_record).

Inductive t_SpecCcsSynthesisErrorKind : Type :=
| SpecCcsSynthesisErrorKind_InvalidSignalIndex
| SpecCcsSynthesisErrorKind_LookupRequiresLowering
| SpecCcsSynthesisErrorKind_BlackBoxRequiresLowering.




Record SpecCcsSynthesisError_record : Type :=
  {
    SpecCcsSynthesisError_f_constraint_index : t_usize;
    SpecCcsSynthesisError_f_kind : t_SpecCcsSynthesisErrorKind;
  }.



#[export] Instance settable_SpecCcsSynthesisError_record : Settable _ :=
  settable! (Build_SpecCcsSynthesisError_record) <SpecCcsSynthesisError_f_constraint_index; SpecCcsSynthesisError_f_kind>.
Definition SpecCcsSynthesisError := Build_SpecCcsSynthesisError_record.
Notation "'t_SpecCcsSynthesisError'" := (SpecCcsSynthesisError_record).


Definition spec_value_to_bigint (value : t_SpecFieldValue) (field : t_FieldId) : t_BigInt :=
  spec_normalize_z (spec_field_value_to_z value) (spec_field_modulus field).

Definition bigint_to_spec_value (value : t_BigInt) (field : t_FieldId) : t_SpecFieldValue :=
  spec_field_value_of_z (spec_normalize_z value (spec_field_modulus field)).

Record SpecCcsBuilder_record : Type :=
  {
    SpecCcsBuilder_f_field : t_FieldId;
    SpecCcsBuilder_f_signal_columns : t_Vec ((t_usize)) ((t_Global));
    SpecCcsBuilder_f_next_col : t_usize;
    SpecCcsBuilder_f_num_public : t_usize;
    SpecCcsBuilder_f_row : t_usize;
    SpecCcsBuilder_f_a_entries : t_Vec ((t_SpecCcsMatrixEntry)) ((t_Global));
    SpecCcsBuilder_f_b_entries : t_Vec ((t_SpecCcsMatrixEntry)) ((t_Global));
    SpecCcsBuilder_f_c_entries : t_Vec ((t_SpecCcsMatrixEntry)) ((t_Global));
  }.









#[export] Instance settable_SpecCcsBuilder_record : Settable _ :=
  settable! (Build_SpecCcsBuilder_record) <SpecCcsBuilder_f_field; SpecCcsBuilder_f_signal_columns; SpecCcsBuilder_f_next_col; SpecCcsBuilder_f_num_public; SpecCcsBuilder_f_row; SpecCcsBuilder_f_a_entries; SpecCcsBuilder_f_b_entries; SpecCcsBuilder_f_c_entries>.
Definition SpecCcsBuilder := Build_SpecCcsBuilder_record.
Notation "'t_SpecCcsBuilder'" := (SpecCcsBuilder_record).


Definition builder_finish (builder : t_SpecCcsBuilder) (field : t_FieldId) : t_SpecCcsProgram :=
  let num_constraints := SpecCcsBuilder_f_row builder in
  let rows := num_constraints in
  let cols := SpecCcsBuilder_f_next_col builder in
  SpecCcsProgram
    field
    num_constraints
    cols
    (SpecCcsBuilder_f_num_public builder)
    [ SpecCcsMatrix rows cols (SpecCcsBuilder_f_a_entries builder)
    ; SpecCcsMatrix rows cols (SpecCcsBuilder_f_b_entries builder)
    ; SpecCcsMatrix rows cols (SpecCcsBuilder_f_c_entries builder)
    ]
    [ SpecCcsMultiset [(0 : t_usize); (1 : t_usize)] (bigint_to_spec_value 1%Z field)
    ; SpecCcsMultiset [(2 : t_usize)] (bigint_to_spec_value (-1)%Z field)
    ].

Definition builder_allocate_aux (builder : t_SpecCcsBuilder) : (t_SpecCcsBuilder*t_usize) :=
  let col := SpecCcsBuilder_f_next_col builder in
  let builder :=
    SpecCcsBuilder
      (SpecCcsBuilder_f_field builder)
      (SpecCcsBuilder_f_signal_columns builder)
      (f_add (SpecCcsBuilder_f_next_col builder) ((1 : t_usize)))
      (SpecCcsBuilder_f_num_public builder)
      (SpecCcsBuilder_f_row builder)
      (SpecCcsBuilder_f_a_entries builder)
      (SpecCcsBuilder_f_b_entries builder)
      (SpecCcsBuilder_f_c_entries builder) in
  (builder, col).

Definition lc_add_term (target : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) (col : t_usize) (coeff : t_BigInt) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  if Z.eqb coeff 0%Z then
    target
  else
    let '(target, existing) := impl_20__remove target col in
    let updated :=
      match existing with
      | Option_Some value => Z.add value coeff
      | Option_None => coeff
      end in
    if Z.eqb updated 0%Z then
      target
    else
      (col, updated) :: target.

Definition lc_const (value : t_BigInt) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  lc_add_term [] (0 : t_usize) value.

Definition lc_var (col : t_usize) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  lc_add_term [] col 1%Z.

Definition lc_one '(_ : unit) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  lc_const 1%Z.

Definition lc_one_minus_var (col : t_usize) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  lc_add_term (lc_one tt) col (-1)%Z.

Definition lc_add_assign (target : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) (other : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  List.fold_left (fun acc entry => lc_add_term acc (fst entry) (snd entry)) other target.

Definition lc_sub_assign (target : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) (other : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  List.fold_left (fun acc entry => lc_add_term acc (fst entry) (Z.opp (snd entry))) other target.

Definition push_lc_entries (field : t_FieldId) (entries : t_Vec ((t_SpecCcsMatrixEntry)) ((t_Global))) (row : t_usize) (lc : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global))) : t_Vec ((t_SpecCcsMatrixEntry)) ((t_Global)) :=
  List.fold_left
    (fun acc entry =>
      let '(col, coeff) := entry in
      let normalized := normalize_mod coeff (impl_FieldId__modulus field) in
      if Z.eqb normalized 0%Z then
        acc
      else
        acc ++ [SpecCcsMatrixEntry row col (bigint_to_spec_value normalized field)])
    lc
    entries.

Inductive t_SpecCcsExpr : Type :=
| SpecCcsExpr_Const : t_SpecFieldValue -> _
| SpecCcsExpr_Signal : t_usize -> _
| SpecCcsExpr_Add : t_Vec ((t_SpecCcsExpr)) ((t_Global)) -> _
| SpecCcsExpr_Sub : t_SpecCcsExpr -> t_SpecCcsExpr -> _
| SpecCcsExpr_Mul : t_SpecCcsExpr -> t_SpecCcsExpr -> _
| SpecCcsExpr_Div : t_SpecCcsExpr -> t_SpecCcsExpr -> _.







Record SpecCcsConstraint_Equal_record : Type :=
  {
    SpecCcsConstraint_Equal_f_lhs : t_SpecCcsExpr;
    SpecCcsConstraint_Equal_f_rhs : t_SpecCcsExpr;
  }.



#[export] Instance settable_SpecCcsConstraint_Equal_record : Settable _ :=
  settable! (Build_SpecCcsConstraint_Equal_record) <SpecCcsConstraint_Equal_f_lhs; SpecCcsConstraint_Equal_f_rhs>.
Record SpecCcsConstraint_Boolean_record : Type :=
  {
    SpecCcsConstraint_Boolean_f_signal_index : t_usize;
  }.


#[export] Instance settable_SpecCcsConstraint_Boolean_record : Settable _ :=
  settable! (Build_SpecCcsConstraint_Boolean_record) <SpecCcsConstraint_Boolean_f_signal_index>.
Record SpecCcsConstraint_Range_record : Type :=
  {
    SpecCcsConstraint_Range_f_signal_index : t_usize;
    SpecCcsConstraint_Range_f_bits : t_u32;
  }.



#[export] Instance settable_SpecCcsConstraint_Range_record : Settable _ :=
  settable! (Build_SpecCcsConstraint_Range_record) <SpecCcsConstraint_Range_f_signal_index; SpecCcsConstraint_Range_f_bits>.
Record SpecCcsConstraint_BlackBox_record : Type :=
  {
    SpecCcsConstraint_BlackBox_f_kind : t_SpecCcsBlackBoxKind;
  }.


#[export] Instance settable_SpecCcsConstraint_BlackBox_record : Settable _ :=
  settable! (Build_SpecCcsConstraint_BlackBox_record) <SpecCcsConstraint_BlackBox_f_kind>.
Inductive t_SpecCcsConstraint : Type :=
| SpecCcsConstraint_Equal : SpecCcsConstraint_Equal_record  -> _
| SpecCcsConstraint_Boolean : SpecCcsConstraint_Boolean_record  -> _
| SpecCcsConstraint_Range : SpecCcsConstraint_Range_record  -> _
| SpecCcsConstraint_Lookup
| SpecCcsConstraint_BlackBox : SpecCcsConstraint_BlackBox_record  -> _.






Record SpecCcsConstraintProgram_record : Type :=
  {
    SpecCcsConstraintProgram_f_field : t_FieldId;
    SpecCcsConstraintProgram_f_signals : t_Vec ((t_SpecCcsSignal)) ((t_Global));
    SpecCcsConstraintProgram_f_constraints : t_Vec ((t_SpecCcsConstraint)) ((t_Global));
  }.




#[export] Instance settable_SpecCcsConstraintProgram_record : Settable _ :=
  settable! (Build_SpecCcsConstraintProgram_record) <SpecCcsConstraintProgram_f_field; SpecCcsConstraintProgram_f_signals; SpecCcsConstraintProgram_f_constraints>.
Notation "'t_SpecCcsConstraintProgram'" := (SpecCcsConstraintProgram_record).


Fixpoint assign_public_signal_columns
  (signals : t_Vec ((t_SpecCcsSignal)) ((t_Global)))
  (signal_index : t_usize)
  (next_col : t_usize)
  (num_public : t_usize)
  (signal_columns : t_Vec ((t_usize)) ((t_Global)))
  : t_usize * t_usize * t_Vec ((t_usize)) ((t_Global)) :=
  match signals with
  | [] =>
      (next_col, num_public, signal_columns)
  | signal :: remaining_signals =>
      match SpecCcsSignal_f_visibility signal with
      | SpecCcsVisibility_Public =>
          let signal_columns :=
            impl__to_vec
              (update_at_usize
                (impl_1__as_slice signal_columns)
                signal_index
                next_col) in
          assign_public_signal_columns
            remaining_signals
            (f_add signal_index ((1 : t_usize)))
            (f_add next_col ((1 : t_usize)))
            (f_add num_public ((1 : t_usize)))
            signal_columns
      | SpecCcsVisibility_NonPublic =>
          assign_public_signal_columns
            remaining_signals
            (f_add signal_index ((1 : t_usize)))
            next_col
            num_public
            signal_columns
      end
  end.

Fixpoint assign_non_public_signal_columns
  (signals : t_Vec ((t_SpecCcsSignal)) ((t_Global)))
  (signal_index : t_usize)
  (next_col : t_usize)
  (signal_columns : t_Vec ((t_usize)) ((t_Global)))
  : t_usize * t_Vec ((t_usize)) ((t_Global)) :=
  match signals with
  | [] =>
      (next_col, signal_columns)
  | signal :: remaining_signals =>
      match SpecCcsSignal_f_visibility signal with
      | SpecCcsVisibility_Public =>
          assign_non_public_signal_columns
            remaining_signals
            (f_add signal_index ((1 : t_usize)))
            next_col
            signal_columns
      | SpecCcsVisibility_NonPublic =>
          let signal_columns :=
            impl__to_vec
              (update_at_usize
                (impl_1__as_slice signal_columns)
                signal_index
                next_col) in
          assign_non_public_signal_columns
            remaining_signals
            (f_add signal_index ((1 : t_usize)))
            (f_add next_col ((1 : t_usize)))
            signal_columns
      end
  end.

Definition builder_new (program : t_SpecCcsConstraintProgram) : t_SpecCcsBuilder :=
  let signal_columns :=
    from_elem
      ((0 : t_usize))
      (impl_1__len (SpecCcsConstraintProgram_f_signals program)) in
  let '(next_col, num_public, signal_columns) :=
    assign_public_signal_columns
      (SpecCcsConstraintProgram_f_signals program)
      (0 : t_usize)
      (1 : t_usize)
      (0 : t_usize)
      signal_columns in
  let '(next_col, signal_columns) :=
    assign_non_public_signal_columns
      (SpecCcsConstraintProgram_f_signals program)
      (0 : t_usize)
      next_col
      signal_columns in
  SpecCcsBuilder
    (SpecCcsConstraintProgram_f_field program)
    signal_columns
    next_col
    num_public
    (0 : t_usize)
    (impl__new tt)
    (impl__new tt)
    (impl__new tt).

Definition builder_signal_lc
  (builder : t_SpecCcsBuilder)
  (signal_index : t_usize)
  (constraint_index : t_usize)
  : t_Result ((t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)))) ((t_SpecCcsSynthesisError)) :=
  match impl__get (impl_1__as_slice (SpecCcsBuilder_f_signal_columns builder)) signal_index with
  | Option_Some col =>
      Result_Ok (lc_var col)
  | Option_None =>
      Result_Err
        (SpecCcsSynthesisError
          constraint_index
          SpecCcsSynthesisErrorKind_InvalidSignalIndex)
  end.

Definition builder_add_row
  (builder : t_SpecCcsBuilder)
  (a : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)))
  (b : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)))
  (c : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)))
  : t_SpecCcsBuilder :=
  let row := SpecCcsBuilder_f_row builder in
  let a_entries :=
    push_lc_entries
      (SpecCcsBuilder_f_field builder)
      (SpecCcsBuilder_f_a_entries builder)
      row
      a in
  let b_entries :=
    push_lc_entries
      (SpecCcsBuilder_f_field builder)
      (SpecCcsBuilder_f_b_entries builder)
      row
      b in
  let c_entries :=
    push_lc_entries
      (SpecCcsBuilder_f_field builder)
      (SpecCcsBuilder_f_c_entries builder)
      row
      c in
  SpecCcsBuilder
    (SpecCcsBuilder_f_field builder)
    (SpecCcsBuilder_f_signal_columns builder)
    (SpecCcsBuilder_f_next_col builder)
    (SpecCcsBuilder_f_num_public builder)
    (f_add row ((1 : t_usize)))
    a_entries
    b_entries
    c_entries.

Definition builder_expr_fuel_budget : nat := 4096%nat.

Definition builder_fuel_exhausted_error
  (constraint_index : t_usize) : t_SpecCcsSynthesisError :=
  SpecCcsSynthesisError constraint_index SpecCcsSynthesisErrorKind_InvalidSignalIndex.

Fixpoint builder_expr_to_lc_fueled
  (fuel : nat)
  (builder : t_SpecCcsBuilder)
  (expr : t_SpecCcsExpr)
  (constraint_index : t_usize)
  {struct fuel}
  : t_SpecCcsBuilder * t_Result ((t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)))) ((t_SpecCcsSynthesisError)) :=
  match fuel with
  | O =>
      (builder, Result_Err (builder_fuel_exhausted_error constraint_index))
  | S fuel =>
      match expr with
      | SpecCcsExpr_Const value =>
          (builder, Result_Ok (lc_const (spec_value_to_bigint value (SpecCcsBuilder_f_field builder))))
      | SpecCcsExpr_Signal signal_index =>
          (builder, builder_signal_lc builder signal_index constraint_index)
      | SpecCcsExpr_Add terms =>
          builder_terms_to_lc_acc_fueled fuel builder terms constraint_index (impl_18__new tt)
      | SpecCcsExpr_Sub lhs rhs =>
          let '(builder, lhs_result) := builder_expr_to_lc_fueled fuel builder lhs constraint_index in
          match lhs_result with
          | Result_Err error =>
              (builder, Result_Err error)
          | Result_Ok lhs_lc =>
              let '(builder, rhs_result) := builder_expr_to_lc_fueled fuel builder rhs constraint_index in
              match rhs_result with
              | Result_Err error =>
                  (builder, Result_Err error)
              | Result_Ok rhs_lc =>
                  (builder, Result_Ok (lc_sub_assign lhs_lc rhs_lc))
              end
          end
      | SpecCcsExpr_Mul lhs rhs =>
          let '(builder, lhs_result) := builder_expr_to_lc_fueled fuel builder lhs constraint_index in
          match lhs_result with
          | Result_Err error =>
              (builder, Result_Err error)
          | Result_Ok lhs_lc =>
              let '(builder, rhs_result) := builder_expr_to_lc_fueled fuel builder rhs constraint_index in
              match rhs_result with
              | Result_Err error =>
                  (builder, Result_Err error)
              | Result_Ok rhs_lc =>
                  let '(builder, aux_col) := builder_allocate_aux builder in
                  (builder_add_row builder lhs_lc rhs_lc (lc_var aux_col), Result_Ok (lc_var aux_col))
              end
          end
      | SpecCcsExpr_Div lhs rhs =>
          let '(builder, numerator_result) := builder_expr_to_lc_fueled fuel builder lhs constraint_index in
          match numerator_result with
          | Result_Err error =>
              (builder, Result_Err error)
          | Result_Ok numerator =>
              let '(builder, denominator_result) := builder_expr_to_lc_fueled fuel builder rhs constraint_index in
              match denominator_result with
              | Result_Err error =>
                  (builder, Result_Err error)
              | Result_Ok denominator =>
                  let '(builder, quotient_col) := builder_allocate_aux builder in
                  let '(builder, inverse_col) := builder_allocate_aux builder in
                  let builder :=
                    builder_add_row builder denominator (lc_var inverse_col) (lc_one tt) in
                  let builder :=
                    builder_add_row builder (lc_var quotient_col) denominator numerator in
                  (builder, Result_Ok (lc_var quotient_col))
              end
          end
      end
  end
with builder_terms_to_lc_acc_fueled
  (fuel : nat)
  (builder : t_SpecCcsBuilder)
  (terms : t_Vec ((t_SpecCcsExpr)) ((t_Global)))
  (constraint_index : t_usize)
  (acc : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)))
  {struct fuel}
  : t_SpecCcsBuilder * t_Result ((t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)))) ((t_SpecCcsSynthesisError)) :=
  match fuel with
  | O =>
      (builder, Result_Err (builder_fuel_exhausted_error constraint_index))
  | S fuel =>
      match terms with
      | [] =>
          (builder, Result_Ok acc)
      | term :: remaining_terms =>
          let '(builder, term_result) := builder_expr_to_lc_fueled fuel builder term constraint_index in
          match term_result with
          | Result_Err error =>
              (builder, Result_Err error)
          | Result_Ok term_lc =>
              builder_terms_to_lc_acc_fueled
                fuel
                builder
                remaining_terms
                constraint_index
                (lc_add_assign acc term_lc)
          end
      end
  end.

Definition builder_expr_to_lc
  (builder : t_SpecCcsBuilder)
  (expr : t_SpecCcsExpr)
  (constraint_index : t_usize)
  : t_SpecCcsBuilder * t_Result ((t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)))) ((t_SpecCcsSynthesisError)) :=
  builder_expr_to_lc_fueled builder_expr_fuel_budget builder expr constraint_index.

Fixpoint range_bits_to_lc
  (remaining : nat)
  (bit_index : nat)
  (builder : t_SpecCcsBuilder)
  (recomposed : t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)))
  : t_SpecCcsBuilder * t_BTreeMap ((t_usize)) ((t_BigInt)) ((t_Global)) :=
  match remaining with
  | O =>
      (builder, recomposed)
  | S remaining_bits =>
      let '(builder, bit_col) := builder_allocate_aux builder in
      let builder :=
        builder_add_row
          builder
          (lc_var bit_col)
          (lc_one_minus_var bit_col)
          (impl_18__new tt) in
      let recomposed :=
        lc_add_term recomposed bit_col (Z.shiftl 1%Z (Z.of_nat bit_index)) in
      range_bits_to_lc remaining_bits (S bit_index) builder recomposed
  end.

Definition encode_constraint_runtime
  (builder : t_SpecCcsBuilder)
  (constraint : t_SpecCcsConstraint)
  (constraint_index : t_usize)
  : t_SpecCcsBuilder * t_Result ((unit)) ((t_SpecCcsSynthesisError)) :=
  match constraint with
  | SpecCcsConstraint_Equal equal_constraint =>
      let lhs := SpecCcsConstraint_Equal_f_lhs equal_constraint in
      let rhs := SpecCcsConstraint_Equal_f_rhs equal_constraint in
      match lhs with
      | SpecCcsExpr_Mul lhs_term rhs_term =>
          let '(builder, a_result) := builder_expr_to_lc builder lhs_term constraint_index in
          match a_result with
          | Result_Err error =>
              (builder, Result_Err error)
          | Result_Ok a =>
              let '(builder, b_result) := builder_expr_to_lc builder rhs_term constraint_index in
              match b_result with
              | Result_Err error =>
                  (builder, Result_Err error)
              | Result_Ok b =>
                  let '(builder, c_result) := builder_expr_to_lc builder rhs constraint_index in
                  match c_result with
                  | Result_Err error =>
                      (builder, Result_Err error)
                  | Result_Ok c =>
                      (builder_add_row builder a b c, Result_Ok tt)
                  end
              end
          end
      | _ =>
          match rhs with
          | SpecCcsExpr_Mul lhs_term rhs_term =>
              let '(builder, a_result) := builder_expr_to_lc builder lhs_term constraint_index in
              match a_result with
              | Result_Err error =>
                  (builder, Result_Err error)
              | Result_Ok a =>
                  let '(builder, b_result) := builder_expr_to_lc builder rhs_term constraint_index in
                  match b_result with
                  | Result_Err error =>
                      (builder, Result_Err error)
                  | Result_Ok b =>
                      let '(builder, c_result) := builder_expr_to_lc builder lhs constraint_index in
                      match c_result with
                      | Result_Err error =>
                          (builder, Result_Err error)
                      | Result_Ok c =>
                          (builder_add_row builder a b c, Result_Ok tt)
                      end
                  end
              end
          | _ =>
              let '(builder, lhs_result) := builder_expr_to_lc builder lhs constraint_index in
              match lhs_result with
              | Result_Err error =>
                  (builder, Result_Err error)
              | Result_Ok lhs_lc =>
                  let '(builder, rhs_result) := builder_expr_to_lc builder rhs constraint_index in
                  match rhs_result with
                  | Result_Err error =>
                      (builder, Result_Err error)
                  | Result_Ok rhs_lc =>
                      let diff := lc_sub_assign lhs_lc rhs_lc in
                      (builder_add_row builder diff (lc_one tt) (impl_18__new tt), Result_Ok tt)
                  end
              end
          end
      end
  | SpecCcsConstraint_Boolean boolean_constraint =>
      let signal_index := SpecCcsConstraint_Boolean_f_signal_index boolean_constraint in
      match impl__get (impl_1__as_slice (SpecCcsBuilder_f_signal_columns builder)) signal_index with
      | Option_Some col =>
          let value := lc_var col in
          (builder_add_row builder value (lc_one_minus_var col) (impl_18__new tt), Result_Ok tt)
      | Option_None =>
          (builder, Result_Err (SpecCcsSynthesisError constraint_index SpecCcsSynthesisErrorKind_InvalidSignalIndex))
      end
  | SpecCcsConstraint_Range range_constraint =>
      let signal_index := SpecCcsConstraint_Range_f_signal_index range_constraint in
      let bits := SpecCcsConstraint_Range_f_bits range_constraint in
      match builder_signal_lc builder signal_index constraint_index with
      | Result_Err error =>
          (builder, Result_Err error)
      | Result_Ok signal_value =>
          let '(builder, recomposed) :=
            range_bits_to_lc
              (N.to_nat (u32_to_n bits))
              O
              builder
              (impl_18__new tt) in
          (builder_add_row builder signal_value (lc_one tt) recomposed, Result_Ok tt)
      end
  | SpecCcsConstraint_Lookup =>
      (builder, Result_Err (SpecCcsSynthesisError constraint_index SpecCcsSynthesisErrorKind_LookupRequiresLowering))
  | SpecCcsConstraint_BlackBox black_box_constraint =>
      match SpecCcsConstraint_BlackBox_f_kind black_box_constraint with
      | SpecCcsBlackBoxKind_RecursiveAggregationMarker =>
          (builder, Result_Ok tt)
      | SpecCcsBlackBoxKind_Other =>
          (builder, Result_Err (SpecCcsSynthesisError constraint_index SpecCcsSynthesisErrorKind_BlackBoxRequiresLowering))
      end
  end.

Fixpoint synthesize_constraints_from
  (builder : t_SpecCcsBuilder)
  (constraints : t_Vec ((t_SpecCcsConstraint)) ((t_Global)))
  (constraint_index : t_usize)
  {struct constraints}
  : t_Result ((t_SpecCcsBuilder)) ((t_SpecCcsSynthesisError)) :=
  match constraints with
  | [] =>
      Result_Ok builder
  | constraint :: remaining_constraints =>
      match encode_constraint_runtime builder constraint constraint_index with
      | (next_builder, Result_Ok tt) =>
          synthesize_constraints_from
            next_builder
            remaining_constraints
            (impl_usize__saturating_add constraint_index ((1 : t_usize)))
      | (_, Result_Err error) =>
          Result_Err error
      end
  end.

Definition synthesize_ccs_program
  (program : t_SpecCcsConstraintProgram)
  : t_Result ((t_SpecCcsProgram)) ((t_SpecCcsSynthesisError)) :=
  let builder := builder_new program in
  match synthesize_constraints_from builder (SpecCcsConstraintProgram_f_constraints program) (0 : t_usize) with
  | Result_Ok builder =>
      Result_Ok (builder_finish builder (SpecCcsConstraintProgram_f_field program))
  | Result_Err error =>
      Result_Err error
  end.
