(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.
From ZkfCoreExtraction Require Import Zkf_core_Field.
Require Import KernelCompat.

Record SpecFieldValue_record : Type :=
  {
    SpecFieldValue_f_bytes : t_Array (t_u8) ((32 : t_usize));
    SpecFieldValue_f_len : t_u8;
    SpecFieldValue_f_negative : bool;
  }.




#[export] Instance settable_SpecFieldValue_record : Settable _ :=
  settable! (Build_SpecFieldValue_record) <SpecFieldValue_f_bytes; SpecFieldValue_f_len; SpecFieldValue_f_negative>.
Notation "'t_SpecFieldValue'" := (SpecFieldValue_record).

Record SpecKernelLookupTable_record : Type :=
  {
    SpecKernelLookupTable_f_column_count : t_usize;
    SpecKernelLookupTable_f_rows : t_Vec ((t_Vec ((t_SpecFieldValue)) ((t_Global)))) ((t_Global));
  }.



#[export] Instance settable_SpecKernelLookupTable_record : Settable _ :=
  settable! (Build_SpecKernelLookupTable_record) <SpecKernelLookupTable_f_column_count; SpecKernelLookupTable_f_rows>.
Notation "'t_SpecKernelLookupTable'" := (SpecKernelLookupTable_record).
Notation "'f_column_count'" := (SpecKernelLookupTable_f_column_count).
Notation "'f_rows'" := (SpecKernelLookupTable_f_rows).

Record SpecKernelWitness_record : Type :=
  {
    SpecKernelWitness_f_values : t_Vec ((t_Option ((t_SpecFieldValue)))) ((t_Global));
  }.


#[export] Instance settable_SpecKernelWitness_record : Settable _ :=
  settable! (Build_SpecKernelWitness_record) <SpecKernelWitness_f_values>.
Notation "'t_SpecKernelWitness'" := (SpecKernelWitness_record).
Notation "'f_values'" := (SpecKernelWitness_f_values).

Record SpecLookupFailureKind_InputArityMismatch_record : Type :=
  {
    SpecLookupFailureKind_InputArityMismatch_f_provided : t_usize;
    SpecLookupFailureKind_InputArityMismatch_f_available : t_usize;
  }.



#[export] Instance settable_SpecLookupFailureKind_InputArityMismatch_record : Settable _ :=
  settable! (Build_SpecLookupFailureKind_InputArityMismatch_record) <SpecLookupFailureKind_InputArityMismatch_f_provided; SpecLookupFailureKind_InputArityMismatch_f_available>.
Inductive t_SpecLookupFailureKind : Type :=
| SpecLookupFailureKind_InputArityMismatch : SpecLookupFailureKind_InputArityMismatch_record  -> _
| SpecLookupFailureKind_NoMatchingRow.



Record SpecKernelCheckError_MissingSignal_record : Type :=
  {
    SpecKernelCheckError_MissingSignal_f_signal_index : t_usize;
  }.


#[export] Instance settable_SpecKernelCheckError_MissingSignal_record : Settable _ :=
  settable! (Build_SpecKernelCheckError_MissingSignal_record) <SpecKernelCheckError_MissingSignal_f_signal_index>.
Record SpecKernelCheckError_UnknownLookupTable_record : Type :=
  {
    SpecKernelCheckError_UnknownLookupTable_f_table_index : t_usize;
  }.


#[export] Instance settable_SpecKernelCheckError_UnknownLookupTable_record : Settable _ :=
  settable! (Build_SpecKernelCheckError_UnknownLookupTable_record) <SpecKernelCheckError_UnknownLookupTable_f_table_index>.
Record SpecKernelCheckError_EqualViolation_record : Type :=
  {
    SpecKernelCheckError_EqualViolation_f_constraint_index : t_usize;
    SpecKernelCheckError_EqualViolation_f_lhs : t_SpecFieldValue;
    SpecKernelCheckError_EqualViolation_f_rhs : t_SpecFieldValue;
  }.




#[export] Instance settable_SpecKernelCheckError_EqualViolation_record : Settable _ :=
  settable! (Build_SpecKernelCheckError_EqualViolation_record) <SpecKernelCheckError_EqualViolation_f_constraint_index; SpecKernelCheckError_EqualViolation_f_lhs; SpecKernelCheckError_EqualViolation_f_rhs>.
Record SpecKernelCheckError_BooleanViolation_record : Type :=
  {
    SpecKernelCheckError_BooleanViolation_f_constraint_index : t_usize;
    SpecKernelCheckError_BooleanViolation_f_signal_index : t_usize;
    SpecKernelCheckError_BooleanViolation_f_value : t_SpecFieldValue;
  }.




#[export] Instance settable_SpecKernelCheckError_BooleanViolation_record : Settable _ :=
  settable! (Build_SpecKernelCheckError_BooleanViolation_record) <SpecKernelCheckError_BooleanViolation_f_constraint_index; SpecKernelCheckError_BooleanViolation_f_signal_index; SpecKernelCheckError_BooleanViolation_f_value>.
Record SpecKernelCheckError_RangeViolation_record : Type :=
  {
    SpecKernelCheckError_RangeViolation_f_constraint_index : t_usize;
    SpecKernelCheckError_RangeViolation_f_signal_index : t_usize;
    SpecKernelCheckError_RangeViolation_f_bits : t_u32;
    SpecKernelCheckError_RangeViolation_f_value : t_SpecFieldValue;
  }.





#[export] Instance settable_SpecKernelCheckError_RangeViolation_record : Settable _ :=
  settable! (Build_SpecKernelCheckError_RangeViolation_record) <SpecKernelCheckError_RangeViolation_f_constraint_index; SpecKernelCheckError_RangeViolation_f_signal_index; SpecKernelCheckError_RangeViolation_f_bits; SpecKernelCheckError_RangeViolation_f_value>.
Record SpecKernelCheckError_LookupViolation_record : Type :=
  {
    SpecKernelCheckError_LookupViolation_f_constraint_index : t_usize;
    SpecKernelCheckError_LookupViolation_f_table_index : t_usize;
    SpecKernelCheckError_LookupViolation_f_inputs : t_Vec ((t_SpecFieldValue)) ((t_Global));
    SpecKernelCheckError_LookupViolation_f_outputs : t_Option ((t_Vec ((t_SpecFieldValue)) ((t_Global))));
    SpecKernelCheckError_LookupViolation_f_kind : t_SpecLookupFailureKind;
  }.






#[export] Instance settable_SpecKernelCheckError_LookupViolation_record : Settable _ :=
  settable! (Build_SpecKernelCheckError_LookupViolation_record) <SpecKernelCheckError_LookupViolation_f_constraint_index; SpecKernelCheckError_LookupViolation_f_table_index; SpecKernelCheckError_LookupViolation_f_inputs; SpecKernelCheckError_LookupViolation_f_outputs; SpecKernelCheckError_LookupViolation_f_kind>.
Inductive t_SpecKernelCheckError : Type :=
| SpecKernelCheckError_MissingSignal : SpecKernelCheckError_MissingSignal_record  -> _
| SpecKernelCheckError_DivisionByZero
| SpecKernelCheckError_UnknownLookupTable : SpecKernelCheckError_UnknownLookupTable_record  -> _
| SpecKernelCheckError_EqualViolation : SpecKernelCheckError_EqualViolation_record  -> _
| SpecKernelCheckError_BooleanViolation : SpecKernelCheckError_BooleanViolation_record  -> _
| SpecKernelCheckError_RangeViolation : SpecKernelCheckError_RangeViolation_record  -> _
| SpecKernelCheckError_LookupViolation : SpecKernelCheckError_LookupViolation_record  -> _.









Definition spec_field_modulus (field : t_FieldId) : Z :=
  match field with
  | FieldId_Bn254 =>
    21888242871839275222246405745257275088548364400416034343698204186575808495617%Z
  | FieldId_Bls12_381_ =>
    52435875175126190479447740508185965837690552500527637822603658699938581184513%Z
  | FieldId_PastaFp =>
    28948022309329048855892746252171976963363056481941560715954676764349967630337%Z
  | FieldId_PastaFq =>
    28948022309329048855892746252171976963363056481941647379679742748393362948097%Z
  | FieldId_Goldilocks =>
    18446744069414584321%Z
  | FieldId_BabyBear =>
    2013265921%Z
  | FieldId_Mersenne31 =>
    2147483647%Z
  end.

Definition spec_normalize_z (value modulus : Z) : Z :=
  ((value mod modulus) + modulus) mod modulus.

Definition spec_u8_of_z (value : Z) : t_u8 :=
  u8 (value mod 256).

Fixpoint spec_bytes_to_z_le (bytes : list t_u8) (weight : Z) : Z :=
  match bytes with
  | [] =>
    0%Z
  | byte :: remaining =>
    ((Z.of_N (U8_f_v (u8_0 byte))) * weight + spec_bytes_to_z_le remaining (weight * 256))%Z
  end.

Definition spec_field_value_to_z (value : t_SpecFieldValue) : Z :=
  let magnitude := spec_bytes_to_z_le (Slice_f_v (Array_f_v (SpecFieldValue_f_bytes value))) 1 in
  if SpecFieldValue_f_negative value then
    (- magnitude)%Z
  else
    magnitude.

Fixpoint spec_z_to_bytes_le (count : nat) (value : Z) : list t_u8 :=
  match count with
  | O =>
    []
  | S remaining =>
    spec_u8_of_z value :: spec_z_to_bytes_le remaining (value / 256)
  end.

Fixpoint spec_canonical_len_aux (bytes : list t_u8) (index current : Z) : Z :=
  match bytes with
  | [] =>
    current
  | byte :: remaining =>
    let next := if Z.eqb (Z.of_N (U8_f_v (u8_0 byte))) 0 then current else (index + 1)%Z in
    spec_canonical_len_aux remaining (index + 1)%Z next
  end.

Definition spec_bytes_to_array32 (bytes : list t_u8) : t_Array (t_u8) ((32 : t_usize)) :=
  Build_t_Array (Build_t_Slice _ bytes).

Definition spec_field_value_of_z (value : Z) : t_SpecFieldValue :=
  let bounded := if Z.ltb value 0 then 0%Z else value in
  let bytes := spec_z_to_bytes_le 32 bounded in
  {| SpecFieldValue_f_bytes := spec_bytes_to_array32 bytes;
     SpecFieldValue_f_len := u8 (spec_canonical_len_aux bytes 0%Z 0%Z);
     SpecFieldValue_f_negative := false |}.

Definition spec_mod_inverse (value modulus : Z) : option Z :=
  let '(g, coefficients) := Z.ggcd value modulus in
  let '(coefficient, _) := coefficients in
  if Z.eqb g 1%Z then
    Some (spec_normalize_z coefficient modulus)
  else
    None.

Definition zero '(_ : unit) : t_SpecFieldValue :=
  spec_field_value_of_z 0%Z.

Definition normalize (value : t_SpecFieldValue) (field : t_FieldId) : t_SpecFieldValue :=
  spec_field_value_of_z (spec_normalize_z (spec_field_value_to_z value) (spec_field_modulus field)).

Definition kernel_signal_value (witness : t_SpecKernelWitness) (signal_index : t_usize) (field : t_FieldId) : t_Result ((t_SpecFieldValue)) ((t_SpecKernelCheckError)) :=
  match impl__get (f_deref (f_values witness)) (signal_index) with
  | Option_Some (Option_Some (value)) =>
    Result_Ok (normalize (value) (field))
  | _ =>
    Result_Err (SpecKernelCheckError_MissingSignal {| SpecKernelCheckError_MissingSignal_f_signal_index := (signal_index) |})
  end.

Definition Add_f_add (lhs : t_SpecFieldValue) (rhs : t_SpecFieldValue) (field : t_FieldId) : t_SpecFieldValue :=
  let modulus := spec_field_modulus field in
  spec_field_value_of_z
    (spec_normalize_z
      (spec_normalize_z (spec_field_value_to_z lhs) modulus +
       spec_normalize_z (spec_field_value_to_z rhs) modulus)
      modulus).

Definition Sub_f_sub (lhs : t_SpecFieldValue) (rhs : t_SpecFieldValue) (field : t_FieldId) : t_SpecFieldValue :=
  let modulus := spec_field_modulus field in
  spec_field_value_of_z
    (spec_normalize_z
      (spec_normalize_z (spec_field_value_to_z lhs) modulus -
       spec_normalize_z (spec_field_value_to_z rhs) modulus)
      modulus).

Definition Mul_f_mul (lhs : t_SpecFieldValue) (rhs : t_SpecFieldValue) (field : t_FieldId) : t_SpecFieldValue :=
  let modulus := spec_field_modulus field in
  spec_field_value_of_z
    (spec_normalize_z
      (spec_normalize_z (spec_field_value_to_z lhs) modulus *
       spec_normalize_z (spec_field_value_to_z rhs) modulus)
      modulus).

Definition Div_f_div (lhs : t_SpecFieldValue) (rhs : t_SpecFieldValue) (field : t_FieldId) : t_Option ((t_SpecFieldValue)) :=
  let modulus := spec_field_modulus field in
  let lhs_value := spec_normalize_z (spec_field_value_to_z lhs) modulus in
  let rhs_value := spec_normalize_z (spec_field_value_to_z rhs) modulus in
  match spec_mod_inverse rhs_value modulus with
  | Some inverse =>
    Option_Some
      (spec_field_value_of_z
        (spec_normalize_z (lhs_value * inverse) modulus))
  | None =>
    Option_None
  end.

Definition PartialEq_f_eq (lhs : t_SpecFieldValue) (rhs : t_SpecFieldValue) (field : t_FieldId) : bool :=
  Z.eqb
    (spec_normalize_z (spec_field_value_to_z lhs) (spec_field_modulus field))
    (spec_normalize_z (spec_field_value_to_z rhs) (spec_field_modulus field)).

Definition is_boolean (value : t_SpecFieldValue) (field : t_FieldId) : bool :=
  let normalized := spec_normalize_z (spec_field_value_to_z value) (spec_field_modulus field) in
  orb (Z.eqb normalized 0%Z) (Z.eqb normalized 1%Z).

Definition fits_bits (value : t_SpecFieldValue) (bits : t_u32) (field : t_FieldId) : bool :=
  let normalized := spec_normalize_z (spec_field_value_to_z value) (spec_field_modulus field) in
  Z.ltb normalized (2 ^ (Z.of_N (U32_f_v (u32_0 bits)))).

Definition t_BigInt := Z.

Definition impl_FieldId__modulus (field : t_FieldId) : t_BigInt :=
  spec_field_modulus field.

Definition normalize_mod (value modulus : t_BigInt) : t_BigInt :=
  spec_normalize_z value modulus.

Definition mod_inverse_bigint (value modulus : t_BigInt) : t_Option ((t_BigInt)) :=
  match spec_mod_inverse value modulus with
  | Some inverse =>
    Option_Some inverse
  | None =>
    Option_None
  end.

Definition spec_field_value_raw_bigint (value : t_SpecFieldValue) : t_BigInt :=
  spec_field_value_to_z value.

Definition spec_field_value_from_bigint_with_field (value : t_BigInt) (field : t_FieldId) : t_SpecFieldValue :=
  spec_field_value_of_z (spec_normalize_z value (spec_field_modulus field)).

Definition spec_field_value_zero '(_ : unit) : t_SpecFieldValue :=
  spec_field_value_of_z 0%Z.

Definition spec_field_value_is_zero_raw (value : t_SpecFieldValue) : bool :=
  Z.eqb (spec_field_value_to_z value) 0%Z.

Definition spec_field_value_is_one_raw (value : t_SpecFieldValue) : bool :=
  Z.eqb (spec_field_value_to_z value) 1%Z.

Definition spec_normalize_mod_bigint (value : t_BigInt) (modulus : t_BigInt) : t_BigInt :=
  spec_normalize_z value modulus.

Definition spec_mod_inverse_bigint (value : t_BigInt) (modulus : t_BigInt) : t_Option ((t_BigInt)) :=
  match spec_mod_inverse value modulus with
  | Some inverse =>
    Option_Some inverse
  | None =>
    Option_None
  end.

Inductive t_SpecKernelExpr : Type :=
| SpecKernelExpr_Const : t_SpecFieldValue -> _
| SpecKernelExpr_Signal : t_usize -> _
| SpecKernelExpr_Add : t_SpecKernelExpr -> t_SpecKernelExpr -> _
| SpecKernelExpr_Sub : t_SpecKernelExpr -> t_SpecKernelExpr -> _
| SpecKernelExpr_Mul : t_SpecKernelExpr -> t_SpecKernelExpr -> _
| SpecKernelExpr_Div : t_SpecKernelExpr -> t_SpecKernelExpr -> _.








Fixpoint render_lookup_outputs_from_list (signal_indices : list t_usize) (current_column : t_usize) (lookup_table : t_SpecKernelLookupTable) (witness : t_SpecKernelWitness) (field : t_FieldId) (acc : t_Vec ((t_SpecFieldValue)) ((t_Global))) : t_Result ((t_Vec ((t_SpecFieldValue)) ((t_Global)))) ((t_SpecKernelCheckError)) :=
  match signal_indices with
  | [] =>
    Result_Ok (acc)
  | signal_index :: remaining_signal_indices =>
    if
      f_lt (current_column) (f_column_count lookup_table)
    then
      match kernel_signal_value (witness) (signal_index) (field) with
      | Result_Ok (value) =>
        let acc := impl_1__push (acc) (value) in
        render_lookup_outputs_from_list (remaining_signal_indices) (f_add (current_column) ((1 : t_usize))) (lookup_table) (witness) (field) (acc)
      | Result_Err (error) =>
        Result_Err (error)
      end
    else
      render_lookup_outputs_from_list (remaining_signal_indices) (f_add (current_column) ((1 : t_usize))) (lookup_table) (witness) (field) (acc)
  end.

Definition render_lookup_outputs_from (signal_indices : t_Slice t_usize) (current_column : t_usize) (lookup_table : t_SpecKernelLookupTable) (witness : t_SpecKernelWitness) (field : t_FieldId) (acc : t_Vec ((t_SpecFieldValue)) ((t_Global))) : t_Result ((t_Vec ((t_SpecFieldValue)) ((t_Global)))) ((t_SpecKernelCheckError)) :=
  render_lookup_outputs_from_list (Slice_f_v signal_indices) (current_column) (lookup_table) (witness) (field) (acc).


Fixpoint row_matches_inputs_from_list (row : list t_SpecFieldValue) (evaluated_inputs : list t_SpecFieldValue) (field : t_FieldId) : bool :=
  match evaluated_inputs with
  | [] =>
    (true : bool)
  | input_value :: remaining_inputs =>
    let row_result := match row with
    | [] =>
      (zero (tt), [])
    | value :: remaining_row =>
      (f_clone (value), remaining_row)
    end in
    let row_value := fst row_result in
    let remaining_row := snd row_result in
    andb (PartialEq_f_eq (row_value) (input_value) (field)) (row_matches_inputs_from_list (remaining_row) (remaining_inputs) (field))
  end.

Definition row_matches_inputs_from (row : t_Slice t_SpecFieldValue) (evaluated_inputs : t_Slice t_SpecFieldValue) (field : t_FieldId) : bool :=
  row_matches_inputs_from_list (Slice_f_v row) (Slice_f_v evaluated_inputs) (field).


Fixpoint skip_row_prefix_list (row : list t_SpecFieldValue) (remaining_to_skip : t_usize) : list t_SpecFieldValue :=
  if
    f_eq (remaining_to_skip) ((0 : t_usize))
  then
    row
  else
    match row with
    | [] =>
      row
    | _value :: remaining_row =>
      skip_row_prefix_list (remaining_row) (f_sub (remaining_to_skip) ((1 : t_usize)))
    end.

Definition skip_row_prefix (row : t_Slice t_SpecFieldValue) (remaining_to_skip : t_usize) : t_Slice t_SpecFieldValue :=
  Build_t_Slice _ (skip_row_prefix_list (Slice_f_v row) (remaining_to_skip)).


Fixpoint row_matches_outputs_from_list (row : list t_SpecFieldValue) (expected_outputs : list t_SpecFieldValue) (field : t_FieldId) : bool :=
  match expected_outputs with
  | [] =>
    (true : bool)
  | output_value :: remaining_outputs =>
    let row_result := match row with
    | [] =>
      (zero (tt), [])
    | value :: remaining_row =>
      (f_clone (value), remaining_row)
    end in
    let row_value := fst row_result in
    let remaining_row := snd row_result in
    andb (PartialEq_f_eq (row_value) (output_value) (field)) (row_matches_outputs_from_list (remaining_row) (remaining_outputs) (field))
  end.

Definition row_matches_outputs_from (row : t_Slice t_SpecFieldValue) (expected_outputs : t_Slice t_SpecFieldValue) (field : t_FieldId) : bool :=
  row_matches_outputs_from_list (Slice_f_v row) (Slice_f_v expected_outputs) (field).

Record SpecKernelConstraint_Equal_record : Type :=
  {
    SpecKernelConstraint_Equal_f_index : t_usize;
    SpecKernelConstraint_Equal_f_lhs : t_SpecKernelExpr;
    SpecKernelConstraint_Equal_f_rhs : t_SpecKernelExpr;
  }.




#[export] Instance settable_SpecKernelConstraint_Equal_record : Settable _ :=
  settable! (Build_SpecKernelConstraint_Equal_record) <SpecKernelConstraint_Equal_f_index; SpecKernelConstraint_Equal_f_lhs; SpecKernelConstraint_Equal_f_rhs>.
Record SpecKernelConstraint_Boolean_record : Type :=
  {
    SpecKernelConstraint_Boolean_f_index : t_usize;
    SpecKernelConstraint_Boolean_f_signal : t_usize;
  }.



#[export] Instance settable_SpecKernelConstraint_Boolean_record : Settable _ :=
  settable! (Build_SpecKernelConstraint_Boolean_record) <SpecKernelConstraint_Boolean_f_index; SpecKernelConstraint_Boolean_f_signal>.
Record SpecKernelConstraint_Range_record : Type :=
  {
    SpecKernelConstraint_Range_f_index : t_usize;
    SpecKernelConstraint_Range_f_signal : t_usize;
    SpecKernelConstraint_Range_f_bits : t_u32;
  }.




#[export] Instance settable_SpecKernelConstraint_Range_record : Settable _ :=
  settable! (Build_SpecKernelConstraint_Range_record) <SpecKernelConstraint_Range_f_index; SpecKernelConstraint_Range_f_signal; SpecKernelConstraint_Range_f_bits>.
Record SpecKernelConstraint_Lookup_record : Type :=
  {
    SpecKernelConstraint_Lookup_f_index : t_usize;
    SpecKernelConstraint_Lookup_f_inputs : t_Vec ((t_SpecKernelExpr)) ((t_Global));
    SpecKernelConstraint_Lookup_f_table_index : t_usize;
    SpecKernelConstraint_Lookup_f_outputs : t_Option ((t_Vec ((t_usize)) ((t_Global))));
  }.





#[export] Instance settable_SpecKernelConstraint_Lookup_record : Settable _ :=
  settable! (Build_SpecKernelConstraint_Lookup_record) <SpecKernelConstraint_Lookup_f_index; SpecKernelConstraint_Lookup_f_inputs; SpecKernelConstraint_Lookup_f_table_index; SpecKernelConstraint_Lookup_f_outputs>.
Inductive t_SpecKernelConstraint : Type :=
| SpecKernelConstraint_Equal : SpecKernelConstraint_Equal_record  -> _
| SpecKernelConstraint_Boolean : SpecKernelConstraint_Boolean_record  -> _
| SpecKernelConstraint_Range : SpecKernelConstraint_Range_record  -> _
| SpecKernelConstraint_Lookup : SpecKernelConstraint_Lookup_record  -> _.





Record SpecKernelProgram_record : Type :=
  {
    SpecKernelProgram_f_field : t_FieldId;
    SpecKernelProgram_f_constraints : t_Vec ((t_SpecKernelConstraint)) ((t_Global));
    SpecKernelProgram_f_lookup_tables : t_Vec ((t_SpecKernelLookupTable)) ((t_Global));
  }.




#[export] Instance settable_SpecKernelProgram_record : Settable _ :=
  settable! (Build_SpecKernelProgram_record) <SpecKernelProgram_f_field; SpecKernelProgram_f_constraints; SpecKernelProgram_f_lookup_tables>.
Notation "'t_SpecKernelProgram'" := (SpecKernelProgram_record).
Notation "'f_field'" := (SpecKernelProgram_f_field).
Notation "'f_constraints'" := (SpecKernelProgram_f_constraints).
Notation "'f_lookup_tables'" := (SpecKernelProgram_f_lookup_tables).

Definition render_lookup_outputs (signal_indices : t_Slice t_usize) (input_len : t_usize) (lookup_table : t_SpecKernelLookupTable) (witness : t_SpecKernelWitness) (field : t_FieldId) : t_Result ((t_Vec ((t_SpecFieldValue)) ((t_Global)))) ((t_SpecKernelCheckError)) :=
  render_lookup_outputs_from (signal_indices) (input_len) (lookup_table) (witness) (field) (impl__new (tt)).

Definition row_matches_inputs (row : t_Slice t_SpecFieldValue) (evaluated_inputs : t_Slice t_SpecFieldValue) (field : t_FieldId) : bool :=
  row_matches_inputs_from (row) (evaluated_inputs) (field).

Definition row_matches_outputs (row : t_Slice t_SpecFieldValue) (input_len : t_usize) (expected_outputs : t_Slice t_SpecFieldValue) (field : t_FieldId) : bool :=
  row_matches_outputs_from (skip_row_prefix (row) (input_len)) (expected_outputs) (field).


Fixpoint lookup_has_matching_row_from_list (rows : list (t_Vec ((t_SpecFieldValue)) ((t_Global)))) (evaluated_inputs : list t_SpecFieldValue) (expected_outputs : t_Option ((t_Vec ((t_SpecFieldValue)) ((t_Global))))) (input_len : t_usize) (field : t_FieldId) : bool :=
  match rows with
  | [] =>
    (false : bool)
  | row :: remaining_rows =>
    let row_matches := if
      row_matches_inputs_from_list (row) (evaluated_inputs) (field)
    then
      match expected_outputs with
      | Option_Some (outputs) =>
        row_matches_outputs_from_list (skip_row_prefix_list (row) (input_len)) (outputs) (field)
      | Option_None =>
        (true : bool)
      end
    else
      (false : bool) in
    orb (row_matches) (lookup_has_matching_row_from_list (remaining_rows) (evaluated_inputs) (expected_outputs) (input_len) (field))
  end.

Definition lookup_has_matching_row_from (rows : t_Slice (t_Vec ((t_SpecFieldValue)) ((t_Global)))) (evaluated_inputs : t_Slice t_SpecFieldValue) (expected_outputs : t_Option ((t_Vec ((t_SpecFieldValue)) ((t_Global))))) (input_len : t_usize) (field : t_FieldId) : bool :=
  lookup_has_matching_row_from_list (Slice_f_v rows) (Slice_f_v evaluated_inputs) (expected_outputs) (input_len) (field).

Fixpoint eval_expr (expr : t_SpecKernelExpr) (witness : t_SpecKernelWitness) (field : t_FieldId) : t_Result ((t_SpecFieldValue)) ((t_SpecKernelCheckError)) :=
  match expr with
  | SpecKernelExpr_Const (value) =>
    Result_Ok (normalize (value) (field))
  | SpecKernelExpr_Signal (signal_index) =>
    kernel_signal_value (witness) (signal_index) (field)
  | SpecKernelExpr_Add (lhs) (rhs) =>
    match eval_expr (lhs) (witness) (field) with
    | Result_Ok (lhs_value) =>
      match eval_expr (rhs) (witness) (field) with
      | Result_Ok (rhs_value) =>
        Result_Ok (Add_f_add (lhs_value) (rhs_value) (field))
      | Result_Err (error) =>
        Result_Err (error)
      end
    | Result_Err (error) =>
      Result_Err (error)
    end
  | SpecKernelExpr_Sub (lhs) (rhs) =>
    match eval_expr (lhs) (witness) (field) with
    | Result_Ok (lhs_value) =>
      match eval_expr (rhs) (witness) (field) with
      | Result_Ok (rhs_value) =>
        Result_Ok (Sub_f_sub (lhs_value) (rhs_value) (field))
      | Result_Err (error) =>
        Result_Err (error)
      end
    | Result_Err (error) =>
      Result_Err (error)
    end
  | SpecKernelExpr_Mul (lhs) (rhs) =>
    match eval_expr (lhs) (witness) (field) with
    | Result_Ok (lhs_value) =>
      match eval_expr (rhs) (witness) (field) with
      | Result_Ok (rhs_value) =>
        Result_Ok (Mul_f_mul (lhs_value) (rhs_value) (field))
      | Result_Err (error) =>
        Result_Err (error)
      end
    | Result_Err (error) =>
      Result_Err (error)
    end
  | SpecKernelExpr_Div (lhs) (rhs) =>
    match eval_expr (lhs) (witness) (field) with
    | Result_Ok (lhs_value) =>
      match eval_expr (rhs) (witness) (field) with
      | Result_Ok (rhs_value) =>
        match Div_f_div (lhs_value) (rhs_value) (field) with
        | Option_Some (value) =>
          Result_Ok (value)
        | Option_None =>
          Result_Err (SpecKernelCheckError_DivisionByZero)
        end
      | Result_Err (error) =>
        Result_Err (error)
      end
    | Result_Err (error) =>
      Result_Err (error)
    end
  end.


Fixpoint collect_evaluated_inputs_from_list (inputs : list t_SpecKernelExpr) (witness : t_SpecKernelWitness) (field : t_FieldId) (acc : t_Vec ((t_SpecFieldValue)) ((t_Global))) : t_Result ((t_Vec ((t_SpecFieldValue)) ((t_Global)))) ((t_SpecKernelCheckError)) :=
  match inputs with
  | [] =>
    Result_Ok (acc)
  | input :: remaining_inputs =>
    match eval_expr (input) (witness) (field) with
    | Result_Ok (value) =>
      let acc := impl_1__push (acc) (value) in
      collect_evaluated_inputs_from_list (remaining_inputs) (witness) (field) (acc)
    | Result_Err (error) =>
      Result_Err (error)
    end
  end.

Definition collect_evaluated_inputs_from (inputs : t_Slice t_SpecKernelExpr) (witness : t_SpecKernelWitness) (field : t_FieldId) (acc : t_Vec ((t_SpecFieldValue)) ((t_Global))) : t_Result ((t_Vec ((t_SpecFieldValue)) ((t_Global)))) ((t_SpecKernelCheckError)) :=
  collect_evaluated_inputs_from_list (Slice_f_v inputs) (witness) (field) (acc).

Definition collect_evaluated_inputs (inputs : t_Slice t_SpecKernelExpr) (witness : t_SpecKernelWitness) (field : t_FieldId) : t_Result ((t_Vec ((t_SpecFieldValue)) ((t_Global)))) ((t_SpecKernelCheckError)) :=
  collect_evaluated_inputs_from (inputs) (witness) (field) (impl__new (tt)).


Fixpoint check_constraints_from_list (constraints : list t_SpecKernelConstraint) (program : t_SpecKernelProgram) (witness : t_SpecKernelWitness) : t_Result ((unit)) ((t_SpecKernelCheckError)) :=
  match constraints with
  | [] =>
    Result_Ok (tt)
  | constraint :: remaining_constraints =>
    match constraint with
    | SpecKernelConstraint_Equal (equal_constraint) =>
      let index := SpecKernelConstraint_Equal_f_index equal_constraint in
      let lhs := SpecKernelConstraint_Equal_f_lhs equal_constraint in
      let rhs := SpecKernelConstraint_Equal_f_rhs equal_constraint in
      match eval_expr (lhs) (witness) (f_field program) with
      | Result_Ok (lhs_value) =>
        match eval_expr (rhs) (witness) (f_field program) with
        | Result_Ok (rhs_value) =>
          if
            PartialEq_f_eq (lhs_value) (rhs_value) (f_field program)
          then
            check_constraints_from_list (remaining_constraints) (program) (witness)
          else
            Result_Err (SpecKernelCheckError_EqualViolation {| SpecKernelCheckError_EqualViolation_f_constraint_index := (index); SpecKernelCheckError_EqualViolation_f_lhs := (lhs_value); SpecKernelCheckError_EqualViolation_f_rhs := (rhs_value) |})
        | Result_Err (error) =>
          Result_Err (error)
        end
      | Result_Err (error) =>
        Result_Err (error)
      end
    | SpecKernelConstraint_Boolean (boolean_constraint) =>
      let index := SpecKernelConstraint_Boolean_f_index boolean_constraint in
      let signal := SpecKernelConstraint_Boolean_f_signal boolean_constraint in
      match kernel_signal_value (witness) (signal) (f_field program) with
      | Result_Ok (value) =>
        if
          is_boolean (value) (f_field program)
        then
          check_constraints_from_list (remaining_constraints) (program) (witness)
        else
          Result_Err (SpecKernelCheckError_BooleanViolation {| SpecKernelCheckError_BooleanViolation_f_constraint_index := (index); SpecKernelCheckError_BooleanViolation_f_signal_index := (signal); SpecKernelCheckError_BooleanViolation_f_value := (value) |})
      | Result_Err (error) =>
        Result_Err (error)
      end
    | SpecKernelConstraint_Range (range_constraint) =>
      let index := SpecKernelConstraint_Range_f_index range_constraint in
      let signal := SpecKernelConstraint_Range_f_signal range_constraint in
      let bits := SpecKernelConstraint_Range_f_bits range_constraint in
      match kernel_signal_value (witness) (signal) (f_field program) with
      | Result_Ok (value) =>
        if
          fits_bits (value) (bits) (f_field program)
        then
          check_constraints_from_list (remaining_constraints) (program) (witness)
        else
          Result_Err (SpecKernelCheckError_RangeViolation {| SpecKernelCheckError_RangeViolation_f_constraint_index := (index); SpecKernelCheckError_RangeViolation_f_signal_index := (signal); SpecKernelCheckError_RangeViolation_f_bits := (bits); SpecKernelCheckError_RangeViolation_f_value := (value) |})
      | Result_Err (error) =>
        Result_Err (error)
      end
    | SpecKernelConstraint_Lookup (lookup_constraint) =>
      let index := SpecKernelConstraint_Lookup_f_index lookup_constraint in
      let inputs := SpecKernelConstraint_Lookup_f_inputs lookup_constraint in
      let table_index := SpecKernelConstraint_Lookup_f_table_index lookup_constraint in
      let outputs := SpecKernelConstraint_Lookup_f_outputs lookup_constraint in
      match impl__get (f_deref (f_lookup_tables program)) (table_index) with
      | Option_Some (lookup_table) =>
        if
          f_gt (impl_1__len (inputs)) (f_column_count lookup_table)
        then
          match collect_evaluated_inputs_from_list (inputs) (witness) (f_field program) (impl__new (tt)) with
          | Result_Ok (rendered_inputs) =>
            match outputs with
            | Option_Some (signal_indices) =>
              match render_lookup_outputs_from_list (signal_indices) (impl_1__len (inputs)) (lookup_table) (witness) (f_field program) (impl__new (tt)) with
              | Result_Ok (values) =>
                Result_Err (SpecKernelCheckError_LookupViolation {| SpecKernelCheckError_LookupViolation_f_constraint_index := (index); SpecKernelCheckError_LookupViolation_f_table_index := (table_index); SpecKernelCheckError_LookupViolation_f_inputs := (rendered_inputs); SpecKernelCheckError_LookupViolation_f_outputs := (Option_Some (values)); SpecKernelCheckError_LookupViolation_f_kind := (SpecLookupFailureKind_InputArityMismatch {| SpecLookupFailureKind_InputArityMismatch_f_provided := (impl_1__len (inputs)); SpecLookupFailureKind_InputArityMismatch_f_available := (f_column_count lookup_table) |}) |})
              | Result_Err (error) =>
                Result_Err (error)
              end
            | Option_None =>
              Result_Err (SpecKernelCheckError_LookupViolation {| SpecKernelCheckError_LookupViolation_f_constraint_index := (index); SpecKernelCheckError_LookupViolation_f_table_index := (table_index); SpecKernelCheckError_LookupViolation_f_inputs := (rendered_inputs); SpecKernelCheckError_LookupViolation_f_outputs := (Option_None); SpecKernelCheckError_LookupViolation_f_kind := (SpecLookupFailureKind_InputArityMismatch {| SpecLookupFailureKind_InputArityMismatch_f_provided := (impl_1__len (inputs)); SpecLookupFailureKind_InputArityMismatch_f_available := (f_column_count lookup_table) |}) |})
            end
          | Result_Err (error) =>
            Result_Err (error)
          end
        else
          match collect_evaluated_inputs_from_list (inputs) (witness) (f_field program) (impl__new (tt)) with
          | Result_Ok (evaluated_inputs) =>
            match outputs with
            | Option_Some (signal_indices) =>
              match render_lookup_outputs_from_list (signal_indices) (impl_1__len (inputs)) (lookup_table) (witness) (f_field program) (impl__new (tt)) with
              | Result_Ok (values) =>
                let expected_outputs := Option_Some (values) in
                if
                  lookup_has_matching_row_from_list (f_rows lookup_table) (evaluated_inputs) (expected_outputs) (impl_1__len (inputs)) (f_field program)
                then
                  check_constraints_from_list (remaining_constraints) (program) (witness)
                else
                  Result_Err (SpecKernelCheckError_LookupViolation {| SpecKernelCheckError_LookupViolation_f_constraint_index := (index); SpecKernelCheckError_LookupViolation_f_table_index := (table_index); SpecKernelCheckError_LookupViolation_f_inputs := (evaluated_inputs); SpecKernelCheckError_LookupViolation_f_outputs := (expected_outputs); SpecKernelCheckError_LookupViolation_f_kind := (SpecLookupFailureKind_NoMatchingRow) |})
              | Result_Err (error) =>
                Result_Err (error)
              end
            | Option_None =>
              let expected_outputs := Option_None in
              if
                lookup_has_matching_row_from_list (f_rows lookup_table) (evaluated_inputs) (expected_outputs) (impl_1__len (inputs)) (f_field program)
              then
                check_constraints_from_list (remaining_constraints) (program) (witness)
              else
                Result_Err (SpecKernelCheckError_LookupViolation {| SpecKernelCheckError_LookupViolation_f_constraint_index := (index); SpecKernelCheckError_LookupViolation_f_table_index := (table_index); SpecKernelCheckError_LookupViolation_f_inputs := (evaluated_inputs); SpecKernelCheckError_LookupViolation_f_outputs := (expected_outputs); SpecKernelCheckError_LookupViolation_f_kind := (SpecLookupFailureKind_NoMatchingRow) |})
            end
          | Result_Err (error) =>
            Result_Err (error)
          end
      | Option_None =>
        Result_Err (SpecKernelCheckError_UnknownLookupTable {| SpecKernelCheckError_UnknownLookupTable_f_table_index := (table_index) |})
      end
    end
  end.

Definition check_constraints_from (constraints : t_Slice t_SpecKernelConstraint) (program : t_SpecKernelProgram) (witness : t_SpecKernelWitness) : t_Result ((unit)) ((t_SpecKernelCheckError)) :=
  check_constraints_from_list (Slice_f_v constraints) (program) (witness).

Definition check_program (program : t_SpecKernelProgram) (witness : t_SpecKernelWitness) : t_Result ((unit)) ((t_SpecKernelCheckError)) :=
  check_constraints_from (f_deref (f_constraints program)) (program) (witness).
