(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.
From ZkfCoreExtraction Require Import Zkf_core_Field.
From ZkfCoreExtraction Require Import Zkf_core_Proof_kernel_spec_Bundle.
From ZkfCoreExtraction Require Import Zkf_core_Proof_kernel_spec.
Require Import KernelCompat.

Record SpecWitnessSignal_record : Type :=
  {
    SpecWitnessSignal_f_constant_value : t_Option ((t_SpecFieldValue));
    SpecWitnessSignal_f_required : bool;
  }.



#[export] Instance settable_SpecWitnessSignal_record : Settable _ :=
  settable! (Build_SpecWitnessSignal_record) <SpecWitnessSignal_f_constant_value; SpecWitnessSignal_f_required>.
Notation "'t_SpecWitnessSignal'" := (SpecWitnessSignal_record).

Record SpecWitnessAssignment_record : Type :=
  {
    SpecWitnessAssignment_f_target_signal_index : t_usize;
    SpecWitnessAssignment_f_expr : t_SpecKernelExpr;
  }.



#[export] Instance settable_SpecWitnessAssignment_record : Settable _ :=
  settable! (Build_SpecWitnessAssignment_record) <SpecWitnessAssignment_f_target_signal_index; SpecWitnessAssignment_f_expr>.
Notation "'t_SpecWitnessAssignment'" := (SpecWitnessAssignment_record).

Record SpecWitnessHint_record : Type :=
  {
    SpecWitnessHint_f_target_signal_index : t_usize;
    SpecWitnessHint_f_source_signal_index : t_usize;
  }.



#[export] Instance settable_SpecWitnessHint_record : Settable _ :=
  settable! (Build_SpecWitnessHint_record) <SpecWitnessHint_f_target_signal_index; SpecWitnessHint_f_source_signal_index>.
Notation "'t_SpecWitnessHint'" := (SpecWitnessHint_record).

Record SpecWitnessGenerationProgram_record : Type :=
  {
    SpecWitnessGenerationProgram_f_kernel_program : t_SpecKernelProgram;
    SpecWitnessGenerationProgram_f_signals : t_Vec ((t_SpecWitnessSignal)) ((t_Global));
    SpecWitnessGenerationProgram_f_assignments : t_Vec ((t_SpecWitnessAssignment)) ((t_Global));
    SpecWitnessGenerationProgram_f_hints : t_Vec ((t_SpecWitnessHint)) ((t_Global));
  }.





#[export] Instance settable_SpecWitnessGenerationProgram_record : Settable _ :=
  settable! (Build_SpecWitnessGenerationProgram_record) <SpecWitnessGenerationProgram_f_kernel_program; SpecWitnessGenerationProgram_f_signals; SpecWitnessGenerationProgram_f_assignments; SpecWitnessGenerationProgram_f_hints>.
Notation "'t_SpecWitnessGenerationProgram'" := (SpecWitnessGenerationProgram_record).
Notation "'f_kernel_program'" := (SpecWitnessGenerationProgram_f_kernel_program).
Notation "'f_signals'" := (SpecWitnessGenerationProgram_f_signals).
Notation "'f_assignments'" := (SpecWitnessGenerationProgram_f_assignments).
Notation "'f_hints'" := (SpecWitnessGenerationProgram_f_hints).

Record SpecWitnessGenerationError_MissingRequiredSignal_record : Type :=
  {
    SpecWitnessGenerationError_MissingRequiredSignal_f_signal_index : t_usize;
  }.


#[export] Instance settable_SpecWitnessGenerationError_MissingRequiredSignal_record : Settable _ :=
  settable! (Build_SpecWitnessGenerationError_MissingRequiredSignal_record) <SpecWitnessGenerationError_MissingRequiredSignal_f_signal_index>.
Record SpecWitnessGenerationError_UnsupportedWitnessSolve_record : Type :=
  {
    SpecWitnessGenerationError_UnsupportedWitnessSolve_f_unresolved_signal_indices : t_Vec ((t_usize)) ((t_Global));
  }.


#[export] Instance settable_SpecWitnessGenerationError_UnsupportedWitnessSolve_record : Settable _ :=
  settable! (Build_SpecWitnessGenerationError_UnsupportedWitnessSolve_record) <SpecWitnessGenerationError_UnsupportedWitnessSolve_f_unresolved_signal_indices>.
Record SpecWitnessGenerationError_AmbiguousLookup_record : Type :=
  {
    SpecWitnessGenerationError_AmbiguousLookup_f_constraint_index : t_usize;
    SpecWitnessGenerationError_AmbiguousLookup_f_table_index : t_usize;
  }.



#[export] Instance settable_SpecWitnessGenerationError_AmbiguousLookup_record : Settable _ :=
  settable! (Build_SpecWitnessGenerationError_AmbiguousLookup_record) <SpecWitnessGenerationError_AmbiguousLookup_f_constraint_index; SpecWitnessGenerationError_AmbiguousLookup_f_table_index>.
Inductive t_SpecWitnessGenerationError : Type :=
| SpecWitnessGenerationError_MissingRequiredSignal : SpecWitnessGenerationError_MissingRequiredSignal_record  -> _
| SpecWitnessGenerationError_UnsupportedWitnessSolve : SpecWitnessGenerationError_UnsupportedWitnessSolve_record  -> _
| SpecWitnessGenerationError_KernelCheck : t_SpecKernelCheckError -> _
| SpecWitnessGenerationError_AmbiguousLookup : SpecWitnessGenerationError_AmbiguousLookup_record  -> _.





Definition wg_u32_one : t_u32 :=
  Build_t_u32 (Build_t_U32 1%N).

Definition wg_zero_value : t_SpecFieldValue :=
  Zkf_core_Proof_kernel_spec_Bundle.zero tt.

Definition wg_normalize_value
  (value : t_SpecFieldValue)
  (field : t_FieldId) : t_SpecFieldValue :=
  Zkf_core_Proof_kernel_spec_Bundle.normalize value field.

Definition wg_field_add
  (lhs rhs : t_SpecFieldValue)
  (field : t_FieldId) : t_SpecFieldValue :=
  Zkf_core_Proof_kernel_spec_Bundle.Add_f_add lhs rhs field.

Definition wg_field_sub
  (lhs rhs : t_SpecFieldValue)
  (field : t_FieldId) : t_SpecFieldValue :=
  Zkf_core_Proof_kernel_spec_Bundle.Sub_f_sub lhs rhs field.

Definition wg_field_mul
  (lhs rhs : t_SpecFieldValue)
  (field : t_FieldId) : t_SpecFieldValue :=
  Zkf_core_Proof_kernel_spec_Bundle.Mul_f_mul lhs rhs field.

Definition wg_field_div
  (lhs rhs : t_SpecFieldValue)
  (field : t_FieldId) : t_Option ((t_SpecFieldValue)) :=
  Zkf_core_Proof_kernel_spec_Bundle.Div_f_div lhs rhs field.

Definition wg_field_eq
  (lhs rhs : t_SpecFieldValue)
  (field : t_FieldId) : bool :=
  Zkf_core_Proof_kernel_spec_Bundle.PartialEq_f_eq lhs rhs field.

Definition wg_witness_of_values
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global)) : t_SpecKernelWitness :=
  Build_SpecKernelWitness_record values.

Fixpoint wg_seed_signal_values
  (signals : t_Vec ((t_SpecWitnessSignal)) (t_Global)) :
  t_Vec (t_Option ((t_SpecFieldValue))) (t_Global) :=
  match signals with
  | [] =>
    []
  | signal :: remaining_signals =>
    SpecWitnessSignal_f_constant_value signal :: wg_seed_signal_values remaining_signals
  end.

Fixpoint wg_apply_inputs
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (inputs : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global)) :
  t_Vec (t_Option ((t_SpecFieldValue))) (t_Global) :=
  match values, inputs with
  | [], _ =>
    []
  | current_value :: remaining_values, [] =>
    current_value :: remaining_values
  | current_value :: remaining_values, input_value :: remaining_inputs =>
    match input_value with
    | Option_Some value =>
      Option_Some value :: wg_apply_inputs remaining_values remaining_inputs
    | Option_None =>
      current_value :: wg_apply_inputs remaining_values remaining_inputs
    end
  end.

Definition wg_value_at
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (signal_index : t_usize) : t_Option ((t_SpecFieldValue)) :=
  match nth_error values (usize_to_nat signal_index) with
  | Some value =>
    value
  | None =>
    Option_None
  end.

Definition wg_has_value
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (signal_index : t_usize) : bool :=
  match wg_value_at values signal_index with
  | Option_Some _ =>
    true
  | Option_None =>
    false
  end.

Fixpoint wg_update_values_at_nat
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (index : nat)
  (value : t_SpecFieldValue) :
  t_Vec (t_Option ((t_SpecFieldValue))) (t_Global) :=
  match values, index with
  | [], _ =>
    []
  | _ :: remaining_values, O =>
    Option_Some value :: remaining_values
  | current_value :: remaining_values, S remaining_index =>
    current_value :: wg_update_values_at_nat remaining_values remaining_index value
  end.

Definition wg_set_value
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (signal_index : t_usize)
  (value : t_SpecFieldValue) :
  t_Vec (t_Option ((t_SpecFieldValue))) (t_Global) :=
  wg_update_values_at_nat values (usize_to_nat signal_index) value.

Fixpoint wg_all_output_values_present
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (signal_indices : t_Vec ((t_usize)) (t_Global)) : bool :=
  match signal_indices with
  | [] =>
    true
  | signal_index :: remaining_signal_indices =>
    andb
      (wg_has_value values signal_index)
      (wg_all_output_values_present values remaining_signal_indices)
  end.

Fixpoint wg_usize_mem
  (signal_index : t_usize)
  (signal_indices : t_Vec ((t_usize)) (t_Global)) : bool :=
  match signal_indices with
  | [] =>
    false
  | current_signal :: remaining_signal_indices =>
    if f_eq current_signal signal_index then
      true
    else
      wg_usize_mem signal_index remaining_signal_indices
  end.

Definition wg_push_unique_usize
  (signal_index : t_usize)
  (signal_indices : t_Vec ((t_usize)) (t_Global)) :
  t_Vec ((t_usize)) (t_Global) :=
  if wg_usize_mem signal_index signal_indices then
    signal_indices
  else
    signal_indices ++ [signal_index].

Fixpoint wg_collect_missing_signals_expr
  (expr : t_SpecKernelExpr)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (acc : t_Vec ((t_usize)) (t_Global)) :
  t_Vec ((t_usize)) (t_Global) :=
  match expr with
  | SpecKernelExpr_Const _ =>
    acc
  | SpecKernelExpr_Signal signal_index =>
    if wg_has_value values signal_index then
      acc
    else
      wg_push_unique_usize signal_index acc
  | SpecKernelExpr_Add lhs rhs =>
    let acc := wg_collect_missing_signals_expr lhs values acc in
    wg_collect_missing_signals_expr rhs values acc
  | SpecKernelExpr_Sub lhs rhs =>
    let acc := wg_collect_missing_signals_expr lhs values acc in
    wg_collect_missing_signals_expr rhs values acc
  | SpecKernelExpr_Mul lhs rhs =>
    let acc := wg_collect_missing_signals_expr lhs values acc in
    wg_collect_missing_signals_expr rhs values acc
  | SpecKernelExpr_Div lhs rhs =>
    let acc := wg_collect_missing_signals_expr lhs values acc in
    wg_collect_missing_signals_expr rhs values acc
  end.

Fixpoint wg_eval_exprs
  (exprs : t_Vec ((t_SpecKernelExpr)) (t_Global))
  (witness : t_SpecKernelWitness)
  (field : t_FieldId) :
  t_Result ((t_Vec ((t_SpecFieldValue)) (t_Global))) ((t_SpecKernelCheckError)) :=
  match exprs with
  | [] =>
    Result_Ok []
  | expr :: remaining_exprs =>
    match eval_expr expr witness field with
    | Result_Ok value =>
      match wg_eval_exprs remaining_exprs witness field with
      | Result_Ok remaining_values =>
        Result_Ok (value :: remaining_values)
      | Result_Err error =>
        Result_Err error
      end
    | Result_Err error =>
      Result_Err error
    end
  end.

Definition wg_is_zero_value (value : t_SpecFieldValue) (field : t_FieldId) : bool :=
  wg_field_eq value wg_zero_value field.

Fixpoint wg_extract_affine_form
  (expr : t_SpecKernelExpr)
  (target : t_usize)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (field : t_FieldId) :
  t_Option ((t_SpecFieldValue * t_SpecFieldValue)) :=
  match expr with
  | SpecKernelExpr_Const value =>
    Option_Some (wg_zero_value, wg_normalize_value value field)
  | SpecKernelExpr_Signal signal_index =>
    if f_eq signal_index target then
      Option_Some (spec_field_value_of_z 1%Z, wg_zero_value)
    else
      match wg_value_at values signal_index with
      | Option_Some value =>
        Option_Some (wg_zero_value, wg_normalize_value value field)
      | Option_None =>
        Option_None
      end
  | SpecKernelExpr_Add lhs rhs =>
    match wg_extract_affine_form lhs target values field,
          wg_extract_affine_form rhs target values field with
    | Option_Some (lhs_coeff, lhs_const), Option_Some (rhs_coeff, rhs_const) =>
      Option_Some
        ( wg_field_add lhs_coeff rhs_coeff field,
          wg_field_add lhs_const rhs_const field )
    | _, _ =>
      Option_None
    end
  | SpecKernelExpr_Sub lhs rhs =>
    match wg_extract_affine_form lhs target values field,
          wg_extract_affine_form rhs target values field with
    | Option_Some (lhs_coeff, lhs_const), Option_Some (rhs_coeff, rhs_const) =>
      Option_Some
        ( wg_field_sub lhs_coeff rhs_coeff field,
          wg_field_sub lhs_const rhs_const field )
    | _, _ =>
      Option_None
    end
  | SpecKernelExpr_Mul lhs rhs =>
    match wg_extract_affine_form lhs target values field,
          wg_extract_affine_form rhs target values field with
    | Option_Some (lhs_coeff, lhs_const), Option_Some (rhs_coeff, rhs_const) =>
      let lhs_coeff_is_zero := wg_is_zero_value lhs_coeff field in
      let rhs_coeff_is_zero := wg_is_zero_value rhs_coeff field in
      if lhs_coeff_is_zero then
        if rhs_coeff_is_zero then
          Option_Some
            ( wg_zero_value,
              wg_field_mul lhs_const rhs_const field )
        else
          Option_Some
            ( wg_field_mul lhs_const rhs_coeff field,
              wg_field_mul lhs_const rhs_const field )
      else if rhs_coeff_is_zero then
        Option_Some
          ( wg_field_mul rhs_const lhs_coeff field,
            wg_field_mul lhs_const rhs_const field )
      else
        Option_None
    | _, _ =>
      Option_None
    end
  | SpecKernelExpr_Div lhs rhs =>
    match wg_extract_affine_form lhs target values field,
          wg_extract_affine_form rhs target values field with
    | Option_Some (lhs_coeff, lhs_const), Option_Some (rhs_coeff, rhs_const) =>
      if wg_is_zero_value rhs_coeff field then
        match wg_field_div lhs_coeff rhs_const field,
              wg_field_div lhs_const rhs_const field with
        | Option_Some coeff, Option_Some constant =>
          Option_Some (coeff, constant)
        | _, _ =>
          Option_None
        end
      else
        Option_None
    | _, _ =>
      Option_None
    end
  end.

Definition wg_solve_single_missing_equality
  (lhs : t_SpecKernelExpr)
  (rhs : t_SpecKernelExpr)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (field : t_FieldId) :
  t_Option ((t_usize * t_SpecFieldValue)) :=
  let missing :=
    wg_collect_missing_signals_expr
      rhs
      values
      (wg_collect_missing_signals_expr lhs values []) in
  match missing with
  | [signal_index] =>
    match wg_extract_affine_form lhs signal_index values field,
          wg_extract_affine_form rhs signal_index values field with
    | Option_Some (lhs_coeff, lhs_const), Option_Some (rhs_coeff, rhs_const) =>
      let coeff := wg_field_sub lhs_coeff rhs_coeff field in
      if wg_is_zero_value coeff field then
        Option_None
      else
        let constant := wg_field_sub lhs_const rhs_const field in
        let neg_constant := wg_field_sub wg_zero_value constant field in
        match wg_field_div neg_constant coeff field with
        | Option_Some value =>
          Option_Some (signal_index, value)
        | Option_None =>
          Option_None
        end
    | _, _ =>
      Option_None
    end
  | _ =>
    Option_None
  end.

Definition wg_extract_known_scalar
  (expr : t_SpecKernelExpr)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (field : t_FieldId) : t_Option ((t_SpecFieldValue)) :=
  match expr with
  | SpecKernelExpr_Const value =>
    Option_Some (wg_normalize_value value field)
  | SpecKernelExpr_Signal signal_index =>
    match wg_value_at values signal_index with
    | Option_Some value =>
      Option_Some (wg_normalize_value value field)
    | Option_None =>
      Option_None
    end
  | _ =>
    Option_None
  end.

Fixpoint wg_scale_missing_terms
  (factor : t_SpecFieldValue)
  (terms : t_Vec ((t_usize * t_SpecFieldValue)) (t_Global))
  (field : t_FieldId) :
  t_Vec ((t_usize * t_SpecFieldValue)) (t_Global) :=
  match terms with
  | [] =>
    []
  | (signal_index, coeff) :: remaining_terms =>
    (signal_index, wg_field_mul coeff factor field)
      :: wg_scale_missing_terms factor remaining_terms field
  end.

Fixpoint wg_negate_missing_terms
  (terms : t_Vec ((t_usize * t_SpecFieldValue)) (t_Global))
  (field : t_FieldId) :
  t_Vec ((t_usize * t_SpecFieldValue)) (t_Global) :=
  match terms with
  | [] =>
    []
  | (signal_index, coeff) :: remaining_terms =>
    (signal_index, wg_field_sub wg_zero_value coeff field)
      :: wg_negate_missing_terms remaining_terms field
  end.

Fixpoint wg_extract_scaled_missing_terms
  (expr : t_SpecKernelExpr)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (field : t_FieldId) :
  t_Option
    ((t_SpecFieldValue * t_Vec ((t_usize * t_SpecFieldValue)) (t_Global))) :=
  match expr with
  | SpecKernelExpr_Const value =>
    Option_Some (wg_normalize_value value field, [])
  | SpecKernelExpr_Signal signal_index =>
    match wg_value_at values signal_index with
    | Option_Some value =>
      Option_Some (wg_normalize_value value field, [])
    | Option_None =>
      Option_Some (wg_zero_value, [(signal_index, spec_field_value_of_z 1%Z)])
    end
  | SpecKernelExpr_Add lhs rhs =>
    match wg_extract_scaled_missing_terms lhs values field,
          wg_extract_scaled_missing_terms rhs values field with
    | Option_Some (lhs_known, lhs_missing), Option_Some (rhs_known, rhs_missing) =>
      Option_Some
        ( wg_field_add lhs_known rhs_known field,
          lhs_missing ++ rhs_missing )
    | _, _ =>
      Option_None
    end
  | SpecKernelExpr_Sub lhs rhs =>
    match wg_extract_scaled_missing_terms lhs values field,
          wg_extract_scaled_missing_terms rhs values field with
    | Option_Some (lhs_known, lhs_missing), Option_Some (rhs_known, rhs_missing) =>
      Option_Some
        ( wg_field_sub lhs_known rhs_known field,
          lhs_missing ++ wg_negate_missing_terms rhs_missing field )
    | _, _ =>
      Option_None
    end
  | SpecKernelExpr_Mul lhs rhs =>
    match wg_extract_known_scalar lhs values field with
    | Option_Some factor =>
      match wg_extract_scaled_missing_terms rhs values field with
      | Option_Some (known, missing) =>
        Option_Some
          ( wg_field_mul known factor field,
            wg_scale_missing_terms factor missing field )
      | Option_None =>
        Option_None
      end
    | Option_None =>
      match wg_extract_known_scalar rhs values field with
      | Option_Some factor =>
        match wg_extract_scaled_missing_terms lhs values field with
        | Option_Some (known, missing) =>
          Option_Some
            ( wg_field_mul known factor field,
              wg_scale_missing_terms factor missing field )
        | Option_None =>
          Option_None
        end
      | Option_None =>
        Option_None
      end
    end
  | SpecKernelExpr_Div _ _ =>
    Option_None
  end.

Definition wg_min_bits (lhs rhs : t_u32) : t_u32 :=
  if N.leb (U32_f_v (u32_0 lhs)) (U32_f_v (u32_0 rhs)) then
    lhs
  else
    rhs.

Fixpoint wg_signal_range_bits_constraints
  (constraints : t_Vec ((t_SpecKernelConstraint)) (t_Global))
  (signal_index : t_usize)
  (current : t_Option ((t_u32))) : t_Option ((t_u32)) :=
  match constraints with
  | [] =>
    current
  | constraint :: remaining_constraints =>
    let next :=
      match constraint with
      | SpecKernelConstraint_Boolean boolean_constraint =>
        if f_eq (SpecKernelConstraint_Boolean_f_signal boolean_constraint) signal_index then
          match current with
          | Option_Some bits =>
            Option_Some (wg_min_bits wg_u32_one bits)
          | Option_None =>
            Option_Some wg_u32_one
          end
        else
          current
      | SpecKernelConstraint_Range range_constraint =>
        if f_eq (SpecKernelConstraint_Range_f_signal range_constraint) signal_index then
          match current with
          | Option_Some bits =>
            Option_Some
              (wg_min_bits (SpecKernelConstraint_Range_f_bits range_constraint) bits)
          | Option_None =>
            Option_Some (SpecKernelConstraint_Range_f_bits range_constraint)
          end
        else
          current
      | _ =>
        current
      end in
    wg_signal_range_bits_constraints remaining_constraints signal_index next
  end.

Definition wg_signal_range_bits
  (program : t_SpecWitnessGenerationProgram)
  (signal_index : t_usize) : t_Option ((t_u32)) :=
  wg_signal_range_bits_constraints
    (SpecKernelProgram_f_constraints (f_kernel_program program))
    signal_index
    Option_None.

Definition wg_power_of_two_exponent (value : Z) : t_Option ((nat)) :=
  if Z.ltb value 1%Z then
    Option_None
  else
    let exponent := Z.log2 value in
    if Z.eqb (2 ^ exponent) value then
      Option_Some (Z.to_nat exponent)
    else
      Option_None.

Record WgDecodedTerm_record : Type :=
  {
    WgDecodedTerm_f_signal_index : t_usize;
    WgDecodedTerm_f_offset : nat;
    WgDecodedTerm_f_bits : t_u32;
  }.

Fixpoint wg_build_decoded_terms
  (program : t_SpecWitnessGenerationProgram)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (terms : t_Vec ((t_usize * t_SpecFieldValue)) (t_Global)) :
  t_Option ((t_Vec ((WgDecodedTerm_record)) (t_Global))) :=
  match terms with
  | [] =>
    Option_Some []
  | (signal_index, coeff) :: remaining_terms =>
    match wg_build_decoded_terms program values remaining_terms with
    | Option_Some decoded_terms =>
      if wg_has_value values signal_index then
        Option_Some decoded_terms
      else
        match wg_signal_range_bits program signal_index,
              wg_power_of_two_exponent (spec_field_value_to_z coeff) with
        | Option_Some bits, Option_Some offset =>
          Option_Some
            (Build_WgDecodedTerm_record signal_index offset bits :: decoded_terms)
        | _, _ =>
          Option_None
        end
    | Option_None =>
      Option_None
    end
  end.

Definition wg_term_end (term : WgDecodedTerm_record) : nat :=
  WgDecodedTerm_f_offset term + N.to_nat (U32_f_v (u32_0 (WgDecodedTerm_f_bits term))).

Definition wg_terms_disjoint (lhs rhs : WgDecodedTerm_record) : bool :=
  orb
    (Nat.leb (wg_term_end lhs) (WgDecodedTerm_f_offset rhs))
    (Nat.leb (wg_term_end rhs) (WgDecodedTerm_f_offset lhs)).

Fixpoint wg_term_disjoint_with_all
  (term : WgDecodedTerm_record)
  (remaining_terms : t_Vec ((WgDecodedTerm_record)) (t_Global)) : bool :=
  match remaining_terms with
  | [] =>
    true
  | next_term :: tail_terms =>
    andb
      (wg_terms_disjoint term next_term)
      (wg_term_disjoint_with_all term tail_terms)
  end.

Fixpoint wg_ranges_disjoint
  (terms : t_Vec ((WgDecodedTerm_record)) (t_Global)) : bool :=
  match terms with
  | [] =>
    true
  | term :: remaining_terms =>
    andb
      (wg_term_disjoint_with_all term remaining_terms)
      (wg_ranges_disjoint remaining_terms)
  end.

Fixpoint wg_decode_radix_assignments
  (target_z : Z)
  (terms : t_Vec ((WgDecodedTerm_record)) (t_Global)) :
  (t_Vec ((t_usize * t_SpecFieldValue)) (t_Global) * Z) :=
  match terms with
  | [] =>
    ([], 0%Z)
  | term :: remaining_terms =>
    let decoded := wg_decode_radix_assignments target_z remaining_terms in
    let remaining_assignments := fst decoded in
    let remaining_recomposed := snd decoded in
    let bit_count := Z.of_N (U32_f_v (u32_0 (WgDecodedTerm_f_bits term))) in
    let offset_z := Z.of_nat (WgDecodedTerm_f_offset term) in
    let mask := (2 ^ bit_count) - 1 in
    let digit_z := Z.land (Z.shiftr target_z offset_z) mask in
    let digit := spec_field_value_of_z digit_z in
    ( (WgDecodedTerm_f_signal_index term, digit) :: remaining_assignments,
      remaining_recomposed + Z.shiftl digit_z offset_z )
  end.

Definition wg_solve_radix_decomposition_side
  (program : t_SpecWitnessGenerationProgram)
  (target : t_SpecFieldValue)
  (expr : t_SpecKernelExpr)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global)) :
  t_Option ((t_Vec ((t_usize * t_SpecFieldValue)) (t_Global))) :=
  let field := SpecKernelProgram_f_field (f_kernel_program program) in
  match wg_extract_scaled_missing_terms expr values field with
  | Option_Some (known_sum, missing_terms) =>
    if Nat.ltb (List.length missing_terms) 2 then
      Option_None
    else
      match wg_build_decoded_terms program values missing_terms with
      | Option_Some decoded_terms =>
        if Nat.ltb (List.length decoded_terms) 2 then
          Option_None
        else if wg_ranges_disjoint decoded_terms then
          let target_z := spec_field_value_to_z (wg_field_sub target known_sum field) in
          let decoded := wg_decode_radix_assignments target_z decoded_terms in
          let assignments := fst decoded in
          let recomposed := snd decoded in
          if Z.eqb recomposed target_z then
            Option_Some assignments
          else
            Option_None
        else
          Option_None
      | Option_None =>
        Option_None
      end
  | Option_None =>
    Option_None
  end.

Definition wg_try_eval_expr
  (expr : t_SpecKernelExpr)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (field : t_FieldId) : t_Option ((t_SpecFieldValue)) :=
  match eval_expr expr (wg_witness_of_values values) field with
  | Result_Ok value =>
    Option_Some value
  | Result_Err _ =>
    Option_None
  end.

Definition wg_solve_radix_decomposition_equality
  (program : t_SpecWitnessGenerationProgram)
  (lhs : t_SpecKernelExpr)
  (rhs : t_SpecKernelExpr)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global)) :
  t_Option ((t_Vec ((t_usize * t_SpecFieldValue)) (t_Global))) :=
  let field := SpecKernelProgram_f_field (f_kernel_program program) in
  match wg_try_eval_expr lhs values field with
  | Option_Some target =>
    match wg_solve_radix_decomposition_side program target rhs values with
    | Option_Some assignments =>
      Option_Some assignments
    | Option_None =>
      match wg_try_eval_expr rhs values field with
      | Option_Some other_target =>
        wg_solve_radix_decomposition_side program other_target lhs values
      | Option_None =>
        Option_None
      end
    end
  | Option_None =>
    match wg_try_eval_expr rhs values field with
    | Option_Some target =>
      wg_solve_radix_decomposition_side program target lhs values
    | Option_None =>
      Option_None
    end
  end.

Definition wg_row_value_or_zero
  (row : t_Vec ((t_SpecFieldValue)) (t_Global))
  (column_index : nat) : t_SpecFieldValue :=
  match nth_error row column_index with
  | Some value =>
    value
  | None =>
    wg_zero_value
  end.

Fixpoint wg_rows_agree_on_outputs
  (lhs_row rhs_row : t_Vec ((t_SpecFieldValue)) (t_Global))
  (column_index : nat)
  (output_signal_indices : t_Vec ((t_usize)) (t_Global))
  (field : t_FieldId) : bool :=
  match output_signal_indices with
  | [] =>
    true
  | _ :: remaining_signal_indices =>
    andb
      (wg_field_eq
        (wg_row_value_or_zero lhs_row column_index)
        (wg_row_value_or_zero rhs_row column_index)
        field)
      (wg_rows_agree_on_outputs
        lhs_row
        rhs_row
        (S column_index)
        remaining_signal_indices
        field)
  end.

Fixpoint wg_find_matching_lookup_row
  (rows : t_Vec ((t_Vec ((t_SpecFieldValue)) (t_Global))) (t_Global))
  (evaluated_inputs : t_Vec ((t_SpecFieldValue)) (t_Global))
  (input_len : nat)
  (output_signal_indices : t_Vec ((t_usize)) (t_Global))
  (field : t_FieldId)
  (constraint_index : t_usize)
  (table_index : t_usize)
  (matched_row : t_Option ((t_Vec ((t_SpecFieldValue)) (t_Global)))) :
  t_Result
    ((t_Option ((t_Vec ((t_SpecFieldValue)) (t_Global)))))
    ((t_SpecWitnessGenerationError)) :=
  match rows with
  | [] =>
    Result_Ok matched_row
  | row :: remaining_rows =>
    if row_matches_inputs_from_list row evaluated_inputs field then
      match matched_row with
      | Option_Some existing_row =>
        if wg_rows_agree_on_outputs existing_row row input_len output_signal_indices field then
          wg_find_matching_lookup_row
            remaining_rows
            evaluated_inputs
            input_len
            output_signal_indices
            field
            constraint_index
            table_index
            matched_row
        else
          Result_Err
            (SpecWitnessGenerationError_AmbiguousLookup
              (Build_SpecWitnessGenerationError_AmbiguousLookup_record
                constraint_index
                table_index))
      | Option_None =>
        wg_find_matching_lookup_row
          remaining_rows
          evaluated_inputs
          input_len
          output_signal_indices
          field
          constraint_index
          table_index
          (Option_Some row)
      end
    else
      wg_find_matching_lookup_row
        remaining_rows
        evaluated_inputs
        input_len
        output_signal_indices
        field
        constraint_index
        table_index
        matched_row
  end.

Fixpoint wg_assign_lookup_outputs_from_row
  (row : t_Vec ((t_SpecFieldValue)) (t_Global))
  (signal_indices : t_Vec ((t_usize)) (t_Global))
  (column_index : nat)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (progress : bool) :
  (t_Vec (t_Option ((t_SpecFieldValue))) (t_Global) * bool) :=
  match signal_indices with
  | [] =>
    (values, progress)
  | signal_index :: remaining_signal_indices =>
    if wg_has_value values signal_index then
      wg_assign_lookup_outputs_from_row
        row
        remaining_signal_indices
        (S column_index)
        values
        progress
    else
      wg_assign_lookup_outputs_from_row
        row
        remaining_signal_indices
        (S column_index)
        (wg_set_value values signal_index (wg_row_value_or_zero row column_index))
        true
  end.

Fixpoint wg_apply_assignments
  (assignments : t_Vec ((t_usize * t_SpecFieldValue)) (t_Global))
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (progress : bool) :
  (t_Vec (t_Option ((t_SpecFieldValue))) (t_Global) * bool) :=
  match assignments with
  | [] =>
    (values, progress)
  | (signal_index, value) :: remaining_assignments =>
    if wg_has_value values signal_index then
      wg_apply_assignments remaining_assignments values progress
    else
      wg_apply_assignments
        remaining_assignments
        (wg_set_value values signal_index value)
        true
  end.

Fixpoint wg_solve_lookup_constraints
  (constraints : t_Vec ((t_SpecKernelConstraint)) (t_Global))
  (program : t_SpecWitnessGenerationProgram)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (progress : bool) :
  t_Result
    ((t_Vec (t_Option ((t_SpecFieldValue))) (t_Global) * bool))
    ((t_SpecWitnessGenerationError)) :=
  match constraints with
  | [] =>
    Result_Ok (values, progress)
  | constraint :: remaining_constraints =>
    match constraint with
    | SpecKernelConstraint_Lookup lookup_constraint =>
      match SpecKernelConstraint_Lookup_f_outputs lookup_constraint with
      | Option_Some output_signal_indices =>
        if wg_all_output_values_present values output_signal_indices then
          wg_solve_lookup_constraints remaining_constraints program values progress
        else
          let field := SpecKernelProgram_f_field (f_kernel_program program) in
          let witness := wg_witness_of_values values in
          match wg_eval_exprs
                  (SpecKernelConstraint_Lookup_f_inputs lookup_constraint)
                  witness
                  field with
          | Result_Ok evaluated_inputs =>
            match nth_error
                    (SpecKernelProgram_f_lookup_tables (f_kernel_program program))
                    (usize_to_nat (SpecKernelConstraint_Lookup_f_table_index lookup_constraint)) with
            | Some lookup_table =>
              let input_len := List.length (SpecKernelConstraint_Lookup_f_inputs lookup_constraint) in
              match wg_find_matching_lookup_row
                      (SpecKernelLookupTable_f_rows lookup_table)
                      evaluated_inputs
                      input_len
                      output_signal_indices
                      field
                      (SpecKernelConstraint_Lookup_f_index lookup_constraint)
                      (SpecKernelConstraint_Lookup_f_table_index lookup_constraint)
                      Option_None with
              | Result_Ok (Option_Some row) =>
                let assignment_result :=
                  wg_assign_lookup_outputs_from_row
                    row
                    output_signal_indices
                    input_len
                    values
                    progress in
                wg_solve_lookup_constraints
                  remaining_constraints
                  program
                  (fst assignment_result)
                  (snd assignment_result)
              | Result_Ok Option_None =>
                wg_solve_lookup_constraints remaining_constraints program values progress
              | Result_Err error =>
                Result_Err error
              end
            | None =>
              Result_Err
                (SpecWitnessGenerationError_KernelCheck
                  (SpecKernelCheckError_UnknownLookupTable
                    (Build_SpecKernelCheckError_UnknownLookupTable_record
                      (SpecKernelConstraint_Lookup_f_table_index lookup_constraint))))
            end
          | Result_Err (SpecKernelCheckError_MissingSignal _) =>
            wg_solve_lookup_constraints remaining_constraints program values progress
          | Result_Err error =>
            Result_Err (SpecWitnessGenerationError_KernelCheck error)
          end
      | Option_None =>
        wg_solve_lookup_constraints remaining_constraints program values progress
      end
    | _ =>
      wg_solve_lookup_constraints remaining_constraints program values progress
    end
  end.

Fixpoint wg_solve_radix_constraints
  (constraints : t_Vec ((t_SpecKernelConstraint)) (t_Global))
  (program : t_SpecWitnessGenerationProgram)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (progress : bool) :
  t_Result
    ((t_Vec (t_Option ((t_SpecFieldValue))) (t_Global) * bool))
    ((t_SpecWitnessGenerationError)) :=
  match constraints with
  | [] =>
    Result_Ok (values, progress)
  | constraint :: remaining_constraints =>
    match constraint with
    | SpecKernelConstraint_Equal equal_constraint =>
      match wg_solve_radix_decomposition_equality
              program
              (SpecKernelConstraint_Equal_f_lhs equal_constraint)
              (SpecKernelConstraint_Equal_f_rhs equal_constraint)
              values with
      | Option_Some assignments =>
        let assignment_result := wg_apply_assignments assignments values progress in
        wg_solve_radix_constraints
          remaining_constraints
          program
          (fst assignment_result)
          (snd assignment_result)
      | Option_None =>
        wg_solve_radix_constraints remaining_constraints program values progress
      end
    | _ =>
      wg_solve_radix_constraints remaining_constraints program values progress
    end
  end.

Fixpoint wg_solve_affine_constraints
  (constraints : t_Vec ((t_SpecKernelConstraint)) (t_Global))
  (program : t_SpecWitnessGenerationProgram)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (progress : bool) :
  t_Result
    ((t_Vec (t_Option ((t_SpecFieldValue))) (t_Global) * bool))
    ((t_SpecWitnessGenerationError)) :=
  match constraints with
  | [] =>
    Result_Ok (values, progress)
  | constraint :: remaining_constraints =>
    match constraint with
    | SpecKernelConstraint_Equal equal_constraint =>
      let field := SpecKernelProgram_f_field (f_kernel_program program) in
      match wg_solve_single_missing_equality
              (SpecKernelConstraint_Equal_f_lhs equal_constraint)
              (SpecKernelConstraint_Equal_f_rhs equal_constraint)
              values
              field with
      | Option_Some (signal_index, value) =>
        if wg_has_value values signal_index then
          wg_solve_affine_constraints remaining_constraints program values progress
        else
          wg_solve_affine_constraints
            remaining_constraints
            program
            (wg_set_value values signal_index value)
            true
      | Option_None =>
        wg_solve_affine_constraints remaining_constraints program values progress
      end
    | _ =>
      wg_solve_affine_constraints remaining_constraints program values progress
    end
  end.

Fixpoint wg_solve_loop
  (fuel : nat)
  (program : t_SpecWitnessGenerationProgram)
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global)) :
  t_Result
    ((t_Vec (t_Option ((t_SpecFieldValue))) (t_Global)))
    ((t_SpecWitnessGenerationError)) :=
  match fuel with
  | O =>
    Result_Ok values
  | S remaining_fuel =>
    match wg_solve_lookup_constraints
            (SpecKernelProgram_f_constraints (f_kernel_program program))
            program
            values
            false with
    | Result_Ok (lookup_values, lookup_progress) =>
      match wg_solve_radix_constraints
              (SpecKernelProgram_f_constraints (f_kernel_program program))
              program
              lookup_values
              lookup_progress with
      | Result_Ok (radix_values, radix_progress) =>
        match wg_solve_affine_constraints
                (SpecKernelProgram_f_constraints (f_kernel_program program))
                program
                radix_values
                radix_progress with
        | Result_Ok (next_values, next_progress) =>
          if next_progress then
            wg_solve_loop remaining_fuel program next_values
          else
            Result_Ok next_values
        | Result_Err error =>
          Result_Err error
        end
      | Result_Err error =>
        Result_Err error
      end
    | Result_Err error =>
      Result_Err error
    end
  end.

Fixpoint wg_collect_unresolved_required_signals
  (signals : t_Vec ((t_SpecWitnessSignal)) (t_Global))
  (values : t_Vec (t_Option ((t_SpecFieldValue))) (t_Global))
  (next_index : nat) :
  t_Vec ((t_usize)) (t_Global) :=
  match signals with
  | [] =>
    []
  | signal :: remaining_signals =>
    let remaining_indices :=
      wg_collect_unresolved_required_signals
        remaining_signals
        values
        (S next_index) in
    if andb
         (SpecWitnessSignal_f_required signal)
         (negb (wg_has_value values (n_to_usize (N.of_nat next_index)))) then
      n_to_usize (N.of_nat next_index) :: remaining_indices
    else
      remaining_indices
  end.

Definition generate_non_blackbox_witness_unchecked_runtime
  (program : t_SpecWitnessGenerationProgram)
  (inputs : t_Slice (t_Option ((t_SpecFieldValue)))) :
  t_Result ((t_SpecKernelWitness)) ((t_SpecWitnessGenerationError)) :=
  let seeded_values := wg_seed_signal_values (f_signals program) in
  let input_values := wg_apply_inputs seeded_values (Slice_f_v inputs) in
  match wg_solve_loop (S (List.length (f_signals program))) program input_values with
  | Result_Ok solved_values =>
    let unresolved_signal_indices :=
      wg_collect_unresolved_required_signals
        (f_signals program)
        solved_values
        O in
    match unresolved_signal_indices with
    | [] =>
      Result_Ok (wg_witness_of_values solved_values)
    | _ =>
      Result_Err
        (SpecWitnessGenerationError_UnsupportedWitnessSolve
          (Build_SpecWitnessGenerationError_UnsupportedWitnessSolve_record
            unresolved_signal_indices))
    end
  | Result_Err error =>
    Result_Err error
  end.

Definition generate_non_blackbox_witness_unchecked (program : t_SpecWitnessGenerationProgram) (inputs : t_Slice (t_Option ((t_SpecFieldValue)))) : t_Result ((t_SpecKernelWitness)) ((t_SpecWitnessGenerationError)) :=
  generate_non_blackbox_witness_unchecked_runtime (program) (inputs).

Definition validate_generated_witness (program : t_SpecWitnessGenerationProgram) (witness : t_SpecKernelWitness) : t_Result ((t_SpecKernelWitness)) ((t_SpecWitnessGenerationError)) :=
  match check_program (f_kernel_program program) (witness) with
  | Result_Ok tt =>
    Result_Ok (witness)
  | Result_Err (error) =>
    Result_Err (SpecWitnessGenerationError_KernelCheck (error))
  end.

Definition generate_non_blackbox_witness (program : t_SpecWitnessGenerationProgram) (inputs : t_Slice (t_Option ((t_SpecFieldValue)))) : t_Result ((t_SpecKernelWitness)) ((t_SpecWitnessGenerationError)) :=
  match generate_non_blackbox_witness_unchecked (program) (inputs) with
  | Result_Ok (witness) =>
    validate_generated_witness (program) (witness)
  | Result_Err (error) =>
    Result_Err (error)
  end.
