/* libzkf_ffi — C-compatible FFI for ZKF. Generated by cbindgen — do not edit. */

#ifndef ZKF_FFI_H
#define ZKF_FFI_H

/* WARNING: this file is auto-generated by cbindgen. Do not modify manually. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * ABI version for the FFI interface. Bump this whenever:
 * - A function signature changes (parameter types, return types)
 * - A function is removed
 * - Struct layouts change (#[repr(C)] structs)
 *
 * Minor bumps (e.g., 1 → 2) for additive changes (new functions).
 * Major bumps (e.g., 1 → 100) for breaking changes.
 */
#define ZKF_FFI_ABI_VERSION 3

/**
 * Universal FFI result. Returned by every zkf_* function.
 * Caller MUST free with `zkf_free_result`.
 */
typedef struct ZkfFfiResult {
  /**
   * 0 = success, 1 = application error, 2 = panic/internal error
   */
  int32_t status;
  /**
   * JSON-encoded result data (null on error). Freed by `zkf_free_result`.
   */
  char *data;
  /**
   * Error message (null on success). Freed by `zkf_free_result`.
   */
  char *error;
} ZkfFfiResult;

/**
 * Free a `ZkfFfiResult` and its string fields.
 */
void zkf_free_result(struct ZkfFfiResult *ptr);

/**
 * Free a C string allocated by the FFI layer.
 */
void zkf_free_string(char *ptr);

/**
 * Request cancellation of the currently-running FFI operation.
 */
void zkf_request_cancel(void);

/**
 * Clear the cancellation flag (call before starting a new operation).
 */
void zkf_clear_cancel(void);

/**
 * Check if cancellation has been requested.
 */
int32_t zkf_is_cancelled(void);

/**
 * Return the FFI ABI version as a plain integer.
 * Swift should call this at startup and compare against its expected version.
 * If mismatched, refuse to call other FFI functions.
 */
uint32_t zkf_ffi_abi_version(void);

/**
 * Check if the ZKF library is available and return version info.
 */
struct ZkfFfiResult *zkf_check_available(void);

/**
 * Return system capabilities: available backends, frontends, fields.
 */
struct ZkfFfiResult *zkf_capabilities(void);

/**
 * Run system doctor — check tooling dependencies.
 */
struct ZkfFfiResult *zkf_doctor(void);

/**
 * Return Metal GPU status.
 */
struct ZkfFfiResult *zkf_metal_doctor(void);

/**
 * Return the detected Apple platform capability snapshot.
 */
struct ZkfFfiResult *zkf_platform_capability(void);

/**
 * Return Neural Engine/control-plane status for the current host.
 */
struct ZkfFfiResult *zkf_neural_engine_status(void);

/**
 * Evaluate the control plane from a JSON request payload.
 */
struct ZkfFfiResult *zkf_evaluate_control_plane(const char *request_json);

/**
 * Create a watchdog handle for later alert polling.
 */
struct ZkfFfiResult *zkf_watchdog_create(int32_t deterministic_mode);

/**
 * Poll alerts for a previously-created watchdog handle.
 */
struct ZkfFfiResult *zkf_watchdog_check_alerts(uint64_t watchdog_id);

/**
 * Destroy a watchdog handle.
 */
struct ZkfFfiResult *zkf_watchdog_destroy(uint64_t watchdog_id);

/**
 * Return adaptive tuning status.
 */
struct ZkfFfiResult *zkf_adaptive_tuning_status(void);

/**
 * Summarize the telemetry corpus used for retraining and freshness checks.
 */
struct ZkfFfiResult *zkf_telemetry_stats(const char *dir);

/**
 * List all available frontends and their capabilities.
 */
struct ZkfFfiResult *zkf_frontends(void);

/**
 * Compile an IR program for a specific backend.
 */
struct ZkfFfiResult *zkf_compile(const char *program_path,
                                 const char *backend,
                                 const char *output_path,
                                 const char *seed);

/**
 * Generate a witness from a program and inputs.
 */
struct ZkfFfiResult *zkf_witness(const char *program_path,
                                 const char *inputs_path,
                                 const char *output_path);

/**
 * Optimize an IR program (constant folding, dedup, dead signal elimination).
 */
struct ZkfFfiResult *zkf_optimize(const char *program_path, const char *output_path);

/**
 * Debug a circuit: constraint traces, under-constrained detection, symbolic analysis.
 */
struct ZkfFfiResult *zkf_debug(const char *program_path,
                               const char *witness_path,
                               const char *output_path,
                               int32_t continue_on_failure);

/**
 * Compile, generate witness, and prove a circuit in one step.
 */
struct ZkfFfiResult *zkf_prove(const char *program_path,
                               const char *inputs_path,
                               const char *backend,
                               const char *output_path,
                               const char *compiled_out,
                               const char *solver,
                               int32_t no_metal,
                               int32_t low_memory);

/**
 * Verify a proof artifact.
 */
struct ZkfFfiResult *zkf_verify(const char *proof_path, const char *backend);

/**
 * Estimate Ethereum verification gas cost for a proof.
 */
struct ZkfFfiResult *zkf_estimate_gas(const char *proof_path, const char *backend);

/**
 * Estimate verification gas cost for a proof against a specific EVM target.
 */
struct ZkfFfiResult *zkf_estimate_gas_for_target(const char *proof_path,
                                                 const char *backend,
                                                 const char *evm_target);

/**
 * Generate a Solidity verifier contract from a proof.
 */
struct ZkfFfiResult *zkf_deploy(const char *proof_path,
                                const char *backend,
                                const char *output_path,
                                const char *contract_name);

/**
 * Generate a Solidity verifier contract from a proof for a specific EVM target.
 */
struct ZkfFfiResult *zkf_deploy_for_target(const char *proof_path,
                                           const char *backend,
                                           const char *output_path,
                                           const char *contract_name,
                                           const char *evm_target);

/**
 * Decode a Groth16 proof into Solidity-ready calldata coordinates (JSON).
 */
struct ZkfFfiResult *zkf_proof_calldata(const char *proof_path);

/**
 * Generate a Foundry test file for behavioral verification of a Groth16 verifier.
 */
struct ZkfFfiResult *zkf_emit_foundry_test(const char *proof_path,
                                           const char *verifier_import_path,
                                           const char *test_output_path,
                                           const char *contract_name);

/**
 * Inspect a proof artifact: proof size, public inputs, VK hash, internal structure.
 */
struct ZkfFfiResult *zkf_explore(const char *artifact_path, const char *backend);

/**
 * Emit a canonical test circuit (example.ir.json).
 */
struct ZkfFfiResult *zkf_emit_example(const char *output_path);

/**
 * Import a circuit from a frontend into ZKF IR format.
 */
struct ZkfFfiResult *zkf_import(const char *frontend,
                                const char *input_path,
                                const char *output_path,
                                const char *field);

/**
 * Import a circuit from a frontend into either canonical `zir-v1` or lowered `ir-v2`.
 */
struct ZkfFfiResult *zkf_import_with_options(const char *frontend,
                                             const char *input_path,
                                             const char *output_path,
                                             const char *field,
                                             const char *ir_family);

/**
 * Inspect a frontend artifact: opcode census, compatible backends, capability hints.
 */
struct ZkfFfiResult *zkf_inspect(const char *frontend, const char *artifact_path);

/**
 * Benchmark across multiple backends.
 */
struct ZkfFfiResult *zkf_benchmark(const char *backends_json,
                                   int32_t iterations,
                                   int32_t parallel,
                                   int32_t continue_on_error);

/**
 * Wrap a STARK proof into a Groth16 proof for on-chain verification.
 */
struct ZkfFfiResult *zkf_wrap(const char *proof_path,
                              const char *compiled_path,
                              const char *output_path,
                              int32_t low_memory);

/**
 * Pre-generate Groth16 keys for STARK→Groth16 wrapping.
 */
struct ZkfFfiResult *zkf_wrap_setup(const char *proof_path, const char *compiled_path);

/**
 * Aggregate multiple proofs into one.
 *
 * `pairs_json` is a JSON array of objects: `[{"proof": "<path>", "compiled": "<path>"}, ...]`
 */
struct ZkfFfiResult *zkf_aggregate(const char *pairs_json,
                                   const char *mode,
                                   const char *output_path);

/**
 * Run test vectors against a circuit across backends.
 */
struct ZkfFfiResult *zkf_test_vectors(const char *program_path,
                                      const char *vectors_path,
                                      const char *backends_json);

/**
 * Run the built-in demo pipeline.
 */
struct ZkfFfiResult *zkf_demo(void);

/**
 * List all gadgets in the ZKF registry.
 */
struct ZkfFfiResult *zkf_registry_list(void);

/**
 * Fetch/install a gadget from the registry.
 */
struct ZkfFfiResult *zkf_registry_add(const char *gadget_name);

/**
 * Publish a gadget to the registry.
 */
struct ZkfFfiResult *zkf_registry_publish(const char *manifest_path, const char *content_path);

/**
 * Compile a package manifest for a specific backend.
 */
struct ZkfFfiResult *zkf_package_compile(const char *manifest_path, const char *backend);

/**
 * Prove a package run for a specific backend.
 */
struct ZkfFfiResult *zkf_package_prove(const char *manifest_path,
                                       const char *backend,
                                       const char *run_id);

/**
 * Run the conformance test suite against a backend.
 * Returns JSON: ConformanceReport with per-test pass/fail, timing, and errors.
 */
struct ZkfFfiResult *zkf_conformance(const char *backend);

/**
 * Run the conformance suite and export standalone JSON and/or CBOR artifacts.
 */
struct ZkfFfiResult *zkf_conformance_export(const char *backend,
                                            const char *json_path,
                                            const char *cbor_path);

/**
 * Validate a ZKF program: schema parsing + type checking.
 * Accepts both ZIR v1 and IR v2 formats.
 * Returns JSON: { valid, program, name, field, ir_format, signals, constraints, type_errors }
 */
struct ZkfFfiResult *zkf_ir_validate(const char *program_path);

/**
 * Initialize a new Powers of Tau ceremony.
 * Returns JSON: { power, n_g1, n_g2, output_path }
 */
struct ZkfFfiResult *zkf_ceremony_init(const char *curve, int32_t power, const char *output_path);

/**
 * Add a contribution to a Powers of Tau ceremony.
 * Returns JSON: { hash, contributions, output_path }
 */
struct ZkfFfiResult *zkf_ceremony_contribute(const char *input_ptau,
                                             const char *output_ptau,
                                             const char *entropy,
                                             const char *name);

/**
 * Apply a random beacon as the final contribution.
 * Returns JSON: { hash, contributions, output_path }
 */
struct ZkfFfiResult *zkf_ceremony_beacon(const char *input_ptau,
                                         const char *output_ptau,
                                         const char *beacon_hex,
                                         int32_t hash_iterations);

/**
 * Prepare a Phase 1 ptau for Phase 2 (currently a pass-through verify + copy).
 * In practice, Hermez ptau files are already Phase 1 ready; this just validates.
 * Returns JSON: { valid, power, contributions, output_path }
 */
struct ZkfFfiResult *zkf_ceremony_prepare_phase2(const char *input_ptau, const char *output_path);

/**
 * Verify the consistency of a .ptau file.
 * Returns JSON: { valid, power, contributions, checks: { ... } }
 */
struct ZkfFfiResult *zkf_ceremony_verify(const char *ptau_path);

/**
 * Phase 2: derive circuit-specific keys from a Phase 1 SRS.
 * Uses the ptau + program to derive a ceremony-bound setup seed, then runs
 * the normal Groth16 circuit_specific_setup with that seed.
 * Returns JSON: { output_path, seed_hex, power }
 */
struct ZkfFfiResult *zkf_ceremony_setup(const char *ptau_path,
                                        const char *program_path,
                                        const char *backend,
                                        const char *output_path);

/**
 * Phase 2 contribution to a circuit-specific zkey.
 */
struct ZkfFfiResult *zkf_ceremony_contribute_phase2(const char *input_zkey,
                                                    const char *output_zkey,
                                                    const char *entropy,
                                                    const char *name);

/**
 * Verify Phase 2 circuit-specific keys against the Phase 1 SRS and program.
 */
struct ZkfFfiResult *zkf_ceremony_verify_phase2(const char *zkey_path,
                                                const char *ptau_path,
                                                const char *program_path);

/**
 * Export a verification key from a ceremony-derived compiled program.
 * Returns JSON: { output_path, vk_size }
 */
struct ZkfFfiResult *zkf_ceremony_export_vk(const char *zkey_path, const char *output_path);

/**
 * Prove using a ceremony-derived key (zkey).
 * Reads the compiled program from zkey_path and the witness inputs from inputs_path,
 * then produces a proof.
 * Returns JSON: the proof artifact.
 */
struct ZkfFfiResult *zkf_prove_with_ceremony(const char *zkey_path,
                                             const char *inputs_path,
                                             const char *output_path,
                                             int32_t no_metal);

/**
 * Return the full backend capability matrix as JSON.
 */
struct ZkfFfiResult *zkf_capability_matrix(void);

/**
 * Detect system resources and return recommendations as JSON.
 *
 * @return JSON: { system: SystemResources, recommendation: ResourceRecommendation }
 */
struct ZkfFfiResult *zkf_system_resources(void);

/**
 * Normalize a ZIR program to canonical form.
 *
 * Applies algebraic rewrites, constant folding, dead signal elimination,
 * and deterministic constraint ordering. Idempotent.
 *
 * @param program_path  path to the ZIR program JSON (required)
 * @param output_path   path for the normalized output (required)
 * @return JSON: NormalizationReport with pass statistics and digests
 */
struct ZkfFfiResult *zkf_normalize(const char *program_path, const char *output_path);

/**
 * Type-check a ZIR program.
 *
 * Verifies signal types, constraint compatibility, and blackbox op signatures.
 *
 * @param program_path  path to the ZIR program JSON (required)
 * @return JSON: { "valid": bool, "errors": [...] }
 */
struct ZkfFfiResult *zkf_type_check(const char *program_path);

/**
 * Run a machine-verifiable audit on a ZIR program and return a JSON report.
 *
 * @param program_path  path to the ZIR program JSON (required)
 * @param backend       backend name (optional, e.g. "arkworks-groth16")
 * @return JSON: full AuditReport with checks, findings, and summary
 */
struct ZkfFfiResult *zkf_audit_report(const char *program_path, const char *backend);

/**
 * Return provenance lineage for an artifact.
 *
 * Reads the JSON file at `artifact_path` and attempts to parse it as a
 * `ZkfArtifactBundle`. If successful, returns the full provenance chain.
 * Falls back to `ProofArtifact` or `CompiledProgram` parsing, and finally
 * returns basic file info (existence, size, computed digest) for unknown formats.
 */
struct ZkfFfiResult *zkf_artifact_lineage(const char *artifact_path);

/**
 * Run semantic equivalence test across backends.
 *
 * Reads the program and inputs files, parses `backends_json` as a JSON array
 * of backend name strings, and runs compile/prove/verify for each backend.
 * Returns a JSON result with per-backend status and cross-backend public input
 * comparison.
 */
struct ZkfFfiResult *zkf_equivalence_test(const char *program_path,
                                          const char *inputs_path,
                                          const char *backends_json);

#endif  /* ZKF_FFI_H */
