(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.
Require Import KernelCompat.

(* NotImplementedYet *)

Inductive t_ProofEmbeddedFieldId : Type :=
| ProofEmbeddedFieldId_Bn254
| ProofEmbeddedFieldId_Bls12_381_
| ProofEmbeddedFieldId_PastaFp
| ProofEmbeddedFieldId_PastaFq
| ProofEmbeddedFieldId_Goldilocks
| ProofEmbeddedFieldId_BabyBear
| ProofEmbeddedFieldId_Mersenne31.








Inductive t_ProofEmbeddedBackendKind : Type :=
| ProofEmbeddedBackendKind_ArkworksGroth16
| ProofEmbeddedBackendKind_Plonky3
| ProofEmbeddedBackendKind_Halo2
| ProofEmbeddedBackendKind_Halo2Bls12381.





Definition canonical_input_key_string (requested : t_String) (alias_target : t_Option ((t_String))) : t_String :=
  impl__unwrap_or (alias_target) (requested).

Record ProgramMismatchFields_record : Type :=
  {
    ProgramMismatchFields_f_expected : t_String;
    ProgramMismatchFields_f_found : t_String;
  }.
Definition t_ProgramMismatchFields := ProgramMismatchFields_record.



#[export] Instance settable_ProgramMismatchFields_record : Settable _ :=
  settable! (Build_ProgramMismatchFields_record) <ProgramMismatchFields_f_expected; ProgramMismatchFields_f_found>.
Definition ProgramMismatchFields := Build_ProgramMismatchFields_record.
Notation f_expected := ProgramMismatchFields_f_expected.
Notation t_ProgramMismatchFieldsf_expected := ProgramMismatchFields_f_expected.
Notation f_found := ProgramMismatchFields_f_found.
Notation t_ProgramMismatchFieldsf_found := ProgramMismatchFields_f_found.

Definition program_mismatch_fields (expected : t_String) (found : t_String) : t_ProgramMismatchFields :=
  ProgramMismatchFields (expected) (found).

Definition default_backend_for_proof_field_spec (field : t_ProofEmbeddedFieldId) : t_ProofEmbeddedBackendKind :=
  match field with
  | ProofEmbeddedFieldId_Bn254 =>
    ProofEmbeddedBackendKind_ArkworksGroth16
  | ProofEmbeddedFieldId_Bls12_381_ =>
    ProofEmbeddedBackendKind_Halo2Bls12381
  | ProofEmbeddedFieldId_PastaFp
  | ProofEmbeddedFieldId_PastaFq =>
    ProofEmbeddedBackendKind_Halo2
  | ProofEmbeddedFieldId_Goldilocks
  | ProofEmbeddedFieldId_BabyBear
  | ProofEmbeddedFieldId_Mersenne31 =>
    ProofEmbeddedBackendKind_Plonky3
  end.

Definition private_identity_merkle_direction_is_binary (direction : t_u8) : bool :=
  orb
    (N.eqb (U8_f_v (u8_0 direction)) 0%N)
    (N.eqb (U8_f_v (u8_0 direction)) 1%N).

Definition private_identity_expected_public_input_arity '(_ : unit) : t_usize :=
  (5 : t_usize).

Definition private_identity_public_input_arity_is_expected (len : t_usize) : bool :=
  f_eq (len) (private_identity_expected_public_input_arity (tt)).

Fixpoint digest_bytes_match_lists (expected : list t_u8) (found : list t_u8) : bool :=
  match expected, found with
  | [], [] =>
    (true : bool)
  | expected_head :: expected_tail, found_head :: found_tail =>
    andb
      (N.eqb (U8_f_v (u8_0 expected_head)) (U8_f_v (u8_0 found_head)))
      (digest_bytes_match_lists expected_tail found_tail)
  | _, _ =>
    (false : bool)
  end.

Definition digest_bytes_match_slices (expected : t_Slice t_u8) (found : t_Slice t_u8) : bool :=
  digest_bytes_match_lists (Slice_f_v expected) (Slice_f_v found).

Definition digest_bytes_match (expected : t_Vec ((t_u8)) ((t_Global))) (found : t_Vec ((t_u8)) ((t_Global))) : bool :=
  digest_bytes_match_lists expected found.

Definition program_digests_match (expected : t_String) (found : t_String) : bool :=
  String.eqb expected found.

Definition program_digest_guard_accepts (expected : t_String) (found : t_String) : bool :=
  program_digests_match (expected) (found).
