#!/usr/bin/env python3

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT_DIR = ROOT / "zkf-ir-spec" / "protocol-parameters"
LEAN_DIR = ROOT / "zkf-protocol-proofs" / "ZkfProtocolProofs"


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def extract_plonky3_pin(cargo_toml: str) -> str:
    matches = re.findall(r'^p3-[^=]+ = "=(.+)"$', cargo_toml, flags=re.MULTILINE)
    if not matches:
        raise RuntimeError("failed to find pinned Plonky3 workspace dependencies")
    versions = sorted(set(matches))
    if len(versions) != 1:
        raise RuntimeError(f"expected one Plonky3 pin, found {versions}")
    return versions[0]


def extract_u8_const(source: str, name: str) -> int:
    match = re.search(rf"const\s+{re.escape(name)}:\s*u8\s*=\s*(\d+);", source)
    if not match:
        raise RuntimeError(f"failed to find u8 const {name}")
    return int(match.group(1))


def extract_str_const(source: str, name: str) -> str:
    match = re.search(rf'const\s+{re.escape(name)}:\s*&str\s*=\s*"([^"]+)";', source)
    if not match:
        raise RuntimeError(f"failed to find string const {name}")
    return match.group(1)


def rust_file_snapshot(path: str) -> dict[str, str]:
    resolved = ROOT / path
    return {"path": path, "sha256": sha256_file(resolved)}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(message)


def canonical_json(payload: dict) -> str:
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def write_or_check(path: Path, expected: str, check: bool) -> None:
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    if check:
        require(
            actual == expected,
            f"{path} is out of sync; run scripts/generate_protocol_parameter_snapshots.py",
        )
        return
    path.write_text(expected, encoding="utf-8")


def emit_json(path: Path, payload: dict, check: bool) -> None:
    write_or_check(path, canonical_json(payload), check)


def lean_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f"\"{escaped}\""


def lean_file_list(entries: list[dict[str, str]]) -> str:
    rendered = []
    for entry in entries:
        rendered.append(
            "  { path := "
            + lean_string(entry["path"])
            + ", sha256 := "
            + lean_string(entry["sha256"])
            + " }"
        )
    return "[\n" + ",\n".join(rendered) + "\n]"


def render_generated_snapshots_lean(
    groth16: dict,
    fri: dict,
    nova: dict,
) -> str:
    return f"""import ZkfProtocolProofs.Common

namespace ZkfProtocolProofs

/-- Generated by `scripts/generate_protocol_parameter_snapshots.py`. -/
def groth16Snapshot : Groth16SurfaceSnapshot := {{
  surface := {lean_string(groth16["surface"])},
  backend := {lean_string(groth16["backend"])},
  field := {lean_string(groth16["field"])},
  curve := {lean_string(groth16["curve"])},
  scheme := {lean_string(groth16["scheme"])},
  setupBlobVersion := {groth16["setup_blob_version"]},
  setupProvenance := {lean_string(groth16["setup_provenance"])},
  securityBoundary := {lean_string(groth16["security_boundary"])},
  developmentBoundary := {lean_string(groth16["development_boundary"])},
  requiredCompiledMetadata := [{", ".join(lean_string(value) for value in groth16["required_compiled_metadata"])}],
  requiredProofMetadata := [{", ".join(lean_string(value) for value in groth16["required_proof_metadata"])}],
  verifierChecks := [{", ".join(lean_string(value) for value in groth16["verifier_checks"])}],
  rustFiles := {lean_file_list(groth16["rust_files"])}
}}

/-- Generated by `scripts/generate_protocol_parameter_snapshots.py`. -/
def friSnapshot : FriSurfaceSnapshot := {{
  surface := {lean_string(fri["surface"])},
  backend := {lean_string(fri["backend"])},
  scheme := {lean_string(fri["scheme"])},
  pcs := {lean_string(fri["pcs"])},
  plonky3Version := {lean_string(fri["plonky3_version"])},
  seedDerivation := {lean_string(fri["seed_derivation"])},
  wrapperSurface := {lean_string(fri["wrapper_surface"])},
  wrapperStatuses := [{", ".join(lean_string(value) for value in fri["wrapper_statuses"])}],
  wrapperStrategies := [{", ".join(lean_string(value) for value in fri["wrapper_strategies"])}],
  wrapperSemantics := [{", ".join(lean_string(value) for value in fri["wrapper_semantics"])}],
  sourceVerificationSemantics := [{", ".join(lean_string(value) for value in fri["source_verification_semantics"])}],
  requiredProofMetadata := [{", ".join(lean_string(value) for value in fri["required_proof_metadata"])}],
  rustFiles := {lean_file_list(fri["rust_files"])}
}}

/-- Generated by `scripts/generate_protocol_parameter_snapshots.py`. -/
def novaSnapshot : NovaSurfaceSnapshot := {{
  surface := {lean_string(nova["surface"])},
  backend := {lean_string(nova["backend"])},
  compileScheme := {lean_string(nova["compile_scheme"])},
  foldScheme := {lean_string(nova["fold_scheme"])},
  nativeMode := {lean_string(nova["native_mode"])},
  profiles := [{", ".join(lean_string(value) for value in nova["profiles"])}],
  primaryCurve := {lean_string(nova["primary_curve"])},
  secondaryCurve := {lean_string(nova["secondary_curve"])},
  curveCycle := {lean_string(nova["curve_cycle"])},
  stepArity := {nova["step_arity"]},
  compressedFoldSupportedProfiles := [{", ".join(lean_string(value) for value in nova["compressed_fold_supported_profiles"])}],
  requiredCompiledMetadata := [{", ".join(lean_string(value) for value in nova["required_compiled_metadata"])}],
  requiredSingleStepProofMetadata := [{", ".join(lean_string(value) for value in nova["required_single_step_proof_metadata"])}],
  requiredFoldProofMetadata := [{", ".join(lean_string(value) for value in nova["required_fold_proof_metadata"])}],
  rustFiles := {lean_file_list(nova["rust_files"])}
}}

end ZkfProtocolProofs
"""


def emit_generated_snapshots_lean(
    groth16: dict,
    fri: dict,
    nova: dict,
    check: bool,
) -> None:
    write_or_check(
        LEAN_DIR / "GeneratedSnapshots.lean",
        render_generated_snapshots_lean(groth16, fri, nova),
        check,
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate or verify protocol parameter snapshots."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in snapshot files differ from the live repo state",
    )
    args = parser.parse_args()

    SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)
    LEAN_DIR.mkdir(parents=True, exist_ok=True)

    cargo_toml = (ROOT / "Cargo.toml").read_text(encoding="utf-8")
    plonky3_pin = extract_plonky3_pin(cargo_toml)
    arkworks_rs = (ROOT / "zkf-backends" / "src" / "arkworks.rs").read_text(encoding="utf-8")
    nova_rs = (ROOT / "zkf-backends" / "src" / "nova_native.rs").read_text(encoding="utf-8")
    setup_blob_version = extract_u8_const(arkworks_rs, "SETUP_BLOB_VERSION")
    nova_native_mode = extract_str_const(nova_rs, "NOVA_NATIVE_MODE")

    groth16 = {
        "surface": "groth16",
        "backend": "arkworks-groth16",
        "field": "bn254",
        "curve": "bn254",
        "scheme": "groth16",
        "setup_blob_version": setup_blob_version,
        "setup_provenance": "trusted-imported-blob",
        "security_boundary": "trusted-imported",
        "development_boundary": "development-only",
        "required_compiled_metadata": [
            "curve",
            "scheme",
            "setup_blob_version",
            "setup_deterministic",
            "setup_seed_source",
            "groth16_setup_provenance",
            "groth16_setup_security_boundary",
            "groth16_setup_blob_path",
        ],
        "required_proof_metadata": [
            "curve",
            "scheme",
            "prove_deterministic",
            "prove_seed_source",
        ],
        "verifier_checks": [
            "compiled_backend_matches",
            "artifact_backend_matches",
            "program_digest_matches",
            "verification_key_matches_compiled_setup_blob",
        ],
        "rust_files": [
            rust_file_snapshot("zkf-backends/src/arkworks.rs"),
            rust_file_snapshot("zkf-backends/src/lib_non_hax.rs"),
        ],
    }
    fri = {
        "surface": "fri",
        "backend": "plonky3",
        "scheme": "stark",
        "pcs": "fri",
        "plonky3_version": plonky3_pin,
        "seed_derivation": "program-digest",
        "wrapper_surface": "stark-to-groth16",
        "wrapper_statuses": ["wrapped-v2", "wrapped-v3"],
        "wrapper_strategies": ["direct-fri-v2", "nova-compressed-v3"],
        "wrapper_semantics": [
            "fri-verifier-circuit",
            "nova-compressed-attestation-binding",
        ],
        "source_verification_semantics": [
            "circuit-replayed",
            "host-compressed-check",
        ],
        "required_proof_metadata": [
            "field",
            "scheme",
            "pcs",
            "seed",
        ],
        "rust_files": [
            rust_file_snapshot("zkf-backends/src/plonky3.rs"),
            rust_file_snapshot("zkf-backends/src/wrapping/stark_to_groth16.rs"),
        ],
    }
    nova = {
        "surface": "nova-hypernova",
        "backend": "nova-native",
        "compile_scheme": "nova-ivc",
        "fold_scheme": "nova-ivc-fold",
        "native_mode": nova_native_mode,
        "profiles": ["classic", "hypernova"],
        "primary_curve": "pallas",
        "secondary_curve": "vesta",
        "curve_cycle": "pallas-vesta",
        "step_arity": 1,
        "compressed_fold_supported_profiles": ["classic"],
        "required_compiled_metadata": [
            "nova_native_mode",
            "nova_profile",
            "nova_curve_cycle",
            "nova_step_arity",
            "scheme",
            "mode",
        ],
        "required_single_step_proof_metadata": [
            "nova_native_mode",
            "nova_steps",
            "nova_curve_cycle",
            "nova_profile",
        ],
        "required_fold_proof_metadata": [
            "nova_native_mode",
            "nova_steps",
            "nova_curve_cycle",
            "nova_profile",
            "nova_compressed",
            "nova_ivc_in",
            "nova_ivc_out",
            "nova_ivc_initial_state",
            "nova_ivc_final_state",
        ],
        "rust_files": [
            rust_file_snapshot("zkf-backends/src/nova_native.rs"),
        ],
    }

    emit_json(SNAPSHOT_DIR / "groth16_surface.json", groth16, args.check)
    emit_json(SNAPSHOT_DIR / "fri_surface.json", fri, args.check)
    emit_json(SNAPSHOT_DIR / "nova_surface.json", nova, args.check)
    emit_generated_snapshots_lean(groth16, fri, nova, args.check)


if __name__ == "__main__":
    main()
