// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;
import "../src/HazardAssessmentVerifier.sol";

/// @title HazardAssessmentVerifierTest
/// @notice Auto-generated Foundry test for Groth16 verifier behavioral correctness.
/// @dev Generated by ZKF. The suite locks valid verification plus fail-closed
///      rejection for tampering, wrong public inputs, wrong arity, and field overflow.
contract HazardAssessmentVerifierTest {
    uint256 internal constant SNARK_SCALAR_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;
    HazardAssessmentVerifier verifier;

    function assertTrue(bool condition, string memory message) internal pure {
        require(condition, message);
    }

    function assertFalse(bool condition, string memory message) internal pure {
        require(!condition, message);
    }

    function setUp() public {
        verifier = new HazardAssessmentVerifier();
    }

    function proofFixture()
        internal
        pure
        returns (uint[2] memory a, uint[2][2] memory b, uint[2] memory c)
    {
        a = [
            uint256(0x17adbc59cb371aebb52b371164499a15d42ac2e7062aa70611ce2b4aa0ec2bb8),
            uint256(0x1f3e85cf46074dc42e5100427573853a79ee4266d6d8162af9585fae840c27a0)
        ];
        b = [
            [uint256(0x2d6e7f1b7253724967335f3abeae49cf15eb65dda9f461d0e9094532cdc1aac5), uint256(0x2e4e11be4ef70076e61db6a8d458b4320bfeb8f6643cfdf6424f006044949e1f)],
            [uint256(0x0d84aafe8ebd975dcb80cc5f00fa76e239347de9b5894927b941ca3ea6f88dd9), uint256(0x095930aa1a72eeaba677d1a9f7d76bd33d8b1a112f4d123cdae317f4303914c2)]
        ];
        c = [
            uint256(0x0b4d769fe9b60488ad70ab3d51cf024dca6439d7dfe8caa3829def3990b2c657),
            uint256(0x1ffa9761cc41abf0f1b9d7f99b598ba26cbbb2cc6f6c95e2abea72a2d0f1c0bb)
        ];
    }

    function validInputFixture() internal pure returns (uint[] memory) {
        uint[] memory input = new uint[](6);
        input[0] = uint256(0x0000000000000000000000000000000000000000000000000000000000000032);
        input[1] = uint256(0x07a78f91d95a320d967eb0aaa01092fcd933d15b3acf8f8ffbd4ddcb4c430391);
        input[2] = uint256(0x0000000000000000000000000000000000000000000000000000000000000064);
        input[3] = uint256(0x00000000000000000000000000000000000000000000000000000000000000c8);
        input[4] = uint256(0x000000000000000000000000000000000000000000000000000000000000000c);
        input[5] = uint256(0x0000000000000000000000000000000000000000000000000000000000000001);
        return input;
    }

    function wrongInputFixture(uint256 delta) internal pure returns (uint[] memory) {
        uint[] memory wrongInput = new uint[](6);
        wrongInput[0] = (uint256(0x0000000000000000000000000000000000000000000000000000000000000032) + delta) % SNARK_SCALAR_FIELD;
        wrongInput[1] = uint256(0x07a78f91d95a320d967eb0aaa01092fcd933d15b3acf8f8ffbd4ddcb4c430391);
        wrongInput[2] = uint256(0x0000000000000000000000000000000000000000000000000000000000000064);
        wrongInput[3] = uint256(0x00000000000000000000000000000000000000000000000000000000000000c8);
        wrongInput[4] = uint256(0x000000000000000000000000000000000000000000000000000000000000000c);
        wrongInput[5] = uint256(0x0000000000000000000000000000000000000000000000000000000000000001);
        return wrongInput;
    }

    function wrongArityInputFixture() internal pure returns (uint[] memory) {
        uint[] memory wrongArity = new uint[](7);
        wrongArity[0] = uint256(0x0000000000000000000000000000000000000000000000000000000000000032);
        wrongArity[1] = uint256(0x07a78f91d95a320d967eb0aaa01092fcd933d15b3acf8f8ffbd4ddcb4c430391);
        wrongArity[2] = uint256(0x0000000000000000000000000000000000000000000000000000000000000064);
        wrongArity[3] = uint256(0x00000000000000000000000000000000000000000000000000000000000000c8);
        wrongArity[4] = uint256(0x000000000000000000000000000000000000000000000000000000000000000c);
        wrongArity[5] = uint256(0x0000000000000000000000000000000000000000000000000000000000000001);
        wrongArity[6] = 1;
        return wrongArity;
    }

    function overflowInputFixture() internal pure returns (uint[] memory) {
        uint[] memory overflowInput = new uint[](6);
        overflowInput[0] = SNARK_SCALAR_FIELD;
        overflowInput[1] = uint256(0x07a78f91d95a320d967eb0aaa01092fcd933d15b3acf8f8ffbd4ddcb4c430391);
        overflowInput[2] = uint256(0x0000000000000000000000000000000000000000000000000000000000000064);
        overflowInput[3] = uint256(0x00000000000000000000000000000000000000000000000000000000000000c8);
        overflowInput[4] = uint256(0x000000000000000000000000000000000000000000000000000000000000000c);
        overflowInput[5] = uint256(0x0000000000000000000000000000000000000000000000000000000000000001);
        return overflowInput;
    }

    function assertRejected(
        uint[2] memory a,
        uint[2][2] memory b,
        uint[2] memory c,
        uint[] memory input,
        string memory message
    ) internal view {
        try verifier.verifyProof(a, b, c, input) returns (bool result) {
            assertFalse(result, message);
        } catch {
            assertTrue(true, message);
        }
    }

    /// @notice Valid proof must pass.
    function test_validProof() public view {
        (uint[2] memory a, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        uint[] memory input = validInputFixture();

        bool result = verifier.verifyProof(a, b, c, input);
        assertTrue(result, "valid proof must pass");
    }

    /// @notice Tampered proof (A.x mutated) must not verify.
    /// An off-curve point causes the EVM pairing precompile to revert,
    /// while a still-on-curve but wrong point returns false. Both are correct rejections.
    function test_tamperedProofFails() public view {
        (, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        uint[2] memory a = [
            uint256(0x17adbc59cb371aebb52b371164499a15d42ac2e7062aa70611ce2b4aa0ec2bb0),
            uint256(0x1f3e85cf46074dc42e5100427573853a79ee4266d6d8162af9585fae840c27a0)
        ];
        uint[] memory input = validInputFixture();

        assertRejected(a, b, c, input, "tampered proof must fail closed");
    }

    /// @notice Wrong public input must fail.
    function test_wrongInputFails() public view {
        (uint[2] memory a, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        uint[] memory wrongInput = wrongInputFixture(1);

        assertRejected(a, b, c, wrongInput, "wrong input must fail closed");
    }

    /// @notice Wrong public-input arity must fail closed.
    function test_wrongPublicInputArityFails() public view {
        (uint[2] memory a, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        uint[] memory wrongArity = wrongArityInputFixture();

        assertRejected(a, b, c, wrongArity, "wrong public-input arity must fail closed");
    }

    /// @notice Inputs equal to the scalar field modulus must fail closed.
    function test_scalarFieldOverflowInputFails() public view {
        (uint[2] memory a, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        uint[] memory overflowInput = overflowInputFixture();

        assertRejected(a, b, c, overflowInput, "scalar-field overflow input must fail closed");
    }

    /// @notice Fuzzing a nonzero public-input delta must always fail closed.
    function testFuzz_nonZeroPublicInputDeltaFails(uint256 deltaRaw) public view {
        uint256 delta = deltaRaw % SNARK_SCALAR_FIELD;
        if (delta == 0) {
            delta = 1;
        }
        (uint[2] memory a, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        uint[] memory wrongInput = wrongInputFixture(delta);

        assertRejected(a, b, c, wrongInput, "fuzzed nonzero public-input delta must fail closed");
    }

    /// @notice Fuzzing proof-coordinate tampering must always fail closed.
    function testFuzz_proofCoordinateTamperingFails(uint256 deltaRaw) public view {
        uint256 delta = (deltaRaw % 17) + 1;
        (uint[2] memory a, uint[2][2] memory b, uint[2] memory c) = proofFixture();
        if (a[0] > delta) {
            a[0] = a[0] - delta;
        } else {
            a[0] = a[0] + delta;
        }
        uint[] memory input = validInputFixture();

        assertRejected(a, b, c, input, "fuzzed proof-coordinate tampering must fail closed");
    }
}
