(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)

Inductive t_ProofReputationEvidenceKind : Type :=
| ProofReputationEvidenceKind_QuorumAgreement
| ProofReputationEvidenceKind_QuorumDisagreement
| ProofReputationEvidenceKind_AttestationValid
| ProofReputationEvidenceKind_AttestationInvalid
| ProofReputationEvidenceKind_HeartbeatTimeout
| ProofReputationEvidenceKind_HeartbeatResumed
| ProofReputationEvidenceKind_ThreatDigestCorroborated
| ProofReputationEvidenceKind_ThreatDigestContradicted
| ProofReputationEvidenceKind_ModelFreshnessMatch
| ProofReputationEvidenceKind_ModelFreshnessMismatch.











Definition min_reputation_bound '(_ : unit) : float :=
  (0.0%float : float).

Definition max_reputation_bound '(_ : unit) : float :=
  (1.0%float : float).

Definition neutral_reputation_bound '(_ : unit) : float :=
  (0.25%float : float).

Definition clamp_reputation_unit_interval (value : float) : float :=
  if
    f_lt (value) (min_reputation_bound (tt))
  then
    min_reputation_bound (tt)
  else
    if
      f_gt (value) (max_reputation_bound (tt))
    then
      max_reputation_bound (tt)
    else
      value.

Definition reputation_delta_for (kind : t_ProofReputationEvidenceKind) : float :=
  match kind with
  | ProofReputationEvidenceKind_QuorumAgreement =>
    (0.02%float : float)
  | ProofReputationEvidenceKind_QuorumDisagreement =>
    ((-0.15)%float : float)
  | ProofReputationEvidenceKind_AttestationValid =>
    (0.01%float : float)
  | ProofReputationEvidenceKind_AttestationInvalid =>
    ((-0.20)%float : float)
  | ProofReputationEvidenceKind_HeartbeatTimeout =>
    ((-0.10)%float : float)
  | ProofReputationEvidenceKind_HeartbeatResumed =>
    (0.05%float : float)
  | ProofReputationEvidenceKind_ThreatDigestCorroborated =>
    (0.01%float : float)
  | ProofReputationEvidenceKind_ThreatDigestContradicted =>
    ((-0.05)%float : float)
  | ProofReputationEvidenceKind_ModelFreshnessMatch =>
    (0.005%float : float)
  | ProofReputationEvidenceKind_ModelFreshnessMismatch =>
    ((-0.03)%float : float)
  end.

Definition bounded_reputation_after_decayed_score_spec (decayed_score : float) (kind : t_ProofReputationEvidenceKind) : float :=
  clamp_reputation_unit_interval (f_add (decayed_score) (reputation_delta_for (kind))).

Definition bounded_decay_score_spec (score : float) (decay_factor : float) : float :=
  let clamped_score := clamp_reputation_unit_interval (score) in
  let clamped_decay := clamp_reputation_unit_interval (decay_factor) in
  clamp_reputation_unit_interval (f_add (neutral_reputation_bound (tt)) (f_mul (f_sub (clamped_score) (neutral_reputation_bound (tt))) (clamped_decay))).

Inductive t_ProofDistributedActivationLevel : Type :=
| ProofDistributedActivationLevel_Dormant
| ProofDistributedActivationLevel_Alert
| ProofDistributedActivationLevel_Active
| ProofDistributedActivationLevel_Emergency.





Definition activation_level_rank (level : t_ProofDistributedActivationLevel) : t_u8 :=
  match level with
  | ProofDistributedActivationLevel_Dormant =>
    (0 : t_u8)
  | ProofDistributedActivationLevel_Alert =>
    (1 : t_u8)
  | ProofDistributedActivationLevel_Active =>
    (2 : t_u8)
  | ProofDistributedActivationLevel_Emergency =>
    (3 : t_u8)
  end.

Record ProofBytes2_record : Type :=
  {
    ProofBytes2_f_pair_left : t_u8;
    ProofBytes2_f_pair_right : t_u8;
  }.



#[export] Instance settable_ProofBytes2_record : Settable _ :=
  settable! (Build_ProofBytes2_record) <ProofBytes2_f_pair_left; ProofBytes2_f_pair_right>.

Record ProofBytes4_record : Type :=
  {
    ProofBytes4_f_quad0 : t_u8;
    ProofBytes4_f_quad1 : t_u8;
    ProofBytes4_f_quad2 : t_u8;
    ProofBytes4_f_quad3 : t_u8;
  }.





#[export] Instance settable_ProofBytes4_record : Settable _ :=
  settable! (Build_ProofBytes4_record) <ProofBytes4_f_quad0; ProofBytes4_f_quad1; ProofBytes4_f_quad2; ProofBytes4_f_quad3>.

Record ProofBytes8_record : Type :=
  {
    ProofBytes8_f_oct0 : t_u8;
    ProofBytes8_f_oct1 : t_u8;
    ProofBytes8_f_oct2 : t_u8;
    ProofBytes8_f_oct3 : t_u8;
    ProofBytes8_f_oct4 : t_u8;
    ProofBytes8_f_oct5 : t_u8;
    ProofBytes8_f_oct6 : t_u8;
    ProofBytes8_f_oct7 : t_u8;
  }.









#[export] Instance settable_ProofBytes8_record : Settable _ :=
  settable! (Build_ProofBytes8_record) <ProofBytes8_f_oct0; ProofBytes8_f_oct1; ProofBytes8_f_oct2; ProofBytes8_f_oct3; ProofBytes8_f_oct4; ProofBytes8_f_oct5; ProofBytes8_f_oct6; ProofBytes8_f_oct7>.

Definition u8_eq (left : t_u8) (right : t_u8) : bool :=
  f_eq (f_from (left)) (f_from (right)).

Definition u8_le (left : t_u8) (right : t_u8) : bool :=
  f_le (f_from (left)) (f_from (right)).

Definition array2_eq (left : t_ProofBytes2) (right : t_ProofBytes2) : bool :=
  andb (u8_eq (f_pair_left left) (f_pair_left right)) (u8_eq (f_pair_right left) (f_pair_right right)).

Definition array4_eq (left : t_ProofBytes4) (right : t_ProofBytes4) : bool :=
  andb (andb (andb (u8_eq (f_quad0 left) (f_quad0 right)) (u8_eq (f_quad1 left) (f_quad1 right))) (u8_eq (f_quad2 left) (f_quad2 right))) (u8_eq (f_quad3 left) (f_quad3 right)).

Definition array8_eq (left : t_ProofBytes8) (right : t_ProofBytes8) : bool :=
  andb (andb (andb (andb (andb (andb (andb (u8_eq (f_oct0 left) (f_oct0 right)) (u8_eq (f_oct1 left) (f_oct1 right))) (u8_eq (f_oct2 left) (f_oct2 right))) (u8_eq (f_oct3 left) (f_oct3 right))) (u8_eq (f_oct4 left) (f_oct4 right))) (u8_eq (f_oct5 left) (f_oct5 right))) (u8_eq (f_oct6 left) (f_oct6 right))) (u8_eq (f_oct7 left) (f_oct7 right)).

Definition bounded_gossip_count_spec (pending_len : t_usize) (gossip_max : t_usize) : t_usize :=
  let capped := if
    f_eq (gossip_max) ((0 : t_usize))
  then
    (1 : t_usize)
  else
    gossip_max in
  if
    f_lt (pending_len) (capped)
  then
    pending_len
  else
    capped.

Definition median_activation_level_three (first : t_ProofDistributedActivationLevel) (second : t_ProofDistributedActivationLevel) (third : t_ProofDistributedActivationLevel) : t_ProofDistributedActivationLevel :=
  match (first,second,third) with
  | (ProofDistributedActivationLevel_Dormant,ProofDistributedActivationLevel_Alert,ProofDistributedActivationLevel_Alert)
  | (ProofDistributedActivationLevel_Alert,ProofDistributedActivationLevel_Dormant,ProofDistributedActivationLevel_Alert)
  | (ProofDistributedActivationLevel_Alert,ProofDistributedActivationLevel_Alert,ProofDistributedActivationLevel_Dormant) =>
    ProofDistributedActivationLevel_Alert
  | _ =>
    second
  end.

Definition capped_positive_reputation_gain_basis_points (e_raw_gain_basis_points : t_u16) : t_u16 :=
  (10 : t_u16).

Definition probationary_peer_score_basis_points (e_raw_gain_basis_points : t_u16) : t_u16 :=
  (35 : t_u16).

Definition admission_pow_total_cost (e_peer_count : t_u16) (unit_cost_seconds : t_u16) : t_u16 :=
  unit_cost_seconds.

Definition coordinator_requires_quorum_spec (activation_level : t_ProofDistributedActivationLevel) (e_peer_reputation_basis_points : t_u16) (e_stage_anomaly_streak : t_u32) (e_backend_trust_tier : t_u8) : bool :=
  match activation_level with
  | ProofDistributedActivationLevel_Active
  | ProofDistributedActivationLevel_Emergency =>
    (true : bool)
  | _ =>
    (false : bool)
  end.

Definition attestation_matches_subgraph_digests_spec (expected_output_digest : t_ProofBytes8) (expected_trace_digest : t_ProofBytes8) (found_output_digest : t_ProofBytes8) (found_trace_digest : t_ProofBytes8) : bool :=
  andb (array8_eq (expected_output_digest) (found_output_digest)) (array8_eq (expected_trace_digest) (found_trace_digest)).

Definition digest_prefix8_spec (digest : t_ProofBytes8) : t_ProofBytes8 :=
  digest.

Definition coordinator_two_party_unanimous_quorum_accepts_spec (remote_digest : t_ProofBytes8) (local_digest : t_ProofBytes8) : bool :=
  array8_eq (digest_prefix8_spec (remote_digest)) (digest_prefix8_spec (local_digest)).

Definition distributed_acceptance_surface_spec (activation_level : t_ProofDistributedActivationLevel) (peer_reputation_basis_points : t_u16) (stage_anomaly_streak : t_u32) (backend_trust_tier : t_u8) (attestation_matches : bool) (digests_agree : bool) : bool :=
  andb (andb (attestation_matches) (coordinator_requires_quorum_spec (activation_level) (peer_reputation_basis_points) (stage_anomaly_streak) (backend_trust_tier))) (digests_agree).

Definition hybrid_bundle_surface_complete_spec (public_key_bundle_present : bool) (signature_bundle_present : bool) : bool :=
  andb (public_key_bundle_present) (signature_bundle_present).

Definition hybrid_signature_material_complete_spec (ed25519_present : bool) (ml_dsa_present : bool) : bool :=
  andb (ed25519_present) (ml_dsa_present).

Definition hybrid_admission_pow_identity_bytes_spec (legacy_public_key : t_Vec ((t_u8)) ((t_Global))) (public_key_bundle_bytes : t_Option ((t_Vec ((t_u8)) ((t_Global))))) : t_Vec ((t_u8)) ((t_Global)) :=
  match public_key_bundle_bytes with
  | Option_Some (bundle_bytes) =>
    bundle_bytes
  | Option_None =>
    legacy_public_key
  end.

Definition encrypted_gossip_negotiation_fail_closed_spec (negotiated : bool) (plaintext_present : bool) (encrypted_payload_present : bool) : bool :=
  if
    negotiated
  then
    f_not (plaintext_present)
  else
    andb (f_not (plaintext_present)) (f_not (encrypted_payload_present)).

Definition append_only_memory_chain_after_append (prefix : t_ProofBytes4) (suffix : t_ProofBytes4) : t_ProofBytes8 :=
  ProofBytes8 (f_quad0 prefix) (f_quad1 prefix) (f_quad2 prefix) (f_quad3 prefix) (f_quad0 suffix) (f_quad1 suffix) (f_quad2 suffix) (f_quad3 suffix).

Definition chain_prefix4 (bytes : t_ProofBytes8) : t_ProofBytes4 :=
  ProofBytes4 (f_oct0 bytes) (f_oct1 bytes) (f_oct2 bytes) (f_oct3 bytes).

Definition append_only_memory_prefix_preserved_spec (prefix : t_ProofBytes4) (suffix : t_ProofBytes4) : bool :=
  array4_eq (chain_prefix4 (append_only_memory_chain_after_append (prefix) (suffix))) (prefix).

Definition snapshot_chain_head_roundtrip_spec (exported_head : t_ProofBytes4) (imported_head : t_ProofBytes4) : bool :=
  array4_eq (exported_head) (imported_head).

Definition canonical_intelligence_leaf_pair (first : t_u8) (second : t_u8) : t_ProofBytes2 :=
  if
    u8_le (first) (second)
  then
    ProofBytes2 (first) (second)
  else
    ProofBytes2 (second) (first).

Definition intelligence_root_convergence_under_canonical_ordering_spec (first : t_u8) (second : t_u8) : bool :=
  array2_eq (canonical_intelligence_leaf_pair (first) (second)) (canonical_intelligence_leaf_pair (second) (first)).
